<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jan Vanhove">
<meta name="dcterms.date" content="2025-12-15">

<title>Does multilingualism really protect against accelerated ageing? Some critical comments – Jan Vanhove</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-ef9afd74c936c907027de2a6fad25a4d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<!-- Google tag (gtag.js) -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-7PMKN7SZET"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-7PMKN7SZET');
</script>
<link href="../../site_libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">
<script src="../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<link href="../../site_libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">
<script src="../../site_libs/datatables-binding-0.34.0/datatables.js"></script>
<script src="../../site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="../../site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="../../site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css" rel="stylesheet">
<script src="../../site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js"></script>
<link href="../../site_libs/crosstalk-1.2.2/css/crosstalk.min.css" rel="stylesheet">
<script src="../../site_libs/crosstalk-1.2.2/js/crosstalk.min.js"></script>
<link href="../../site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="../../site_libs/pagedtable-1.1/js/pagedtable.js"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Jan Vanhove</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../support.html"> 
<span class="menu-text">Methods and stats support</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../courses.html"> 
<span class="menu-text">Courses</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../archive.html"> 
<span class="menu-text">Blog archive</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resources.html"> 
<span class="menu-text">Teaching resources</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../publications.html"> 
<span class="menu-text">Publications</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../archive.xml"> <i class="bi bi-rss" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#tldr" id="toc-tldr" class="nav-link active" data-scroll-target="#tldr">tl;dr</a></li>
  <li><a href="#a-first-look" id="toc-a-first-look" class="nav-link" data-scroll-target="#a-first-look">A first look</a>
  <ul class="collapse">
  <li><a href="#data-and-code-availability" id="toc-data-and-code-availability" class="nav-link" data-scroll-target="#data-and-code-availability">Data and code availability</a></li>
  <li><a href="#unjustifiable-causal-claims" id="toc-unjustifiable-causal-claims" class="nav-link" data-scroll-target="#unjustifiable-causal-claims">Unjustifiable causal claims</a></li>
  <li><a href="#sec-bag" id="toc-sec-bag" class="nav-link" data-scroll-target="#sec-bag">Construction of the outcome variable</a></li>
  <li><a href="#country-level-vs-individual-multilingualism" id="toc-country-level-vs-individual-multilingualism" class="nav-link" data-scroll-target="#country-level-vs-individual-multilingualism">Country-level vs individual multilingualism</a></li>
  <li><a href="#on-the-interpretation-of-the-reported-odds-ratios" id="toc-on-the-interpretation-of-the-reported-odds-ratios" class="nav-link" data-scroll-target="#on-the-interpretation-of-the-reported-odds-ratios">On the interpretation of the reported odds ratios</a></li>
  <li><a href="#insufficient-confounder-control" id="toc-insufficient-confounder-control" class="nav-link" data-scroll-target="#insufficient-confounder-control">Insufficient confounder control</a></li>
  <li><a href="#nesting-not-taken-into-account" id="toc-nesting-not-taken-into-account" class="nav-link" data-scroll-target="#nesting-not-taken-into-account">Nesting not taken into account</a></li>
  </ul></li>
  <li><a href="#getting-stuck-in" id="toc-getting-stuck-in" class="nav-link" data-scroll-target="#getting-stuck-in">Getting stuck in</a>
  <ul class="collapse">
  <li><a href="#reproducing-the-odds-ratios" id="toc-reproducing-the-odds-ratios" class="nav-link" data-scroll-target="#reproducing-the-odds-ratios">Reproducing the odds ratios</a></li>
  <li><a href="#missing-info" id="toc-missing-info" class="nav-link" data-scroll-target="#missing-info">Missing info</a></li>
  <li><a href="#drawing-some-plots" id="toc-drawing-some-plots" class="nav-link" data-scroll-target="#drawing-some-plots">Drawing some plots</a></li>
  <li><a href="#refitting-the-models" id="toc-refitting-the-models" class="nav-link" data-scroll-target="#refitting-the-models">Refitting the models</a></li>
  <li><a href="#using-a-continuous-outcome" id="toc-using-a-continuous-outcome" class="nav-link" data-scroll-target="#using-a-continuous-outcome">Using a continuous outcome</a></li>
  </ul></li>
  <li><a href="#now-what" id="toc-now-what" class="nav-link" data-scroll-target="#now-what">Now what?</a></li>
  <li><a href="#software-versions" id="toc-software-versions" class="nav-link" data-scroll-target="#software-versions">Software versions</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Does multilingualism really protect against accelerated ageing? Some critical comments</h1>
  <div class="quarto-categories">
    <div class="quarto-category">correlational studies</div>
    <div class="quarto-category">R</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jan Vanhove </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 15, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>Amoruso et al.’s <a href="https://10.1038/s43587-025-01000-2"><em>Multilingualism protects against accelerated aging in cross-sectional and longitudinal analyses of 27 European countries</em></a> struck a chord with multilingualism enthusiasts. But whenever a study claims to have found something that suits us ideologically or economically, it behooves us, as academics, to take a closer look at it.</p>
<p>So I did.</p>
<p>You can find my critical comments below. Most are not very technical in nature, and many can be identified just by reading the paper and looking at the data and code the authors shared—without actually needing to run it. I believe that these comments should lead to a substantial revision of the published article.</p>
<p>Everything below is based on Amoruso et al.’s article, its supplementary materials, and the data and code provided on the project’s <a href="https://github.com/euroladbrainlat/Biobehavioral-age-gaps-Multilingualism">GitHub</a> page, which I’ve <a href="https://github.com/janhove/Biobehavioral-age-gaps-Multilingualism">forked</a>. I didn’t consult the sources that the authors obtained their data from.</p>
<section id="tldr" class="level2">
<h2 class="anchored" data-anchor-id="tldr">tl;dr</h2>
<ol type="1">
<li><strong>Missing predictors:</strong> The article suggests that 14 predictors were used, but the data and code suggest that only 12 predictors were used.</li>
<li><strong>Missing respondents and countries:</strong> The article claims that the evidence is based on data from 86,149 respondents in 27 European countries. However, the cross-sectional analyses are based on data from only 84,127 respondents in <em>26</em> countries; the longitudinal analyses are based on data from only 81,329 respondents.</li>
<li><strong>Unjustified causal claims:</strong> By their own admission in the discussion section, the authors can’t make any causal claims, but already the title and the abstract make a bold causal claim.</li>
<li><strong>Questionable construction of the outcome variable:</strong> The construction of the outcome variable (“BAGs”) requires some more scrutiny. For the time being, I’ll content myself by pointing out that it is a dichotomised version of a continuous metric.</li>
<li><strong>Conflation of country-level and individual multilingualism:</strong> The multilingual data that the authors used is situated at the country level, but the authors regularly frame their findings in terms of individual multilingualism.</li>
<li><strong>Meaningless odds ratios:</strong> The odds ratios reported in Table 1 are presented without mentioning how the data were coded. A closer look at the Jupyter notebooks reveals that they are essentially meaningless.</li>
<li><strong>Insufficient confounder control:</strong> Several confounders are controlled for in the analyses—but only one at a time.</li>
<li><strong>GDP incorrectly controlled for:</strong> The authors claim to have used per capita GDP as a control variable. Their data and code show that they used GDP—<em>not</em> per capita GDP—instead.</li>
<li><strong>Insufficient accounting for nesting:</strong> The nested nature of the data (respondents in cohorts in countries) isn’t accounted for sufficiently.</li>
</ol>
</section>
<section id="a-first-look" class="level2">
<h2 class="anchored" data-anchor-id="a-first-look">A first look</h2>
<p>The first few critical comments can be raised by just reading the article and comparing the claims made in it to the data and code made available by the authors.</p>
<section id="data-and-code-availability" class="level3">
<h3 class="anchored" data-anchor-id="data-and-code-availability">Data and code availability</h3>
<p>Let’s take a look at how Amoruso et al.’s analytical pipeline is supposed to work.</p>
<p>The dataset <a href="https://github.com/janhove/Biobehavioral-age-gaps-Multilingualism/blob/main/scripts/main/data/data.csv"><code>scripts/main/data/data.csv</code></a> contains 86,149 observations of 14 variables: the respondents’ country, age, sex, and scores and indicators of 11 biobehavioural factors:</p>
<ul>
<li><code>Education</code>,</li>
<li><a href="https://en.wikipedia.org/wiki/Barthel_scale"><code>Barthel</code></a>,</li>
<li><code>Diabetes</code>,</li>
<li><code>Hypertension</code>,</li>
<li><code>Heart_Disease</code>,</li>
<li><code>Physical_activity</code>,</li>
<li><code>Cognition</code>,</li>
<li><code>Well_being_domain</code>,</li>
<li><code>Sleep_problems</code>,</li>
<li><code>Audition_problems</code>,</li>
<li><code>Vision_problems</code>.</li>
</ul>
<p>The authors derived what they dubbed <em>biobehavioural age gaps</em> (‘BAGs’) from this dataset in the Jupyter notebook <code>scripts/main_BAGs_computation.ipynb</code>. Lots of the code in this notebook isn’t really important, but if you look for the string <code>vars_list</code>, you’ll see that the eleven biobehavioural factors as well as the participants’ sex were used as predictors, for a total of twelve predictors.</p>
<p>But their article (particularly Figure 1b) suggests that fourteen predictors were used to derive the BAGs. The factors <em>unhealthy weight</em> and <em>alcohol consumption</em> are mentioned both in this Figure and in the article’s Methods section, but they simply aren’t in the dataset and apparently weren’t used when deriving the BAGs.</p>
<p>Further, the Jupyter notebook doesn’t actually output the BAGs. Instead, two new datasets are fed to the second round of analyses. The first of these new datasets is <a href="https://github.com/janhove/Biobehavioral-age-gaps-Multilingualism/blob/main/scripts/main/data/BAG_OR_cross.csv"><code>scripts/main/data/BAG_OR_cross.csv</code></a>. It contains 84,127 observations of 21 variables. I’ll discuss these variables later. This dataset was used for the cross-sectional analyses carried out in the Jupyter notebook <a href="https://github.com/janhove/Biobehavioral-age-gaps-Multilingualism/blob/main/scripts/main/ORs_cross.ipynb"><code>scripts/main/ORs_cross.ipynb</code></a>. The second is <a href="https://github.com/janhove/Biobehavioral-age-gaps-Multilingualism/blob/main/scripts/main/data/BAG_OR_long.csv"><code>scripts/main/data/BAG_or_long.csv</code></a>, which contains 81,329 observations of 22 variables and was used for the longitudinal analyses carried out in the Jupyter notebook <a href="https://github.com/janhove/Biobehavioral-age-gaps-Multilingualism/blob/main/scripts/main/ORs_long.ipynb"><code>scripts/main/ORs_long.ipynb</code></a>.</p>
<p>The difference in sample sizes is not commented on anywhere. The difference between 86,149 (<code>data.csv</code>) and 84,127 (<code>BAG_OR_cross.csv</code>) is 2,022, which happens to be exactly the size of the Slovak sample. The supplementary Table 6 does not contain any information about Slovakia. But it does contain information about Serbia, which isn’t represented in <code>data.csv</code>. I suspect that the authors blundered when merging the BAGs with the country-level information. Neither the actual BAG computation nor the merging is documented in any of the notebooks, though.</p>
<p>Another 2,798 observations are missing from <code>BAG_OR_long.csv</code>. I didn’t investigate these further; for the time being, I’ll focus on the cross-sectional analyses.</p>
</section>
<section id="unjustifiable-causal-claims" class="level3">
<h3 class="anchored" data-anchor-id="unjustifiable-causal-claims">Unjustifiable causal claims</h3>
<p>As the authors correctly point out in their discussion, their design and analysis do not allow them to establish any causal links between the degree of multilingualism in a country and the extent to which its inhabitants show signs of accelerated ageing. Unfortunately, they don’t seem to have kept this insight in mind when they came up with the title (“Multilingualism protects…”) and the abstract (“These results underscore the protective role of multilingualism…”).</p>
<p>Further, the authors write</p>
<blockquote class="blockquote">
<p>“[R]andomized controlled trials could explicitly manipulate multilingualism and directly assess its effects on aging clocks.”</p>
</blockquote>
<p>Could they really, though?</p>
</section>
<section id="sec-bag" class="level3">
<h3 class="anchored" data-anchor-id="sec-bag">Construction of the outcome variable</h3>
<p>The study’s outcome variable was the presence or absence of “accelerated ageing”. Let’s see how this outcome variable was constructed.</p>
<p>First, the authors gathered data on individual “biobehavioural” factors (see <code>data.csv</code>). These are based on self-reports and are fairly coarse. For example, the variable <code>Hypertension</code> is simply the yes/no response to whether a physician has ever told the respondent that their blood pressure was too high. The list of specific questions can be found in the supplementary materials.</p>
<p>Then, they used the dataset to fit a model with the respondents’ age as the outcome variable and all of these biobehavioural factors as predictors. The model itself is gradient boosting, but that is not especially important conceptually. What is important is that the model is able to pick up on nonlinearities and interactions. The model’s hyperparameters were estimated from the data, and a couple of different cross-validation techniques were used. For our present purposes, I’m going to focus on the <em>leave one country out</em> cross-validation, because it makes the most sense to me. What this means is that 27 models predicting age from biobehavioural factors were fitted, with each leaving out the data from another country.</p>
<p>Next, the models fitted were used to predict the age of the inhabitants of the country that was left out when fitting them. That is, the Belgian respondents’ ages were predicted on the basis of the model fitted to the data from the respondents in the other 26 countries.</p>
<p>Then, the authors computed, for each respondent, <span class="math display">\[\texttt{GAP} := \textrm{predicted age} - \textrm{actual age},\]</span> that is, the negative model residuals. As the authors correctly point out, though, the predictive model will tend to underestimate the age of the oldest respondents and overestimate the age of the youngest respondents. To account for this phenomenon, they fitted linear models with <span class="math inline">\(\texttt{GAP}\)</span> as the outcome and the participants’ actual age as the predictor; let’s call the predicted values of model the predicted <span class="math inline">\(\texttt{GAP}\)</span> values. They then defined <span class="math display">\[\textrm{corrected } \texttt{GAP} := \texttt{GAP} - \textrm{predicted } \texttt{GAP}.\]</span></p>
<p>Finally, the authors defined the variable “biobehavioural age gap” (<span class="math inline">\(\texttt{BAG}\)</span>) as <span class="math display">\[\texttt{BAG} := \begin{cases}1, &amp;\textrm{if corrected } \texttt{GAP} &gt; 0, \\ 0, &amp; \textrm{otherwise}.\end{cases}\]</span> I’m always somewhat skeptical when the input to one statistical model is the output of another one. The <span class="math inline">\(\texttt{BAG}\)</span> values that serve as the outcome variable in the models testing for a multilingualism effect are themselves the dichotomised output of another statistical model whose input, in turn, is the input the output of yet another statistical model. At the very least, the literal meaning of these <span class="math inline">\(\texttt{BAG}\)</span> values is highly convoluted.</p>
<p>Further, I do not see why the corrected <span class="math inline">\(\texttt{GAP}\)</span>s had to be dichotomised in the first place, thereby losing the distinction between a corrected <span class="math inline">\(\texttt{GAP}\)</span> of, say, half a year and one of 12 years. The authors write that these dichotomous variables were created because otherwise no odds ratios (and relative risks) could be computed. But this is hardly a satisfactory justification; it’s a bit like scattering dust throughout your living room before vacuum cleaning it as otherwise there would be no dust to get rid of.</p>
<p>Lastly, note that any given respondent’s <span class="math inline">\(\texttt{BAG}\)</span> value doesn’t just depend on this respondent’s biobehavioural data: both the model to compute their raw <span class="math inline">\(\texttt{GAP}\)</span> value as well as the one to compute their corrected <span class="math inline">\(\texttt{GAP}\)</span> value are based on the data from the respondents in all the other countries. In fact, you’d expect roughly half the respondents to have a positive <span class="math inline">\(\texttt{GAP}\)</span> value.</p>
</section>
<section id="country-level-vs-individual-multilingualism" class="level3">
<h3 class="anchored" data-anchor-id="country-level-vs-individual-multilingualism">Country-level vs individual multilingualism</h3>
<p>The authors use country-level data on multilingualism, namely the estimated percentage of monolinguals in the country, the estimated percentage of people in the country who know (exactly) one additional language, those who know (exactly) two additional languages, and those who know at least three additional languages. Throughout their article, though, they move back and forth between interpreting country-level and individual-level interpretations. For instance, they write</p>
<blockquote class="blockquote">
<p>“In the cross-sectional analysis, monolinguals (that is, those speaking only their mother tongue) were 2.11 times more likely to experience accelerated aging (…).”</p>
</blockquote>
<p>and</p>
<blockquote class="blockquote">
<p>“Individuals speaking one additional language were 1.11 less likely to develop accelerated aging (…), those speaking two additional languages were 1.25 times less likely (…), and those speaking three or more additional languages were 1.41 less likely (…).”</p>
</blockquote>
<p>Again, in the discussion they point out that their data are situated at the country level, which limits their ability to draw conclusions about individual multilingualism. A cleaner and more consistent choice of wording in the title and throughout the article would have been preferable.</p>
</section>
<section id="on-the-interpretation-of-the-reported-odds-ratios" class="level3">
<h3 class="anchored" data-anchor-id="on-the-interpretation-of-the-reported-odds-ratios">On the interpretation of the reported odds ratios</h3>
<p>Now that we’ve established that the multilingualism data are situated at the country level, what are we to make of the odds ratio of 2.11 in the claim that “monolinguals … were 2.11 times more likely to experience accelerated aging”?</p>
<p>Their Python code (<code>ORs_cross.ipynb</code>) shows that the authors scaled the multilingualism data to a range from 0.05 to 0.95. The highest degree of country-level monolingualism was 63.2, the lowest was 2.86. So, with <span class="math inline">\(p\)</span> the percentage of monolinguals in a given country, the scaled monolingualism variable <span class="math inline">\(s(p)\)</span> becomes</p>
<p><span class="math display">\[s(p) = \left(\frac{p - 2.86}{63.2 - 2.86}\right)(0.95 - 0.05) +0.05.\]</span> The odds ratio output by the model is the estimated ratio <span class="math display">\[\textrm{OR(monolingualism)} = \frac{\textrm{odds of accelerated ageing if } s(p) = 1}{\textrm{odds of accelerated ageing if } s(p) = 0}.\]</span> As some basic algebra reveals, <span class="math inline">\(s(p) = 0\)</span> corresponds to a percentage of monolinguals of <span class="math display">\[\frac{-0.05}{0.95 - 0.05}(63.2-2.86) + 2.86 = -0.49,\]</span> that is negative (!) 49 monolinguals per 10,000 inhabitants. Similarly, <span class="math inline">\(s(p) = 1\)</span> corresponds to a percentage of monolinguals of <span class="math display">\[\frac{0.95}{0.95 - 0.05}(63.2-2.86) + 2.86 = 66.55,\]</span> that is 6,655 monolinguals for every 10,000 inhabitants.</p>
<p>What the odds ratio of 2.11 for monolingualism means, then, is that the model estimates that the inhabitants of a country with 6,655 monolinguals for every 10,000 inhabitants are 2.11 times more likely to show signs of accelerated ageing compared to the inhabitants of a country with negative 49 monolinguals per 10,000 inhabitants.</p>
<p>It would have been more sensible to set the baseline at 0% monolinguals and have the OR refer to a difference in monolingualism of, say, 1 or 10 percentage points.</p>
<p>The interpretation of the other odds ratios suffers from the same problem, of course. Further, these other odds ratios aren’t too useful for an additional reason Take, for example, the following statement:</p>
<blockquote class="blockquote">
<p>“speaking one foreign language were [sic.] 1.3 less likely (…).”</p>
</blockquote>
<p>The highest percentage of speakers of exactly one additional language was 62.08; the lowest was 9.48. The same computation as above shows that this odds ratio has the following interpretation: According to the model, inhabitants of a country with 6,500 speakers of exactly one additional language per 10,000 inhabitants are 1.3 times less likely to show signs of accelerated ageing compared to the inhabitants of a country with only 656 speakers of exactly one additional language per 10,000 inhabitants.</p>
<p>Crucially, a country with 6,500 speakers of exactly one additional language per 10,000 inhabitants isn’t necessarily more multilingual than a country with only 656 speakers of exactly one additional language per 10,000 inhabitants: In the 2016 data, Luxembourg only had 16.2% speakers of exactly one additional language compared to, say, Austria’s 49.6%. But Luxembourg had 72% speakers of at least three additional languages compared to Austria’s 13.4%—more speakers of exactly one additional language doesn’t mean that the country is more multilingual!</p>
<p>The same remark goes for the analyses concerning the percentage of speakers of exactly two additional languages or of speakers of at least three additional languages.</p>
<p>Further, the result that “individuals (sic.) speaking at least one additional foreign language were 2.17 times less likely (…) to experience accelerated ageing” is superfluous: if we already know the odds ratio for the degree of monolingualism, we also know the odds ratio for the degree of multilingualism: it must be the inverse. The fact that it isn’t <em>exactly</em> the inverse in this report is something I will come back to when reproducing the analyses.</p>
<p>Finally, the operative phrase in the interpretations above is <em>according to the model</em>. While the article contains quite a few graphs, none shows a data plot for the association between degree of mono/multilingualism versus prevalence of accelerated ageing. It is therefore entirely possible that the actual relationship between these two variables is nonlinear.</p>
<p>Incidentally, for some reason or other, the notebook <code>ORs_cross.ipynb</code> doesn’t actually fit the logistic regression models that the authors claim to have fitted: They fit log-linear regression models. Moreover, for reasons unspecified, the data were split up into a training set and a test set, but the test set was never used for anything. This isn’t mentioned anywhere in the article, either.</p>
</section>
<section id="insufficient-confounder-control" class="level3">
<h3 class="anchored" data-anchor-id="insufficient-confounder-control">Insufficient confounder control</h3>
<p>The authors write in the abstract that the “[e]ffects persisted after adjusting for linguistic, physical, social and sociopolitical exposomes.” This is true but also easily misunderstood: They only controlled for one exposome at a time. Hence, it is possible that the mono/multilingualism variables acted as a proxy for some of the exposomes that weren’t considered in the analysis.</p>
<p>Further, the authors write that one of the exposomes taken into consideration was the GDP <em>per capita</em>. However, the GDP variable in <code>BAG_OR_cross.csv</code> ranges from 13.5 billion (in nominal USD?) to about 3.9 trillion (in nominal USD?). I suspect the first figure is for Malta in 2017 and the second for Germany in 2019. But nowhere in their analysis code do they compute the <em>per capita</em> GDP.</p>
</section>
<section id="nesting-not-taken-into-account" class="level3">
<h3 class="anchored" data-anchor-id="nesting-not-taken-into-account">Nesting not taken into account</h3>
<p>The logistic models fitted in <code>ORs_cross.ipynb</code> don’t take the nested nature of the data into account: the respondents’ data were collected in different waves in different countries. It is quite plausible that the reported confidence intervals would be considerably wider once this nesting is properly accounted for. Since the predictors in these models are situated at the country level (e.g., country-level multilingualism and GDP), simple data aggregation would be a viable approach.</p>
</section>
</section>
<section id="getting-stuck-in" class="level2">
<h2 class="anchored" data-anchor-id="getting-stuck-in">Getting stuck in</h2>
<p>Now let’s get our hands dirty and try to (a) reproduce the authors’ findings using the code and data they provided and (b) improve on these analyses. In doing so, I will assume for the time being that their computation of the BAGs (the outcome variable) makes sense—even though I believe it ought to be scrutinised further. I will focus entirely on the cross-sectional analyses carried out in <code>ORs_cross.ipynb</code>.</p>
<p>I carried out part of the reproduction in Python, using a stripped-down and refactored version of the notebook that the authors shared in their GitHub repository; I’ll link to my Python script when we need it. I additionally also used R.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load packages and set plotting theme</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">show.signif.stars =</span> <span class="cn">FALSE</span>, <span class="at">tidyverse.quiet =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DT)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_bw</span>(<span class="dv">12</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<section id="reproducing-the-odds-ratios" class="level3">
<h3 class="anchored" data-anchor-id="reproducing-the-odds-ratios">Reproducing the odds ratios</h3>
<p>I tried to reproduce the first couple of odds ratios reported in the authors’ Table 1, namely those reported for the models without additional covariates. The table caption says that these were estimated using logistic regression models. In their Python code (<code>ORs_cross.ipynb</code>), however, they fit log-link models, not logistic models:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode default code-with-copy"><code class="sourceCode default"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>sm.GLM(y_train, X_train_scaled, family=sm.families.Binomial(link=sm.families.links.log())).fit()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The output of such models can still be converted to odds ratios, though. When I run the <code>ORs_cross.ipynb</code> notebook and convert the parameters of the log-linear models fitted in it to odds ratio, I obtain slightly different results from the ones reported in the article, see <a href="#tbl-odds-ratios" class="quarto-xref">Table&nbsp;1</a>.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>log_to_OR <span class="ot">&lt;-</span> <span class="cf">function</span>(intercept, slope) {</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  odds0 <span class="ot">&lt;-</span> <span class="fu">exp</span>(intercept) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">exp</span>(intercept))</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  odds1 <span class="ot">&lt;-</span> <span class="fu">exp</span>(intercept <span class="sc">+</span> slope) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">exp</span>(intercept <span class="sc">+</span> slope))</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  odds1 <span class="sc">/</span> odds0</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">Predictor =</span> <span class="fu">c</span>(<span class="st">"Mono"</span>, <span class="st">"One"</span>, <span class="st">"Two"</span>, <span class="st">"Three"</span>, <span class="st">"Total"</span>),</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">Intercept =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.916226</span>, <span class="sc">-</span><span class="fl">0.699792</span>, <span class="sc">-</span><span class="fl">0.628158</span>, <span class="sc">-</span><span class="fl">0.704455</span>, <span class="sc">-</span><span class="fl">0.527900</span>),</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">Slope =</span> <span class="fu">c</span>(<span class="fl">0.388409</span>, <span class="sc">-</span><span class="fl">0.145554</span>, <span class="sc">-</span><span class="fl">0.343348</span>, <span class="sc">-</span><span class="fl">0.226496</span>, <span class="sc">-</span><span class="fl">0.388527</span>),</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">OR reported</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="fl">2.11</span>, <span class="fl">0.75</span>, <span class="fl">0.54</span>, <span class="fl">0.67</span>, <span class="fl">0.47</span>)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">OR computed</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">log_to_OR</span>(Intercept, Slope)) <span class="sc">|&gt;</span> </span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_if</span>(is.numeric, round, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-odds-ratios" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-odds-ratios-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: The intercept and slope parameter for the log-linear models without any co-variables fitted in <code>ORs_cross.ipynb</code>, the odds ratios reported in Amoruso et al.’s Table 1, and the ORs recomputed from the log-linear models.
</figcaption>
<div aria-describedby="tbl-odds-ratios-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["Predictor"],"name":[1],"type":["chr"],"align":["left"]},{"label":["Intercept"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Slope"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["OR reported"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["OR computed"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"Mono","2":"-0.916","3":"0.388","4":"2.11","5":"2.157"},{"1":"One","2":"-0.700","3":"-0.146","4":"0.75","5":"0.763"},{"1":"Two","2":"-0.628","3":"-0.343","4":"0.54","5":"0.532"},{"1":"Three","2":"-0.704","3":"-0.226","4":"0.67","5":"0.665"},{"1":"Total","2":"-0.528","3":"-0.389","4":"0.47","5":"0.463"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
</figure>
</div>
</div>
<p>There could be several reasons for the discrepancies between the reported odds ratios and the ones that are computed using their code. I’m not going to speculate on these reasons.</p>
<p>As already mentioned above, the authors rescaled the predictor variables (<code>Mono</code>, <code>One</code>, etc.) to a range from 0.05 and 0.95 and split off an used test set from the main data. I don’t see any added value in these steps. Further, I do not see much value in the results other than the one for either the <span class="math inline">\(\texttt{Mono}\)</span> or the <span class="math inline">\(\texttt{Total}\)</span> variable; the former is the percentage of monolinguals, the latter the percentage of non-monolinguals.</p>
<p>Next, let us take a closer look at some of the other results in their Table 1. These concern logistic regression models for which another predictor was taken into account. Because of the issue identified with the GDP variable above, I’ve focused on reproducing the findings for this analysis. As <a href="#tbl-OR-gdp" class="quarto-xref">Table&nbsp;2</a> shows, the results in the authors’ Table 1 are indeed roughly consistent with the models fitted in <code>ORs_cross.pynb</code> in which GDP (<em>not</em> per capita GDP!) was used as a control variable. Again, there could be several reasons for the slight discrepancies; I’ll refrain from speculating on these.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Predictor =</span> <span class="fu">c</span>(<span class="st">"Mono"</span>, <span class="st">"One"</span>, <span class="st">"Two"</span>, <span class="st">"Three"</span>, <span class="st">"Total"</span>),</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Intercept =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.905862</span>, <span class="sc">-</span><span class="fl">0.703005</span>, <span class="sc">-</span><span class="fl">0.618220</span>, <span class="sc">-</span><span class="fl">0.690530</span>, <span class="sc">-</span><span class="fl">0.512324</span>),</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Slope =</span> <span class="fu">c</span>(<span class="fl">0.393635</span>, <span class="sc">-</span><span class="fl">0.155711</span>, <span class="sc">-</span><span class="fl">0.348275</span>, <span class="sc">-</span><span class="fl">0.240334</span>, <span class="sc">-</span><span class="fl">0.393752</span>),</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">OR reported</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="fl">2.16</span>, <span class="fl">0.74</span>, <span class="fl">0.53</span>, <span class="fl">0.65</span>, <span class="fl">0.46</span>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">OR computed</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">log_to_OR</span>(Intercept, Slope)) <span class="sc">|&gt;</span> </span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_if</span>(is.numeric, round, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-OR-gdp" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-OR-gdp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: The intercept and slope parameter for the log-linear models with GDP as the co-variable fitted in <code>ORs_cross.ipynb</code>, the odds ratios reported in Amoruso et al.’s Table 1, and the ORs recomputed from the log-linear models.
</figcaption>
<div aria-describedby="tbl-OR-gdp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["Predictor"],"name":[1],"type":["chr"],"align":["left"]},{"label":["Intercept"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Slope"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["OR reported"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["OR computed"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"Mono","2":"-0.906","3":"0.394","4":"2.16","5":"2.203"},{"1":"One","2":"-0.703","3":"-0.156","4":"0.74","5":"0.750"},{"1":"Two","2":"-0.618","3":"-0.348","4":"0.53","5":"0.525"},{"1":"Three","2":"-0.691","3":"-0.240","4":"0.65","5":"0.647"},{"1":"Total","2":"-0.512","3":"-0.394","4":"0.46","5":"0.454"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="missing-info" class="level3">
<h3 class="anchored" data-anchor-id="missing-info">Missing info</h3>
<p>Important information is missing from the dataset <code>BAG_OR_cross.csv</code>, on which the cross-sectional analyses are based: it doesn’t specify the country and the wave of data collection that the respondents belong to, nor does it contain any information about the respondents’ age or the corrected <span class="math inline">\(\texttt{GAP}\)</span> value. Only country/cohort level covariates and the binary <span class="math inline">\(\texttt{BAG}\)</span> variable are available; the latter is called <code>GAP_bin</code> in the dataset. Note that the <code>ID</code> variable is just the row number (using zero-based indexing); it doesn’t actually allow you to link a particular respondent’s data in one dataset to their data in another dataset.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>d_cross <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"BAG_OR_cross.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>There are 97 unique combinations of country- and cohort-level predictors.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>country_cohort <span class="ot">&lt;-</span> d_cross <span class="sc">|&gt;</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>ID, <span class="sc">-</span>GAP_bin) <span class="sc">|&gt;</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by_all</span>() <span class="sc">|&gt;</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co"># write_csv(country_cohort, "country_cohort.csv")</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Using the information provided in the supplementary materials, I could piece together which of these combinations corresponded to which country and wave of data collection. I also had ChatGPT create a table with the approximate population of each country in each year of data collection. I’ve put this information in the dataset <a href="country_cohort.csv"><code>country_cohort.csv</code></a>. Let’s add it to the dataset for the cross-sectional analyses. While we’re at it, let’s compute per capita GDP, too, expressed in 10,000 units of whatever currency the GDP variable is expressed in.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>country_cohort <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"country_cohort.csv"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">datatable</span>(country_cohort)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="datatables html-widget html-fill-item" id="htmlwidget-6140ad95d013fb206c58" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-6140ad95d013fb206c58">{"x":{"filter":"none","vertical":false,"data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60","61","62","63","64","65","66","67","68","69","70","71","72","73","74","75","76","77","78","79","80","81","82","83","84","85","86","87","88","89","90","91","92","93","94","95","96","97"],["Austria","Austria","Belgium","Belgium","Belgium","Belgium","Belgium","Bulgaria","Bulgaria","Croatia","Croatia","Croatia","Cyprus","Cyprus","Czechia","Czechia","Czechia","Czechia","Czechia","Denmark","Denmark","Denmark","Denmark","Denmark","Estonia","Estonia","Estonia","Estonia","Estonia","Finland","Finland","France","France","France","France","France","Germany","Germany","Germany","Germany","Germany","Greece","Greece","Greece","Hungary","Hungary","Hungary","Italy","Italy","Italy","Italy","Italy","Latvia","Latvia","Lithuania","Lithuania","Luxembourg","Luxembourg","Luxembourg","Luxembourg","Malta","Malta","Netherlands","Netherlands","Netherlands","Poland","Poland","Poland","Poland","Portugal","Portugal","Portugal","Romania","Romania","Slovenia","Slovenia","Slovenia","Slovenia","Slovenia","Spain","Spain","Spain","Spain","Spain","Sweden","Sweden","Sweden","Sweden","Sweden","Switzerland","Switzerland","Switzerland","Switzerland","Switzerland","Austria","Austria","Austria"],[2011,2013,2011,2013,2017,2015,2019,2017,2019,2018,2019,2020,2019,2017,2011,2013,2015,2017,2019,2011,2013,2019,2017,2015,2019,2017,2015,2013,2011,2017,2019,2011,2017,2016,2013,2019,2011,2014,2019,2017,2016,2019,2017,2015,2011,2019,2017,2019,2017,2015,2013,2011,2019,2017,2017,2019,2013,2015,2019,2017,2017,2019,2011,2013,2019,2019,2017,2015,2011,2011,2016,2015,2019,2017,2019,2017,2015,2013,2011,2019,2017,2016,2013,2011,2011,2013,2015,2016,2019,2011,2013,2016,2017,2015,2017,2015,2019],[21.9,18.66,42.1,33.86,21.5833333333333,25.62,21.75,50.7166666666667,51.15,27.72,25.7833333333333,23.75,9.300000000000001,10.1,30.9,26.94,22.98,21.1833333333333,21.55,5.90000000000001,5.22,7,5.13333333333334,4.54,6.65,8.08333333333333,9.94,12.22,14.5,7.96666666666667,7.9,41.2,37.0166666666667,40.16,40.68,31.25,21.5,21.42,16.8,19.8,21.34,31.15,32.7166666666667,35.18,63.2,54.45,56.55,33.05,33.6833333333333,35.22,37.66,40.1,4.6,4.33333333333334,4.51666666666667,4.55,2.86,4.62,5.5,5.5,10.2333333333333,14.3,13.9,13.82,10.35,30,31.9333333333333,33.94,38.1,41.5,30.85,33.1,57.7,62.0333333333333,9.949999999999999,13.9166666666667,14.24,10.92,7.59999999999999,44.75,45.45,46.42,47.66,48.9,8.199999999999999,6.28,4.36000000000001,3.51666666666667,3.75,12.1,10.58,8.300000000000001,8.300000000000001,9.06,13.4333333333333,15.42,12.7],[50.5,50.14,13.8,15.56,19.35,17.32,21.65,32.8333333333333,33.5,44.1,46.05,47.75,61.85,62.0833333333333,39.6,41.64,43.68,45.0166666666667,45.65,26.3,27.74,29.55,29.7833333333333,29.18,22.85,25.2166666666667,25.94,25.02,24.1,16.4166666666667,18.05,34.9,35.25,35.3,35.1,34.95,41.9,41.82,41.55,41.65,41.74,51.75,49.5833333333333,47.4,25.9,29.6,28.9333333333333,39.55,40.9166666666667,41.2,40.4,39.6,30.05,32.4833333333333,42.1333333333333,40.6,9.48,13.96,16.75,16.3833333333333,34.8666666666667,39.8,25.2,26.6,24.7,46.2,45.4,43.74,38.7,26.6,29.25,28.44,29.95,26.45,18.65,20.0166666666667,19.56,17.28,15,34.7,34.7666666666667,34.64,34.32,34,31.6,37.32,43.04,46.7166666666667,48.35,20.9,20.42,19.7,19.7,19.94,50.1666666666667,49.78,51.3],[18.9,20.66,23.5,27.5,32.8333333333333,31.5,31.5,13.2833333333333,12.45,21.7,22.0333333333333,22.5,20.75,20.45,22.4,24.2,26,26.5,25.7,43.1,42.34,37.1,39.8333333333333,41.58,41.15,39.7833333333333,38.3,36.7,35.1,31.9166666666667,32.55,19.2,21.7166666666667,19.92,19.56,24.95,26.3,26.42,28.2,27.1333333333333,26.54,14.2,14.9333333333333,14.68,9.199999999999999,12.65,11.6166666666667,21.45,20.55,19.4,18,16.6,50.95,49.85,40.45,43.35,24.04,26.08,25.1,26.4333333333333,40.0833333333333,33.85,37.1,37.1,34.55,19.85,19.4166666666667,19.2,19.2,20.5,24.8333333333333,23.94,11.25,10.55,24.4,25.2666666666667,27.08,29.84,32.6,15.05,14.55,13.96,13.28,12.6,29.7,30.5,31.3,31.8,32,34.2,34.72,35.5,35.5,35.24,23.5166666666667,22.42,23.95],[8.800000000000001,10.64,20.6,23.12,26.3333333333333,25.64,25.2,3.16666666666667,2.9,6.48,6.13333333333333,6,8.1,7.36666666666667,7.1,7.22,7.34,7.3,7.1,24.7,24.66,26.35,25.1833333333333,24.62,29.35,26.9166666666667,25.82,26.06,26.3,43.7666666666667,41.5,4.6,6.01666666666667,4.6,4.6,8.85,10.3,10.34,13.5,11.4333333333333,10.38,2.9,2.76666666666667,2.76,1.7,3.25,2.88333333333333,6,4.93333333333333,4.26,3.98,3.7,14.35,13.25,12.9666666666667,11.5,63.68,55.36,52.65,51.6833333333333,14.8166666666667,12.05,23.7,22.46,30.4,3.9,3.16666666666667,3.04,4,11.5,15.0833333333333,14.54,1.05,0.95,47,40.8,39.14,42.02,44.9,5.5,5.3,5.06,4.78,4.5,30.5,25.9,21.3,17.95,15.85,32.9,34.34,36.5,36.5,35.78,12.9666666666667,12.48,12.1],[78.2,81.44,57.9,66.18000000000001,78.51666666666669,74.45999999999999,78.34999999999999,49.2833333333333,48.85,72.28,74.2166666666667,76.25,90.7,89.90000000000001,69.09999999999999,73.06,77.02,78.81666666666671,78.45,94.09999999999999,94.73999999999999,93,94.8,95.38,93.34999999999999,91.9166666666667,90.06,87.78,85.5,92.09999999999999,92.09999999999999,58.7,62.9833333333333,59.82,59.26,68.75,78.5,78.58,83.25,80.2166666666667,78.66,68.84999999999999,67.2833333333333,64.84,36.8,45.5,43.4333333333333,67,66.40000000000001,64.86,62.38,59.9,95.34999999999999,95.5833333333333,95.55,95.45,97.2,95.40000000000001,94.5,94.5,89.76666666666669,85.7,86,86.16,89.65000000000001,69.95,67.98333333333331,65.98,61.9,58.6,69.1666666666667,66.92,42.25,37.95,90.05,86.0833333333333,85.78,89.14,92.5,55.25,54.6166666666667,53.66,52.38,51.1,91.8,93.72,95.64,96.4666666666667,96.2,88,89.48,91.7,91.7,90.95999999999999,86.65000000000001,84.68000000000001,87.34999999999999],[0.580798724495706,0.612023796245296,0.649688601313795,0.700628907893829,0.706897645940199,0.707102146035726,0.706849627676817,0.352614298236295,0.303553046129488,0.467967507068733,0.416864850253943,0.431016090818687,0.518348976820751,0.508491840511581,0.57549588640669,0.584577168435884,0.570518373201654,0.577188066544074,0.540472231051049,0.738176215450677,0.74657664198943,0.752485295197633,0.740385625688507,0.739032644332725,0.739203700977757,0.777452744562331,0.693769165828153,0.630803479120532,0.658084727585558,0.728673272271674,0.758023657759448,0.611129847259675,0.6858322043898381,0.655835730660721,0.641501908198259,0.676407211089183,0.77243104419727,0.745797455655099,0.770107575389864,0.766072575949743,0.753989697066441,0.624962334324878,0.600759765179868,0.561763660628951,0.594386860859112,0.304635246429338,0.338991800480261,0.556318557239642,0.546244186397989,0.512581775838313,0.508190933959124,0.479988256685893,0.460142815797487,0.435598392763092,0.53116995027916,0.555819916901424,0.5263565565327391,0.543416709660275,0.517131905398845,0.514126776151578,0.449599553570998,0.446751589672481,0.737235578642613,0.696354270626467,0.664668829711179,0.49782387612697,0.555375343128699,0.598994507286445,0.505934763256214,0.580249142405441,0.673617029749779,0.636048131252454,0.402825936891591,0.331745304470748,0.629923544669341,0.657733489884756,0.629271354675515,0.658809332458844,0.682417292755148,0.734383399500478,0.6527307646667,0.646993119355833,0.667837241913958,0.653347152140712,0.78567488229906,0.796084282709819,0.785481024563946,0.7800436914014161,0.773035390304849,0.611132730821539,0.628778047658607,0.588084828450292,0.6138920371265471,0.631247208523444,0.632453993911947,0.607060203159468,0.623048696556997],[0.635756190801168,0.642925171296124,0.624768661487405,0.690016529252265,0.689837360594835,0.689837360594835,0.677363381641823,0.388660146611258,0.293015165082719,0.525543081308283,0.438108939455045,0.451121429551038,0.5915234651372731,0.583252419162839,0.6158312562462021,0.642258909503217,0.585529149167005,0.592882025943423,0.5490458664733,0.689799021050047,0.685316251411818,0.672756806208638,0.676340179357228,0.676340179357228,0.727283440292095,0.8047241517429971,0.695410411451305,0.682354469560685,0.680845255816266,0.660226364859378,0.657658280769555,0.671168277915854,0.6810742624174519,0.685307863306434,0.685307863306434,0.6810742624174519,0.863909245361325,0.797974165627674,0.834768258645469,0.834768258645469,0.797974165627674,0.714164243353444,0.706601247274399,0.703967917135623,0.727318365636899,0.204891265688374,0.290216734980804,0.612556195711775,0.6146981559719,0.578025922647491,0.578025922647491,0.577895516964031,0.336982179916302,0.346251549467754,0.57439773141487,0.575727286586563,0.547656308439092,0.547656308439092,0.530762992659873,0.547656308439092,0.424125475561718,0.424125475561718,0.72759410351785,0.675827165309369,0.657048451587722,0.564226860220629,0.690999880199329,0.762561321547621,0.683710672823743,0.696133748675272,0.757918821554342,0.727363720529281,0.421790720149067,0.382485611816826,0.57011900087543,0.6270512315353,0.596332366462193,0.681565991451114,0.74997133300007,0.767573520526197,0.673645401668012,0.689245859267658,0.7333167518756269,0.732521695817834,0.731432107600651,0.737716998227077,0.71893276089067,0.71893276089067,0.7008672234289099,0.659838779772511,0.677075975714684,0.580293266325754,0.629238309272155,0.6601432502821321,0.630783885407954,0.642925171296124,0.612824094029719],[0.50752210275509,0.570821962844191,0.682915187748982,0.71477874608258,0.729644693067351,0.730121859956913,0.746164622390143,0.304553167069678,0.317603554191847,0.391200074749334,0.388539397985808,0.404208972508887,0.420782992398723,0.408811068976571,0.52171539328734,0.5076681803461059,0.550504005247852,0.5562627873449409,0.529040717154713,0.802679141318183,0.8282571627595779,0.858789947182959,0.825779554130212,0.822622597633387,0.755097381891972,0.741090868321443,0.691580838330617,0.562068825200328,0.6277373566112791,0.81993581548807,0.891844160412638,0.53107860638477,0.692176127019685,0.61653955379977,0.583093968054025,0.670184475984824,0.650460109311862,0.676228509024998,0.683893331049057,0.674478332355441,0.695343738984797,0.506026455620124,0.459637789053827,0.372157985286723,0.417144854488729,0.437627220750622,0.404025221146204,0.481335039276799,0.454972226966108,0.425322913426076,0.415077615707969,0.349445242981708,0.6243569969724,0.554727517156876,0.473532908764879,0.529276757321238,0.497956887324268,0.537763911288519,0.49895712238414,0.469420733101561,0.483564990916704,0.476919741820165,0.750090878808964,0.723723744382597,0.674829333875788,0.40928656400209,0.374542627034525,0.380905421604876,0.268900217166174,0.425736334045665,0.561214640677027,0.514294012216685,0.377539559214956,0.264091561342644,0.709662936394557,0.698643167684032,0.673190005626612,0.62846712046915,0.5923452390952511,0.690129904799519,0.624844581998285,0.590656132806732,0.580531228631732,0.547781093904549,0.857998581896938,0.873907328686809,0.87421204279498,0.861524932082411,0.869259612806101,0.546191332220243,0.564380810250504,0.598473577949677,0.593430340932404,0.5927191528451931,0.634680805250606,0.559240245643925,0.6366814999267],[431685217367.511,430190979705.962,523330354138.133,521791015247.06,502764720556.354,462335574841.484,535865804349.803,59309748166.1179,68881010245.5498,51011170111.8487,56322449844.1579,61867157679.3215,25947020102.4332,22946583374.7569,229562733398.948,211685616592.931,188033050459.881,218628940951.675,252548179964.897,344003137611.271,343584391647.927,346498737961.635,332121063806.391,302673070846.857,31290453293.5451,26924385103.0659,22890762090.1508,25115753366.1114,23213994093.4631,255647979916.471,268514916972.549,2865157541994.17,2595151045197.65,2439188643162.5,2811876903329.03,2728870246705.88,3749314991050.59,3733804649549.03,3889177589254.9,3690849152517.65,3357585719351.56,205252760889.364,199844406013.531,195683527003.375,141942264554.475,164020460331.659,143112196040.326,2011302198827.45,1961796197354.36,1836637711060.55,2141924094298.56,2294994296589.5,34225547537.0745,30483806017.8318,47758736931.7801,54808531641.4117,65203276466.9763,60071584216.1375,69890505323.5842,65712180342.9836,13484541925.7714,16004563885.7539,905270626332.687,877172824534.512,910194347568.626,596058473058.766,524641252834.826,477111287969.227,524374183218.309,245117990242.248,221357874718.93,199394066525.44,251017797625.017,210147163769.848,54386654313.9685,48589100043.0954,43107506024.3254,48415657264.8758,51583869785.1849,1394320055129.41,1313245330197.65,1196156971279.69,1355579535912.55,1480710495710.12,574094112972.733,586841821796.891,505103781349.757,541018749769.097,533879529188.454,715888126682.396,706234937370.968,695200833086.499,721369112726.724,694118186379.6281,417261151844.977,381971148530.543,444596155845.254],[15.6570549611063,16.5613906058116,10.162808151585,11.2231706729085,12.2835331942319,12.2835331942319,12.2835331942319,1.428196392424,1.428196392424,13.6047139871854,13.6047139871854,13.6047139871854,16.834034154295,16.834034154295,3.79727925076362,3.81975246546639,3.84222568016916,3.84222568016916,3.84222568016916,9.36613248065313,9.73256191696272,10.0989913532723,10.0989913532723,10.0989913532723,15.4163092221449,15.4163092221449,15.4163092221449,15.7925916070553,16.1688739919657,5.73968325726902,5.73968325726902,11.5617252969557,12.0884793768866,12.0884793768866,11.8251023369212,12.0884793768866,14.5186915462586,14.6988714207909,14.8790512953233,14.8790512953233,14.8790512953233,11.3423773738507,11.3423773738507,11.3423773738507,4.40031731724867,4.56246525249104,4.56246525249104,9.6807677420957,9.6807677420957,9.6807677420957,9.69373440512658,9.70670106815747,13.3532402640341,13.3532402640341,4.72608962255138,4.72608962255138,39.2271146141833,43.9641339422687,43.9641339422687,43.9641339422687,9.8984880693625,9.8984880693625,11.1537458235597,11.4247142823404,11.6956827411211,1.60418083655994,1.60418083655994,1.60418083655994,1.65314423403824,7.3833357951508,8.089593589365901,8.089593589365901,1.16313480315329,1.16313480315329,11.4129640933173,11.4129640933173,11.4129640933173,11.7937170278644,12.1744699624115,12.6902371918259,12.6902371918259,12.6902371918259,13.0045834623447,13.3189297328634,15.162381155937,15.9649699531588,16.7675587503806,16.7675587503806,16.7675587503806,27.0782615919657,28.232473566981,29.3866855419963,29.3866855419963,29.3866855419963,17.465726250517,17.465726250517,17.465726250517],[2,2,3,3,3,3,3,1,1,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,2,2,2,2,1,1,2,2,2,1,1,1,1,2,2,2,2,2,2,2,2,2,2,4,4,4,4,4,2,2,2,2,2,3,3,3,3,3,2,2,2],[4,4,4,4,4,4,4,2,2,2,2,2,0,0,3,3,3,3,3,2,2,2,2,2,1,1,1,1,1,3,3,5,5,5,5,5,10,10,10,10,10,5,5,5,2,2,2,7,7,7,7,7,2,2,2,2,0,0,0,0,1,1,9,9,9,3,3,3,3,2,2,2,2,2,1,1,1,1,1,2,2,2,2,2,0,0,0,0,0,5,5,5,5,5,4,4,4],[31,31,17,17,17,17,17,27,27,11,11,11,44,44,9,9,9,9,9,11,11,11,11,11,84,84,84,84,84,51,51,15,15,15,15,15,31,31,31,31,31,566,566,566,84,84,84,21,21,21,21,21,60,60,83,83,20,20,20,20,24,24,14,14,14,45,45,45,45,21,21,21,144,144,12,12,12,12,12,9,9,9,9,9,21,21,21,21,21,28,28,28,28,28,31,31,31],[0.426828279760995,0.543639371099459,0.788752453285698,0.771795206135098,0.733479730340766,0.770577818785721,0.763582679863982,0.574077430237829,0.593385048182073,0.272754455252371,0.148182945804232,0.10819453215087,0.167355264855434,0.124090086972018,0.412856528398529,0.281728066583104,0.323979707848844,0.237989021748751,0.181914445229453,0.980318762388752,0.98815789868686,1,0.985380171917574,0.939743841507157,0.701844752720087,0.62552315664267,0.659284917677901,0.463750373948703,0.5097981974231151,0.65733831066174,0.9056802188781951,0.601169310764201,0.816265901000798,0.697502896409844,0.644580916982944,0.7244875339975561,0.825582477601391,0.860734649541857,0.814817730019517,0.80239382496182,0.872876922902425,0.479861203672287,0.429434305740094,0.33932483912477,0.269847186788382,0.18601363383361,0.126011095067465,0.582472706593823,0.584059033754853,0.553344457445312,0.496156449738574,0.462407048192141,0.818484879851504,0.666913512530305,0.455658050759793,0.507530485837698,0.279865332126045,0.395900861554826,0.334706929885288,0.254371244268105,0.09139601030674591,0.20502106892747,0.941901823111549,0.754033215488991,0.644007914732912,0.308738892318581,0.266344509582717,0.414607839209798,0.362256207054077,0.268378899560797,0.423898698498664,0.407074249443784,0.264307006775348,0,0.678219280400696,0.620825950603305,0.674147177895333,0.612509496370865,0.5392434957980971,0.898806430188091,0.728583250926207,0.754658682158509,0.716263551877634,0.682560690445687,0.8852632301735101,0.94755869945104,0.959349895627042,0.888476950589474,0.940462182332811,0.493945528283135,0.5362005238983431,0.530847647900476,0.598162130030467,0.568473789489118,0.551164626596747,0.43762701017644,0.597203310692323],[0.503145435911682,0.5762339248405211,0.5007338507019879,0.588590414828691,0.652985213058817,0.635837143801066,0.660096372491632,0.339582070971206,0.353252774887295,0.326771694921556,0.400151297535909,0.394555842165914,0.527092477772834,0.546787564402138,0.288092120599296,0.38325178309719,0.43247057949965,0.474009216829284,0.473108940802588,0.619076686257154,0.762045688357306,0.7924192242649279,0.769736268250839,0.775037531639919,0.970854800363237,0.980465497704374,0.940148955338641,0.895295607825121,0.8857595514230669,1,0.9859016450757701,0.553794903451837,0.717052603515046,0.676807123014157,0.617046666191478,0.718164659389015,0.527032418235431,0.618568161483755,0.699825226090617,0.696349814079812,0.65759873849641,0.587600879237466,0.579108691051016,0.505544178463795,0.290229351986448,0.484892719776279,0.48112629676621,0.50350771987855,0.503079869365694,0.413982307524276,0.409570224545826,0.258768186925823,0.690388580201498,0.700972742644027,0.773582650843486,0.765484971311202,0.69548681132824,0.754427909347769,0.779448387884415,0.789693424172379,0.667940937752009,0.645491242952779,0.530593035537567,0.657878758399541,0.689122062203096,0.203071416971638,0.196789544360365,0.197244228073966,0,0.755743682823111,0.852337816125009,0.833338651403803,0.522632658523842,0.520669745756327,0.46311520779532,0.47510355244879,0.419496913058577,0.396348655160043,0.281002098030865,0.795040074333924,0.794098643216795,0.758050457002427,0.766070874758303,0.670659134477839,0.89860905872718,0.9581139038933379,0.97192820806654,0.980048462941711,0.9821314709003089,0.607591431340556,0.669287585865513,0.789264443973245,0.787067164371683,0.709683669046461,0.692383961994576,0.628982615644225,0.683211559458146],[0.592592592592593,0.592592592592593,0.75925925925926,0.78395061728395,0.802469135802469,0.78395061728395,0.814814814814815,0,0.00617283950617287,0.574074074074074,0.617283950617283,0.709876543209877,0.567901234567901,0.555555555555555,0.864197530864197,0.8580246913580249,0.895061728395062,0.95679012345679,0.932098765432099,0.808641975308643,0.7345679012345681,0.78395061728395,0.722222222222222,0.753086419753086,0.592592592592593,0.617283950617283,0.475308641975309,0.327160493827161,0.487654320987654,0.802469135802469,0.78395061728395,0.438271604938271,0.543209876543211,0.475308641975309,0.487654320987654,0.567901234567901,0.598765432098765,0.549382716049383,0.537037037037037,0.524691358024691,0.555555555555555,0.450617283950618,0.37037037037037,0.271604938271605,0.691358024691358,0.6419753086419761,0.604938271604938,0.358024691358025,0.277777777777777,0.308641975308642,0.339506172839505,0.327160493827161,0.364197530864198,0.296296296296297,0.191358024691358,0.314814814814815,0.518518518518518,0.462962962962963,0.382716049382716,0.364197530864198,0.691358024691358,0.580246913580247,0.777777777777778,0.75925925925926,0.691358024691358,0.71604938271605,0.660493827160494,0.530864197530864,0.444444444444444,0.253086419753087,0.407407407407407,0.302469135802469,0.345679012345679,0.271604938271605,0.987654320987654,1,0.925925925925926,0.876543209876543,0.95679012345679,0.376543209876544,0.351851851851851,0.259259259259259,0.259259259259259,0.290123456790123,0.790123456790123,0.71604938271605,0.691358024691358,0.71604938271605,0.685185185185185,0.537037037037037,0.487654320987654,0.475308641975309,0.395061728395062,0.5,0.660493827160494,0.611111111111111,0.62962962962963],[0.456749385859517,0.480838247290084,0,0.259992735052012,0.259992735052012,0.259992735052012,0.259992735052012,0.187469048916231,0.187469048916231,0.391769162702179,0.391769162702179,0.391769162702179,0.480838247290084,0.480838247290084,0.593873626237206,0.603940490870655,0.512203096766381,0.512203096766381,0.512203096766381,0.456749385859517,0.480838247290084,0.480838247290084,0.480838247290084,0.480838247290084,0.603940490870655,0.603940490870655,0.603940490870655,0.603940490870655,0.593873626237206,0.480838247290084,0.480838247290084,0.456749385859517,0.480838247290084,0.480838247290084,0.480838247290084,0.480838247290084,0.456749385859517,0.480838247290084,0.480838247290084,0.480838247290084,0.480838247290084,0.480838247290084,0.480838247290084,0.480838247290084,1,0.0274007053717487,0.115478642147258,0.480838247290084,0.480838247290084,0.480838247290084,0.480838247290084,0.456749385859517,0.379773677279894,0.312628092200508,0.518012693042467,0.518012693042467,0.480838247290084,0.480838247290084,0.480838247290084,0.480838247290084,0.0970280261725964,0.0970280261725964,0.456749385859517,0.480838247290084,0.480838247290084,0.518012693042467,0.518012693042467,0.746059748677704,0.279909980941069,0.456749385859517,0.480838247290084,0.480838247290084,0.379773677279894,0.391769162702179,0.518012693042467,0.518012693042467,0.518012693042467,0.746059748677704,1,0.480838247290084,0.480838247290084,0.480838247290084,0.480838247290084,0.456749385859517,0.456749385859517,0.480838247290084,0.480838247290084,0.480838247290084,0.480838247290084,0.456749385859517,0.480838247290084,0.480838247290084,0.480838247290084,0.480838247290084,0.480838247290084,0.480838247290084,0.480838247290084],[0.841614906832298,0.839703774486383,0.939321548017201,0.939321548017201,0.938604873387483,0.938604873387483,0.916387959866222,0.650740563784042,0.650740563784042,0.730530339225992,0.730530339225992,0.766841853798376,0.794553272814143,0.81055900621118,0.851648351648352,0.815575728619208,0.815575728619208,0.861204013377927,0.861204013377927,0.913521261347349,0.913521261347349,0.90157668418538,0.915910176779743,0.915910176779743,0.883659818442428,0.904921165790731,0.904921165790731,0.914715719063546,0.914715719063546,0.842331581462017,0.832059245102724,0.841853798375538,0.883182035355949,0.839464882943145,0.839464882943145,0.883182035355949,1,0.8901098901098911,0.8834209268991881,0.8834209268991881,0.8901098901098911,0.963927376970856,0.903248924988056,0.903248924988056,0.889393215480173,0.792164357381749,0.799092212135691,0.760630673674152,0.778308647873866,0.778308647873866,0.778308647873866,0.942666029622552,0,0.0155279503105583,0.877687529861444,0.873865265169614,0.710463449593885,0.710463449593885,0.709030100334449,0.710463449593885,0.873387482083134,0.873387482083134,0.884854276158625,0.885809842331582,0.869087434304826,0.836120401337792,0.933588150979455,0.933588150979455,0.97372193024367,0.8449593884376499,0.896559961777354,0.896559961777354,0.832059245102724,0.829431438127091,0.8561872909699,0.8561872909699,0.84854276158624,0.849737219302438,0.849737219302438,0.972288580984234,0.8862876254180611,0.8862876254180611,0.906115623506929,0.906115623506929,0.813903487816532,0.813903487816532,0.809842331581462,0.809842331581462,0.7692307692307701,0.851887243191591,0.851887243191591,0.8354037267080749,0.830864787386528,0.8354037267080749,0.768514094601051,0.839703774486383,0.79933110367893],[0.5718729393752,0.578371132270373,0.766233537416515,0.767232273423944,0.767232273423944,0.767232273423944,0.7395532711331541,0.208886163671582,0.21168436629226,0.575696709268767,0.467892504637976,0.412555009063305,0.477537326919165,0.428447409624395,0.630001316158747,0.6328321718572451,0.6328321718572451,0.479952304254137,0.444233641742675,0.66010241467572,0.662057055419367,0.623763851768614,0.623763851768614,0.623763851768614,0.711498501544693,1,0.796832416988931,0.734814096153636,0.73884410580941,0.673663344529051,0.673663344529051,0.707429587299265,0.681636426894681,0.742287982863414,0.742287982863414,0.681636426894681,0.998887595585785,0.845391140221911,0.999256475503795,0.999256475503795,0.845391140221911,0.634468599490482,0.664895067157102,0.654361746601997,0.453926306612221,0,0.0980903522666448,0.597827287565276,0.621226415405655,0.606741175722192,0.606741175722192,0.474585908591476,0.603989380926697,0.605146139365442,0.533839426438748,0.5429799118173509,0.603656598184934,0.603656598184934,0.603656598184934,0.603656598184934,0.334000533759073,0.334000533759073,0.998887595585785,0.766775415148336,0.708382968288504,0.223680374023149,0.6024949784821449,0.660693688240078,0.730709365681395,0.712124287787362,0.883575144533371,0.761354740433126,0.453214588086925,0.286626476311311,0.511338699266945,0.625717031510266,0.510486100601497,0.62217908720575,0.641860202079278,0.816179017342091,0.526467497475526,0.5888693278741109,0.7453249002171199,0.766233537416515,0.7934627668320881,0.794513467907224,0.762164950552001,0.762164950552001,0.686623450532943,0.544753256358795,0.589613178696921,0.551448630301773,0.5315621476144879,0.5383657934502289,0.600995668603022,0.578371132270373,0.498339494012204],[0.672787531137658,0.672787531137658,0.793519560515903,0.793519560515903,0.793519560515903,0.793519560515903,0.793519560515903,0.507544810073176,0.122166681338342,0.404176114036193,0.162243751254032,0.233319692640291,0.613165013525699,0.613165013525699,0.387801730940502,0.516687246665763,0.381505599425188,0.518168689375248,0.378542714006216,0.728823022317601,0.684848441590473,0.684848441590473,0.684848441590473,0.684848441590473,0.710034950310603,0.710034950310603,0.475947572154904,0.475947572154904,0.475947572154904,0.644072286156362,0.644072286156362,0.678640340129095,0.678640340129095,0.678640340129095,0.678640340129095,0.678640340129095,1,0.9755573848888091,0.9755573848888091,0.9755573848888091,0.9755573848888091,0.777422749662354,0.777422749662354,0.777422749662354,0.565953940455203,0,0.148205733373621,0.610928574317589,0.578419313317995,0.446215619703823,0.446215619703823,0.43758074378258,0.364165661458619,0.451704015994506,0.368051276316823,0.368051276316823,0.395666938687464,0.395666938687464,0.329527024830027,0.395666938687464,0.392085860232066,0.392085860232066,0.569885156467473,0.569885156467473,0.569885156467473,0.679093972479109,0.709903698293248,0.709903698293248,0.75050141442884,0.7707019326165619,0.7707019326165619,0.7707019326165619,0.0221153701267236,0.0221153701267236,0.394937320222407,0.508287910618566,0.508287910618566,0.508287910618566,0.508287910618566,0.800988236488378,0.800988236488378,0.800988236488378,0.800988236488378,0.800988236488378,0.861612789894467,0.861612789894467,0.822885514139133,0.822885514139133,0.866776426661845,0.78596523368014,0.78596523368014,0.453482461003083,0.673688054797519,0.78596523368014,0.672787531137658,0.672787531137658,0.672787531137658],[2872,108,1852,1100,64,1149,777,1061,892,2390,272,136,522,683,2657,849,237,61,1771,233,1033,1026,36,281,2507,29,815,130,4041,836,1146,1967,50,378,118,1127,10,2394,2003,46,114,73,29,2497,2245,739,26,818,87,1327,1272,1037,776,908,634,1399,947,453,671,33,475,784,518,1049,979,1278,1943,359,32,1710,9,195,1248,835,1626,57,1533,532,1543,1064,106,329,2360,1053,42,1362,162,42,1184,1306,49,33,1179,67,36,123,1181],[8375164,8451860,11011716,11160992,11384723,11258434,11467933,6803468,6985000,4265344,4058200,4058200,1224000,1212900,10500000,10510000,10550000,10590000,10649800,5600940,5624000,5806100,5731110,5678910,1324800,1327439,1331475,1326898,1326040,5566210,5514100,65316851,65438667,64818789,66734800,67028000,80274983,82905782,83019200,80425823,80274983,10722800,10645000,10721582,9759755,9772800,9913588,60359500,60789190,60795612,60650000,59296632,1907800,1903000,2778000,2794200,543000,569000,613900,598000,464000,493600,16645000,16750000,17410000,37950000,38640000,38750000,38175000,10512254,10470000,10501200,19200000,19470000,2080200,2089000,2080000,2061500,2050191,47200000,46950000,46700000,46670000,46196548,9448073,9481000,9525000,9545000,9753000,7851000,8120000,8344000,8416000,8300000,8772865,8584926,8858775]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>Country<\/th>\n      <th>Year<\/th>\n      <th>Mono<\/th>\n      <th>One<\/th>\n      <th>Two<\/th>\n      <th>Three<\/th>\n      <th>Total<\/th>\n      <th>total_exposomes<\/th>\n      <th>sociopolitical<\/th>\n      <th>social_physical<\/th>\n      <th>GDP<\/th>\n      <th>Migration<\/th>\n      <th>number_leng_inst<\/th>\n      <th>number_stable_inst<\/th>\n      <th>distance<\/th>\n      <th>gender_equal_l<\/th>\n      <th>Polution_conc_inv<\/th>\n      <th>Eq<\/th>\n      <th>free_parties_l<\/th>\n      <th>inclu_suff_est<\/th>\n      <th>cred_elect_est<\/th>\n      <th>local_dem_est<\/th>\n      <th>n<\/th>\n      <th>Pop<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"columnDefs":[{"className":"dt-right","targets":[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24]},{"orderable":false,"targets":0},{"name":" ","targets":0},{"name":"Country","targets":1},{"name":"Year","targets":2},{"name":"Mono","targets":3},{"name":"One","targets":4},{"name":"Two","targets":5},{"name":"Three","targets":6},{"name":"Total","targets":7},{"name":"total_exposomes","targets":8},{"name":"sociopolitical","targets":9},{"name":"social_physical","targets":10},{"name":"GDP","targets":11},{"name":"Migration","targets":12},{"name":"number_leng_inst","targets":13},{"name":"number_stable_inst","targets":14},{"name":"distance","targets":15},{"name":"gender_equal_l","targets":16},{"name":"Polution_conc_inv","targets":17},{"name":"Eq","targets":18},{"name":"free_parties_l","targets":19},{"name":"inclu_suff_est","targets":20},{"name":"cred_elect_est","targets":21},{"name":"local_dem_est","targets":22},{"name":"n","targets":23},{"name":"Pop","targets":24}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>d_cross <span class="ot">&lt;-</span> d_cross <span class="sc">|&gt;</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(country_cohort) <span class="sc">|&gt;</span> </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">GDP_percapita =</span> (GDP <span class="sc">/</span> Pop) <span class="sc">/</span> <span class="dv">10000</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Joining with `by = join_by(Mono, One, Two, Three, Total, total_exposomes,
sociopolitical, social_physical, GDP, Migration, number_leng_inst,
number_stable_inst, distance, gender_equal_l, Polution_conc_inv, Eq,
free_parties_l, inclu_suff_est, cred_elect_est, local_dem_est)`</code></pre>
</div>
</div>
</section>
<section id="drawing-some-plots" class="level3">
<h3 class="anchored" data-anchor-id="drawing-some-plots">Drawing some plots</h3>
<p>Amoruso et al.&nbsp;drew lots of plots—just none that show how the predictors and the BAGs are related. A first (naive) plot is shown in <a href="#fig-naive" class="quarto-xref">Figure&nbsp;1</a>. The smooth trend line attempts to estimate the proportion of respondents showing accelerated ageing (again, I’m taking the accelerated ageing variable as given for now; I’ll scrutinise it later) based on the extent of country-level monolingualism.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>d_cross <span class="sc">|&gt;</span> </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Mono, <span class="at">y =</span> GAP_bin)) <span class="sc">+</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"gam"</span>, <span class="at">formula =</span> y <span class="sc">~</span> <span class="fu">s</span>(x, <span class="at">bs =</span> <span class="st">"cr"</span>),</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Percentage of monolinguals in country"</span>) <span class="sc">+</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Proportion of accelerated ageing"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-naive" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-naive-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-naive-1.svg" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-naive-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: A naive trendline showing the extent of accelerated ageing according to country-level monolingualism.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The bumps in this graph highlight a problem with Amoruso et al.’s analysis: they didn’t take the nested nature of the data into account. To address this, I’ve computed the number and proportion of respondents showing accelerated ageing for each combination of country and year of data collection. <a href="#fig-by_country_year" class="quarto-xref">Figure&nbsp;2</a> shows how the proportion of respondents with accelerated ageing varied between different waves of data collection within each country.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>by_country_year <span class="ot">&lt;-</span> d_cross <span class="sc">|&gt;</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Country, Year, Mono, GDP_percapita) <span class="sc">|&gt;</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_accelerated =</span> <span class="fu">sum</span>(GAP_bin <span class="sc">&gt;</span> <span class="dv">0</span>),</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">prop_accelerated =</span> <span class="fu">mean</span>(GAP_bin <span class="sc">&gt;</span> <span class="dv">0</span>),</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>by_country_year <span class="sc">|&gt;</span> </span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Mono, <span class="at">y =</span> prop_accelerated)) <span class="sc">+</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">shape =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="fu">vars</span>(<span class="fu">reorder</span>(Country, prop_accelerated))) <span class="sc">+</span></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Proportion of monolinguals"</span>) <span class="sc">+</span></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Proportion of accelerated ageing"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-by_country_year" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-by_country_year-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-by_country_year-1.svg" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-by_country_year-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Each point represents a combination of country and year of data collection. The countries are sorted top to bottom, left to right, in increasing average proportion of respondents showing accelerated ageing.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The proportion of monolinguals tends to vary fairly little within each country, and I’m not convinced that we should put too much stock in the yearly changes in these proportions. So I’ll simply aggregate the data per country instead. <a href="#fig-country_mono" class="quarto-xref">Figure&nbsp;3</a> shows that there is indeed a tendency for countries with relatively more monolinguals to have a greater of respondents with accelerated ageing.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>by_country <span class="ot">&lt;-</span> d_cross <span class="sc">|&gt;</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Country) <span class="sc">|&gt;</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_accelerated =</span> <span class="fu">sum</span>(GAP_bin <span class="sc">&gt;</span> <span class="dv">0</span>),</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">prop_accelerated =</span> <span class="fu">mean</span>(GAP_bin <span class="sc">&gt;</span> <span class="dv">0</span>),</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_Mono =</span> <span class="fu">mean</span>(Mono),</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_GDP =</span> <span class="fu">mean</span>(GDP_percapita),</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>by_country <span class="sc">|&gt;</span> </span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> mean_Mono, <span class="at">y =</span> prop_accelerated)) <span class="sc">+</span></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> Country), <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>, <span class="dv">65</span>) <span class="sc">+</span></span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Percentage of monolinguals"</span>) <span class="sc">+</span></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Proportion of accelerated ageing"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-country_mono" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-country_mono-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-country_mono-1.svg" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-country_mono-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: The percentage of monolinguals shown is the weighted average of the percentages of monolinguals in the country at the different waves of data collection.
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-country_gdp" class="quarto-xref">Figure&nbsp;4</a> shows the association of the proportion of respondents per country with accelerated ageing and the country’s per capita GDP.</p>
<div class="cell preview-image">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>by_country <span class="sc">|&gt;</span> </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> mean_GDP, <span class="at">y =</span> prop_accelerated)) <span class="sc">+</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> Country), <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"GDP per capita (in 10k)"</span>) <span class="sc">+</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>, <span class="fl">12.5</span>) <span class="sc">+</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Proportion of accelerated ageing"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-country_gdp" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-country_gdp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-country_gdp-1.svg" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-country_gdp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: The GDP per capita is the weighted average of the country’s GDP per capita at the different waves of data collection.
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-mono_gdp" class="quarto-xref">Figure&nbsp;5</a> shows the association between the per capita GDP and the proportion of monolinguals in the country.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>by_country <span class="sc">|&gt;</span> </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> mean_GDP, <span class="at">y =</span> mean_Mono)) <span class="sc">+</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> Country), <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"GDP per capita (in 10k)"</span>) <span class="sc">+</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>, <span class="fl">12.5</span>) <span class="sc">+</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Proportion of monolinguals"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-mono_gdp" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mono_gdp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-mono_gdp-1.svg" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mono_gdp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: The GDP per capita and the proportion of monolinguals are the weighted average of the country’s values at the different waves of data collection.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="refitting-the-models" class="level3">
<h3 class="anchored" data-anchor-id="refitting-the-models">Refitting the models</h3>
<p>To take the nested nature of the data into account, we could fit a binomial model to the data aggregated by country. I expressed the monolingualism variable in such a way that a one-unit increase in this variable corresponds to a difference of 10 percentage points in monolingualism. I also centred this variable at its median, corresponding to about 19% monolinguals.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>by_country<span class="sc">$</span>c.Mono10 <span class="ot">&lt;-</span> by_country<span class="sc">$</span>mean_Mono <span class="sc">/</span> <span class="dv">10</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>by_country<span class="sc">$</span>c.Mono10 <span class="ot">&lt;-</span> by_country<span class="sc">$</span>c.Mono10 <span class="sc">-</span> <span class="fu">median</span>(by_country<span class="sc">$</span>c.Mono10)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>mono.glm <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="fu">cbind</span>(n_accelerated, n <span class="sc">-</span> n_accelerated) <span class="sc">~</span> c.Mono10,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> by_country,</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>))</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mono.glm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = cbind(n_accelerated, n - n_accelerated) ~ c.Mono10, 
    family = binomial(link = "logit"), data = by_country)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)
(Intercept) -0.195093   0.007354  -26.53   &lt;2e-16
c.Mono10     0.099915   0.004304   23.21   &lt;2e-16

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 2565.1  on 25  degrees of freedom
Residual deviance: 2023.3  on 24  degrees of freedom
AIC: 2245.3

Number of Fisher Scoring iterations: 3</code></pre>
</div>
</div>
<p>The problem with this model is the <em>massive</em> overdispersion: <span class="math inline">\(\chi^2 = 2023.3/24 = 84.3 \gg 1\)</span>. The binomial logistic model assumes that the number of respondents showing accelerated ageing in the <span class="math inline">\(i\)</span>-th country is <span class="math display">\[Y_i \sim \textrm{Binomial}(n_i, \pi_i),\]</span> where <span class="math inline">\(n_i\)</span> is the number of respondents in the <span class="math inline">\(i\)</span>-th country and <span class="math inline">\(\pi_i\)</span> is the probability parameter modelled as <span class="math display">\[\pi_i = \textrm{Logistic}(\beta_0 + \beta_1x_i) = \frac{1}{1 + \exp({-(\beta_0 + \beta_1x_i)})},\]</span> with <span class="math inline">\(x_i\)</span> the percentage of monolinguals in the <span class="math inline">\(i\)</span>-th country.</p>
<p>Clearly, this model underspecifies the true data-generating mechanism. In normal (ordinary least squares) regression models, this isn’t a huge problem in and of itself: the error term doesn’t depend on the modelled mean and can absorb the variance associated with unmodelled factors.</p>
<p>But the binomial model does not <em>have</em> a separate error term. Instead, it assumes that the variance around <span class="math inline">\(Y_i\)</span> is the variance of the binomial distribution, i.e., <span class="math inline">\(\textrm{Var}(Y_i) = n_i\pi_i(1-\pi_i)\)</span>. To the extent that other factors beyond the ones modelled contribute to the outcome, <span class="math inline">\(\textrm{Var}(Y_i)\)</span> can be considerably larger than <span class="math inline">\(n_i\pi_i(1-\pi_i)\)</span>, and the standard errors and confidence intervals need to be widened to take this into account.</p>
<p>One option is to fit the data in a quasibinomial regression model instead. The resulting parameter estimates are the same as before, but the standard error increased by a factor of about 9.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>mono.glm <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="fu">cbind</span>(n_accelerated, n <span class="sc">-</span> n_accelerated) <span class="sc">~</span> c.Mono10,</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> by_country,</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">family =</span> <span class="fu">quasibinomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>))</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mono.glm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = cbind(n_accelerated, n - n_accelerated) ~ c.Mono10, 
    family = quasibinomial(link = "logit"), data = by_country)

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)
(Intercept) -0.19509    0.06715  -2.905  0.00776
c.Mono10     0.09992    0.03930   2.542  0.01789

(Dispersion parameter for quasibinomial family taken to be 83.37782)

    Null deviance: 2565.1  on 25  degrees of freedom
Residual deviance: 2023.3  on 24  degrees of freedom
AIC: NA

Number of Fisher Scoring iterations: 3</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>mono.conf <span class="ot">&lt;-</span> <span class="fu">confint</span>(mono.glm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>mono.conf[<span class="dv">1</span>, ] <span class="sc">|&gt;</span> <span class="fu">plogis</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>    2.5 %    97.5 % 
0.4189363 0.4840508 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>mono.conf[<span class="dv">2</span>, ] <span class="sc">|&gt;</span> <span class="fu">exp</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   2.5 %   97.5 % 
1.023329 1.193924 </code></pre>
</div>
</div>
<p>The correct interpretation of these estimates is as follows. If the model for the <span class="math inline">\(\pi_i\)</span>s is correct, we’d expect that in a country with the median percentage of monolinguals (i.e., about 19%), about <span class="math inline">\(\textrm{Logistic}(-0.19509) \approx 45\%\)</span> of the respondents show accelerated ageing; 95% CI: <span class="math inline">\((42\%, 48\%)\)</span>. A 10-percentage point difference in the percentage of monolinguals is associated with an odds ratio of about <span class="math inline">\(\exp(0.09992) \approx 1.105\)</span>; 95% CI: <span class="math inline">\((1.02, 1.19)\)</span>.</p>
<p>Let’s now add per capita GDP to the equation. The per capita GDP variable was centred at its sample median of about 26,800 units per capita of whatever currency the data are expressed in.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>by_country<span class="sc">$</span>c.mean_GDP <span class="ot">&lt;-</span> by_country<span class="sc">$</span>mean_GDP <span class="sc">-</span> <span class="fu">median</span>(by_country<span class="sc">$</span>mean_GDP)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>gdp.glm <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="fu">cbind</span>(n_accelerated, n <span class="sc">-</span> n_accelerated) <span class="sc">~</span> c.Mono10 <span class="sc">+</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>                 c.mean_GDP,</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> by_country,</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">family =</span> <span class="fu">quasibinomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>))</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gdp.glm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = cbind(n_accelerated, n - n_accelerated) ~ c.Mono10 + 
    c.mean_GDP, family = quasibinomial(link = "logit"), data = by_country)

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)
(Intercept) -0.11740    0.06898  -1.702   0.1023
c.Mono10     0.06063    0.03930   1.543   0.1365
c.mean_GDP  -0.07211    0.02998  -2.405   0.0246

(Dispersion parameter for quasibinomial family taken to be 69.35127)

    Null deviance: 2565.1  on 25  degrees of freedom
Residual deviance: 1613.8  on 23  degrees of freedom
AIC: NA

Number of Fisher Scoring iterations: 3</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>gdp.conf <span class="ot">&lt;-</span> <span class="fu">confint</span>(gdp.glm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>gdp.conf[<span class="dv">1</span>, ] <span class="sc">|&gt;</span> <span class="fu">plogis</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>    2.5 %    97.5 % 
0.4371134 0.5044157 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>gdp.conf[<span class="dv">2</span>, ] <span class="sc">|&gt;</span> <span class="fu">exp</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>    2.5 %    97.5 % 
0.9838391 1.1477900 </code></pre>
</div>
</div>
<p>The model predicts a country with a per capita GDP of about 26.8k and 19% monolinguals to have about <span class="math inline">\(\textrm{Logistic}(-0.1174) \approx 47\%\)</span> of respondents with accelerated ageing; 95% CI: <span class="math inline">\((43.7\%, 50.4\%)\)</span>. Keeping per capita GDP constant, a 10-percentage point difference in monolingualism is associated with <span class="math inline">\(\exp(0.06063) \approx 1.06\)</span> times larger odds of accelerated ageing in the country, 95% CI: <span class="math inline">\((0.98, 1.15)\)</span>. Hence, once GDP is taken into account, the association between accelerated ageing and monolingualism is no longer significant.</p>
<p>Alternative model specifications are, of course, possible. Some, for instance generalised linear mixed models using individual-level BAGs but country-level predictors, lead to parameter estimates that can be fairly difficult to wrap one’s head round. Moreover, here I only looked at a single possible confounder (per capita GDP) as I had earlier identified a problem with it. This doesn’t mean that <em>only</em> this confounder should be considered.</p>
</section>
<section id="using-a-continuous-outcome" class="level3">
<h3 class="anchored" data-anchor-id="using-a-continuous-outcome">Using a continuous outcome</h3>
<p>Up till now, I used the <span class="math inline">\(\texttt{BAG}\)</span> values that Amoruso et al.&nbsp;provided in the <code>data.csv</code> dataset. To recall (see <a href="#sec-bag" class="quarto-xref">Section&nbsp;2.3</a>), these values are binary indicators of whether the respondent’s predicted age is older than their actual age, after correcting for the overprediction of younger ages and the underprediction of older ages. The predicted ages aren’t actually shared in any of the datasets: Amoruso et al.&nbsp;fit the models predicting age from biobehavioural factors in a couple of scripts, but these don’t contain the code for exporting the predicted ages. So I adapted their Jupyter notebooks in order to compute and export the predicted ages myself.</p>
<p>I stuck to Amoruso et al.’s approach, even though I’m pretty skeptical about it. Based on their Python code, I wrote my own Python script, <a href="compute_bag.py"><code>compute_bag.py</code></a>. In it, 26 models are trained using gradient boosting to predict respondents’ age from their biobehavioural factors, always leaving out a different country. I excluded the Slovak data seeing as these did not enter into Amoruso et al.’s analyses. For each model, a hyperparameter search was conducted. The ages for the out-of-fold respondents were then predicted, and their <span class="math inline">\(\texttt{GAP}\)</span> scores computed accordingly. To correct for the overestimation of the ages of the youngest participants and the underestimation of those of the oldest participants, I fitted linear regression models just like in the original to the training data. The corrected <span class="math inline">\(\texttt{GAP}\)</span> scores were computed as in the original. One additional difference to the original is that didn’t set all the random seeds to 42.</p>
<p>The predicted ages and <span class="math inline">\(\texttt{GAP}\)</span> values are stored in <a href="data_predictions.csv"><code>data_predictions.csv</code></a>. Let’s first reassure ourselves that the model output is comparable to that reported by Amoruso et al. As the scatterplot in <a href="#fig-predicted-ages" class="quarto-xref">Figure&nbsp;6</a> shows, the prediction is far from good. Up till age 66, the respondents’ age is overestimated; from then onwards, their age is underestimated.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data_predictions.csv"</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(d,</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> Age, <span class="at">y =</span> predicted_age)) <span class="sc">+</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">group =</span> Age), <span class="at">outlier.shape =</span> <span class="dv">1</span>, <span class="at">varwidth =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="dv">1</span>, <span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"solid"</span>, <span class="at">colour =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"gam"</span>, <span class="at">formula =</span> y <span class="sc">~</span> <span class="fu">s</span>(x, <span class="at">bs =</span> <span class="st">"tp"</span>)) <span class="sc">+</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"True age (years)"</span>) <span class="sc">+</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Predicted age (years)"</span>) <span class="sc">+</span></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Predicted vs. true age"</span></span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-predicted-ages" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-predicted-ages-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-predicted-ages-1.svg" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-predicted-ages-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: The predicted ages are out-of-fold predictions based on gradient boosting. The red lines shows the identity; the blue line is a scatterplot smoother highlighting the mean trend.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The root mean squared error for the age prediction is 8.71 years, which is similar to the number reported by Amoruso et al.&nbsp; (8.65 in the leave-one-country-out cross-validation). The mean absolute error is 7.15 years, again similar to the number reported in the article (7.09). The mean directional error is about 0.03 years (an average overestimation of about 12 days); which is similar to the number reported in the article (0.03).</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">mean</span>((d<span class="sc">$</span>predicted_age <span class="sc">-</span> d<span class="sc">$</span>Age)<span class="sc">^</span><span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8.712974</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">abs</span>(d<span class="sc">$</span>predicted_age <span class="sc">-</span> d<span class="sc">$</span>Age))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7.150154</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(d<span class="sc">$</span>predicted_age) <span class="sc">-</span> <span class="fu">mean</span>(d<span class="sc">$</span>Age)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.03412678</code></pre>
</div>
</div>
<p>These differences can be explained by the fact that I excluded Slovakia from the data when fitting the models; Amoruso et al.&nbsp;didn’t. Further, Amoruso et al.&nbsp;set all their random seeds to 42; I decided to leave them unspecified by default.</p>
<p>Let’s now take a look at the corrected <span class="math inline">\(\texttt{GAP}\)</span> values, <a href="#fig-gap" class="quarto-xref">Figure&nbsp;7</a>. Note that a slight nonlinear trend remains.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(d,</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> Age, <span class="at">y =</span> GAP_corrected)) <span class="sc">+</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">group =</span> Age), <span class="at">outlier.shape =</span> <span class="dv">1</span>, <span class="at">varwidth =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"gam"</span>, <span class="at">formula =</span> y <span class="sc">~</span> <span class="fu">s</span>(x, <span class="at">bs =</span> <span class="st">"tp"</span>)) <span class="sc">+</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"True age (years)"</span>) <span class="sc">+</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Corrected GAP (years)"</span>) <span class="sc">+</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Corrected GAP vs. true age"</span></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-gap" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-gap-1.svg" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-gap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: The GAP values after correction for linear under- and overestimation.
</figcaption>
</figure>
</div>
</div>
</div>
<p>While the datasets <code>data.csv</code> and <code>data_predictions.csv</code> do specify the respondents’ countries, they don’t specify which year the data was collected in. For this reason, I calculated mean monolingualism and mean GDP per capita values per country and added these to the dataset.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>country_cohort <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"country_cohort.csv"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">GDP =</span> (GDP <span class="sc">/</span> Pop) <span class="sc">/</span> <span class="dv">10000</span>) <span class="sc">|&gt;</span> </span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Country) <span class="sc">|&gt;</span> </span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_Mono =</span> <span class="fu">weighted.mean</span>(Mono, n),</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_GDP =</span> <span class="fu">weighted.mean</span>(GDP, n),</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">c.Mono10 =</span> (mean_Mono <span class="sc">/</span> <span class="dv">10</span>) <span class="sc">-</span> <span class="fu">median</span>(mean_Mono <span class="sc">/</span> <span class="dv">10</span>),</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">c.GDP =</span> mean_GDP <span class="sc">-</span> <span class="fu">median</span>(mean_GDP)</span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> d <span class="sc">|&gt;</span></span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(country_cohort, <span class="fu">join_by</span>(<span class="st">"country"</span> <span class="sc">==</span> <span class="st">"Country"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>I’ll go through a similar analysis as before but this time without discretising the <code>GAP_corrected</code> variable. <a href="#fig-mono-gap" class="quarto-xref">Figure&nbsp;8</a> confirms that there is some association between the percentage of monolinguals in a country and the average corrected GAP value in this country.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>by_country <span class="ot">&lt;-</span> d <span class="sc">|&gt;</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(country, mean_Mono, mean_GDP, c.Mono10, c.GDP) <span class="sc">|&gt;</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_GAP =</span> <span class="fu">mean</span>(GAP),</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_corrected_GAP =</span> <span class="fu">mean</span>(GAP_corrected),</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_Age =</span> <span class="fu">mean</span>(Age),</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_predicted_Age =</span> <span class="fu">mean</span>(predicted_age),</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a>by_country <span class="sc">|&gt;</span> </span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> mean_Mono, <span class="at">y =</span> mean_corrected_GAP)) <span class="sc">+</span></span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> country), <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>, <span class="dv">65</span>) <span class="sc">+</span></span>
<span id="cb42-17"><a href="#cb42-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Percentage of monolinguals"</span>) <span class="sc">+</span></span>
<span id="cb42-18"><a href="#cb42-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Mean corrected GAP (years)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-mono-gap" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mono-gap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-mono-gap-1.svg" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mono-gap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: The percentage of monolinguals shown is the weighted average of the percentages of monolinguals in the country at the different waves of data collection.
</figcaption>
</figure>
</div>
</div>
</div>
<p>As <a href="#fig-gdp-gap" class="quarto-xref">Figure&nbsp;9</a> shows, per capita GDP is likewise associated with the average GAP value per country.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>by_country <span class="sc">|&gt;</span> </span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> mean_GDP, <span class="at">y =</span> mean_corrected_GAP)) <span class="sc">+</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> country), <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>, <span class="fl">12.5</span>) <span class="sc">+</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Per capita GDP"</span>) <span class="sc">+</span></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Mean corrected GAP (years)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-gdp-gap" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gdp-gap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-gdp-gap-1.svg" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-gdp-gap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: The GDP per capita is the weighted average of the country’s GDP per capita at the different waves of data collection.
</figcaption>
</figure>
</div>
</div>
</div>
<p>We don’t need to worry about logistic models and odds ratios this time. A simple OLS regression model at the country level is all we need.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>mono.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean_corrected_GAP <span class="sc">~</span> c.Mono10, <span class="at">data =</span> by_country)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mono.lm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mean_corrected_GAP ~ c.Mono10, data = by_country)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.5164 -0.5098 -0.1333  0.3304  2.4568 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)
(Intercept) -0.22313    0.17936  -1.244  0.22549
c.Mono10     0.36317    0.09901   3.668  0.00121

Residual standard error: 0.8815 on 24 degrees of freedom
Multiple R-squared:  0.3592,    Adjusted R-squared:  0.3325 
F-statistic: 13.46 on 1 and 24 DF,  p-value: 0.001213</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mono.lm) <span class="sc">*</span> <span class="fl">365.25</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                2.5 %    97.5 %
(Intercept) -216.7067  53.70753
c.Mono10      58.0121 207.28204</code></pre>
</div>
</div>
<p>This country predicts country with 19% monolinguals to have an average corrected GAP value of about <span class="math inline">\(-0.22\)</span> years (about <span class="math inline">\(-80\)</span> days), 95% CI: <span class="math inline">\((-217, 54)\)</span> days. A 10-percentage point difference in the extent of monolingualism is associated with a change in the average corrected GAP value of about <span class="math inline">\(0.36\)</span> years (about 133 days), 95% CI: <span class="math inline">\((58, 207)\)</span> days.</p>
<p>We can also control for per capita GDP:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>gdp.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean_corrected_GAP <span class="sc">~</span> c.Mono10 <span class="sc">+</span> c.GDP, <span class="at">data =</span> by_country)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gdp.lm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mean_corrected_GAP ~ c.Mono10 + c.GDP, data = by_country)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.40401 -0.37359 -0.06492  0.19045  2.43794 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)
(Intercept) -0.08645    0.19926  -0.434   0.6684
c.Mono10     0.28744    0.11009   2.611   0.0156
c.GDP       -0.11308    0.07820  -1.446   0.1617

Residual standard error: 0.8621 on 23 degrees of freedom
Multiple R-squared:  0.4126,    Adjusted R-squared:  0.3616 
F-statistic: 8.079 on 2 and 23 DF,  p-value: 0.0022</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(gdp.lm) <span class="sc">*</span> <span class="fl">365.25</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5 %    97.5 %
(Intercept) -182.13353 118.97890
c.Mono10      21.80848 188.16438
c.GDP       -100.38508  17.78279</code></pre>
</div>
</div>
<p>So, this model predicts that a country with a per capita GDP of about 26.8k and 19% monolinguals to have an average corrected GAP of about <span class="math inline">\(-0.09\)</span> years (about <span class="math inline">\(-32\)</span> days), 95% CI: <span class="math inline">\((-182, 119)\)</span> days). Keeping per capita GDP constant, it predicts a 10-percentage point change in the extent of monolingualism to be associated with a change in the average corrected GAP of about <span class="math inline">\(0.287\)</span> years (some 105 days), 95% CI: <span class="math inline">\((22, 188)\)</span> days.</p>
<p>Again, I only took into consideration per capita GDP because Amoruso et al.&nbsp;didn’t. This should in no way be taken to mean that I think that <em>only</em> per capita GDP should be taken into account as a possible confounder.</p>
</section>
</section>
<section id="now-what" class="level2">
<h2 class="anchored" data-anchor-id="now-what">Now what?</h2>
<p>Suffice it to say that I think the authors ought to substantially revise their article, both in terms of how the analyses are conducted and interpreted and in terms of how the overall method is described. The analyses that I carried out using per capita GDP (as opposed to overall GDP) as a control variable are a start—not a suggestion of what the final model should look like. Further, I’ve only looked at the cross-sectional analyses as I think my comments on these already ought to prompt readers to take the entire study with a grain of salt. This doesn’t mean that I think that the longitudinal analyses that are also reported in the article are trustworthy—I’ve literally not looked at them. Finally, we’ve taken the authors’ method for quantifying accelerated ageing as-is, but I am somewhat skeptical of it.</p>
<p><strong>Update 2026/01/09:</strong> A slightly edited version of this blog post is now available as a preprint from <a href="https://osf.io/preprints/psyarxiv/rmnv9_v1">PsyArxiv Preprints</a>. The main change is that I log-transformed the per-capita GDP data for the preprint.</p>
</section>
<section id="software-versions" class="level2">
<h2 class="anchored" data-anchor-id="software-versions">Software versions</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>devtools<span class="sc">::</span><span class="fu">session_info</span>(<span class="st">"attached"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>─ Session info ───────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.5.1 (2025-06-13)
 os       Ubuntu 25.10
 system   x86_64, linux-gnu
 ui       X11
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       Europe/Zurich
 date     2026-07-13
 pandoc   3.8.3 @ /usr/lib/rstudio/resources/app/bin/quarto/bin/tools/x86_64/ (via rmarkdown)
 quarto   1.9.38 @ /usr/local/bin/quarto

─ Packages ───────────────────────────────────────────────────────────────────
 package   * version date (UTC) lib source
 dplyr     * 1.1.4   2023-11-17 [1] CRAN (R 4.5.1)
 DT        * 0.34.0  2025-09-02 [1] CRAN (R 4.5.1)
 forcats   * 1.0.1   2025-09-25 [1] CRAN (R 4.5.1)
 ggplot2   * 4.0.0   2025-09-11 [1] CRAN (R 4.5.1)
 lubridate * 1.9.4   2024-12-08 [1] CRAN (R 4.5.1)
 purrr     * 1.1.0   2025-07-10 [1] CRAN (R 4.5.1)
 readr     * 2.1.5   2024-01-10 [1] CRAN (R 4.5.1)
 stringr   * 1.5.2   2025-09-08 [1] CRAN (R 4.5.1)
 tibble    * 3.3.0   2025-06-08 [1] CRAN (R 4.5.1)
 tidyr     * 1.3.1   2024-01-24 [1] CRAN (R 4.5.1)
 tidyverse * 2.0.0   2023-02-22 [1] CRAN (R 4.5.1)

 [1] /home/jan/R/x86_64-pc-linux-gnu-library/4.5
 [2] /usr/local/lib/R/site-library
 [3] /usr/lib/R/site-library
 [4] /usr/lib/R/library
 * ── Packages attached to the search path.

──────────────────────────────────────────────────────────────────────────────</code></pre>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/janhove\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>