{
  "hash": "52ce5180e7e882398e898e122b6a01ba",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Baby steps in Bayes: Recoding predictors and homing in on specific comparisons\"\ndate: \"2018-12-20\"\ncategories: [Bayesian statistics, brms, R, graphs, mixed-effects models, contrast coding]\nexecute: \n  cache: true\n---\n\nInterpreting models that take into account a host of possible interactions between predictor variables can be a pain, especially when some of the predictors contain more than two levels. In this post, I show how I went about fitting and then making sense of a multilevel model containing a three-way interaction between its categorical fixed-effect predictors. To this end, I used the [`brms`](https://github.com/paul-buerkner/brms) package, which makes it relatively easy to fit Bayesian models using a notation that hardly differs from the one used in the popular `lme4` package. I won't discuss the Bayesian bit much here (I don't think it's too important), and I will instead cover the following points:\n\n1.  How to fit a multilevel model with `brms` using `R`'s default way of handling categorical predictors (treatment coding).\n2.  How to interpret this model's fixed parameter estimates.\n3.  How to visualise the modelled effects.\n4.  How to recode predictors to obtain more useful parameter estimates.\n5.  How to extract information from the model to home in on specific comparisons.\n\n## The data\n\nFor a longitudinal project, 328 children wrote narrative and argumentative texts in Portuguese at three points in time. About a third of the children hailed from Portugal, about a third were children of Portuguese heritage living in the French-speaking part of Switzerland, and about a third were children of Portuguese heritage living in the German-speaking part of Switzerland. Not all children wrote both kinds of texts at all three points in time, and 1,040 texts were retained for the analysis. For each text, we computed the Guiraud index, which is a function of the number of words (tokens) and the number of *different* words (types) in the texts. Higher values are assumed to reflect greater diversity in vocabulary use.\n\nIf you want to know more about this project, check out Bonvin et al. (2018), Lambelet et al. (2017a,b) and Vanhove et al. (2019); you'll find the references at the bottom of this page.\n\n**Update (2023-08-06):** I ran all of the R code again with newer software versions when converting the format of this blog.\n\nRead in the data:\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load tidyverse suite\nlibrary(tidyverse)\n\n# Read in data from my webspace\nd <- read_csv(\"http://homeweb.unifr.ch/VanhoveJ/Pub/Data/portuguese_guiraud.csv\")\n\n# Need to code factors explicitly\nd$Group    <- factor(d$Group)\nd$TextType <- factor(d$TextType)\nd$Time     <- factor(d$Time)\n\nstr(d)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nspc_tbl_ [1,040 × 6] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\n $ Group   : Factor w/ 3 levels \"monolingual Portuguese\",..: 1 1 1 1 1 1 1 1 1 1 ...\n $ Class   : chr [1:1040] \"monolingual Portuguese_AI\" \"monolingual Portuguese_AI\" \"monolingual Portuguese_AI\" \"monolingual Portuguese_AI\" ...\n $ Child   : chr [1:1040] \"monolingual Portuguese_AI_1\" \"monolingual Portuguese_AI_1\" \"monolingual Portuguese_AI_1\" \"monolingual Portuguese_AI_10\" ...\n $ Time    : Factor w/ 3 levels \"T1\",\"T2\",\"T3\": 1 1 2 1 1 3 3 1 3 1 ...\n $ TextType: Factor w/ 2 levels \"argumentative\",..: 1 2 2 1 2 1 2 2 2 1 ...\n $ Guiraud : num [1:1040] 4.73 5.83 3.9 4.22 4.57 ...\n - attr(*, \"spec\")=\n  .. cols(\n  ..   Group = col_character(),\n  ..   Class = col_character(),\n  ..   Child = col_character(),\n  ..   Time = col_character(),\n  ..   TextType = col_character(),\n  ..   Guiraud = col_double()\n  .. )\n - attr(*, \"problems\")=<externalptr> \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(d)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    Group        Class              Child           Time    \n monolingual Portuguese:360   Length:1040        Length:1040        T1:320  \n Portuguese-French     :360   Class :character   Class :character   T2:340  \n Portuguese-German     :320   Mode  :character   Mode  :character   T3:380  \n                                                                            \n                                                                            \n                                                                            \n          TextType      Guiraud    \n argumentative:560   Min.   :2.32  \n narrative    :480   1st Qu.:3.93  \n                     Median :4.64  \n                     Mean   :4.75  \n                     3rd Qu.:5.48  \n                     Max.   :8.43  \n```\n\n\n:::\n:::\n\n\nLet's also plot the data. Incidentally, and contrary to popular belief, I don't write `ggplot` code such as this from scratch. What you see is the result of drawing and redrawing (see comments).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot Guiraud scores\nggplot(d,\n       aes(x = Time,\n           y = Guiraud,\n           # reorder: sort the Groups by their median Guiraud value\n           fill = reorder(Group, Guiraud, median))) +\n  # I prefer empty (shape = 1) to filled circles (shape = 16).\n  geom_boxplot(outlier.shape = 1) +\n  facet_grid(. ~ TextType) +\n  # The legend name (\"Group\") seems superfluous, so suppress it;\n  # the default colours contain red and green, which can be hard to\n  #  distinguish for some people.\n  scale_fill_brewer(name = element_blank(), type = \"qual\") +\n  # I prefer the black and white look to the default grey one.\n  theme_bw() +\n  # Put the legend at the bottom rather than on the right\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![**Figure 1.** The texts' Guiraud values by time of data collection, text type, and language background.](index_files/figure-html/unnamed-chunk-3-1.svg)\n:::\n:::\n\n\n## A multilevel model with treatment coding\n\nOur data are nested: Each child wrote up to 6 texts, and the data were collected in classes, with each child belong to one class. It's advisable to take such nesting into account since you may end up overestimating your degree of certainty about the results otherwise. I mostly use `lme4`'s `lmer()` and `glmer()` functions to handle such data, but as will become clearer in a minute, `brms`'s `brm()` function offers some distinct advantages. So let's load that package:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(brms)\n```\n:::\n\n\n### Fitting the model\n\nWe'll fit a model with a three-way fixed-effect interaction between `Time`, `TextType` and `Group` as well as with by-`Child` and by-`Class` random intercepts. In order to take into account the possibility that children vary in the development of their lexical diversity, we add a random slope of `Time` by `Child`, and in order to take into account the possibility that their lexical diversity varies by text type, we do the same for `TextType`. Similarly, we add by-`Class` random slopes for `Time` and `TextType`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_default <- brm(Guiraud ~ Time*TextType*Group +\n                   (1 + TextType + Time|Class) +\n                   (1 + TextType + Time|Child),\n                 cores = 4, iter = 4000,\n                 silent = 2,\n                 control = list(adapt_delta = 0.95),\n                 data = d)\n```\n:::\n\n\n### Interpreting the parameter estimates\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m_default)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: gaussian \n  Links: mu = identity \nFormula: Guiraud ~ Time * TextType * Group + (1 + TextType + Time | Class) + (1 + TextType + Time | Child) \n   Data: d (Number of observations: 1040) \n  Draws: 4 chains, each with iter = 4000; warmup = 2000; thin = 1;\n         total post-warmup draws = 8000\n\nMultilevel Hyperparameters:\n~Child (Number of levels: 328) \n                                 Estimate Est.Error l-95% CI u-95% CI Rhat\nsd(Intercept)                        0.42      0.05     0.33     0.52 1.00\nsd(TextTypenarrative)                0.26      0.09     0.05     0.43 1.01\nsd(TimeT2)                           0.09      0.07     0.00     0.24 1.00\nsd(TimeT3)                           0.39      0.09     0.21     0.55 1.01\ncor(Intercept,TextTypenarrative)     0.24      0.28    -0.27     0.80 1.00\ncor(Intercept,TimeT2)               -0.09      0.41    -0.81     0.74 1.00\ncor(TextTypenarrative,TimeT2)        0.05      0.43    -0.78     0.81 1.00\ncor(Intercept,TimeT3)                0.15      0.23    -0.25     0.67 1.01\ncor(TextTypenarrative,TimeT3)       -0.04      0.30    -0.60     0.61 1.00\ncor(TimeT2,TimeT3)                   0.09      0.44    -0.75     0.85 1.02\n                                 Bulk_ESS Tail_ESS\nsd(Intercept)                        2812     4473\nsd(TextTypenarrative)                 488      756\nsd(TimeT2)                           1147     1896\nsd(TimeT3)                            566     1120\ncor(Intercept,TextTypenarrative)      736     2131\ncor(Intercept,TimeT2)                6991     4697\ncor(TextTypenarrative,TimeT2)        3272     5945\ncor(Intercept,TimeT3)                 716     1250\ncor(TextTypenarrative,TimeT3)         530     1180\ncor(TimeT2,TimeT3)                    289      962\n\n~Class (Number of levels: 25) \n                                 Estimate Est.Error l-95% CI u-95% CI Rhat\nsd(Intercept)                        0.16      0.08     0.02     0.33 1.00\nsd(TextTypenarrative)                0.25      0.08     0.10     0.42 1.00\nsd(TimeT2)                           0.11      0.07     0.01     0.28 1.00\nsd(TimeT3)                           0.10      0.07     0.00     0.27 1.00\ncor(Intercept,TextTypenarrative)    -0.15      0.37    -0.77     0.62 1.00\ncor(Intercept,TimeT2)               -0.09      0.43    -0.82     0.75 1.00\ncor(TextTypenarrative,TimeT2)        0.08      0.41    -0.71     0.80 1.00\ncor(Intercept,TimeT3)                0.13      0.43    -0.74     0.85 1.00\ncor(TextTypenarrative,TimeT3)       -0.15      0.41    -0.84     0.68 1.00\ncor(TimeT2,TimeT3)                   0.10      0.44    -0.75     0.84 1.00\n                                 Bulk_ESS Tail_ESS\nsd(Intercept)                        1287     1728\nsd(TextTypenarrative)                2038     1642\nsd(TimeT2)                           2457     3574\nsd(TimeT3)                           2513     3009\ncor(Intercept,TextTypenarrative)     2373     3458\ncor(Intercept,TimeT2)                5754     5433\ncor(TextTypenarrative,TimeT2)        6168     6098\ncor(Intercept,TimeT3)                6103     5865\ncor(TextTypenarrative,TimeT3)        6407     5928\ncor(TimeT2,TimeT3)                   5602     6387\n\nRegression Coefficients:\n                                                Estimate Est.Error l-95% CI\nIntercept                                           5.25      0.13     4.99\nTimeT2                                              0.57      0.13     0.32\nTimeT3                                              0.92      0.14     0.64\nTextTypenarrative                                  -0.26      0.18    -0.61\nGroupPortugueseMFrench                             -1.06      0.17    -1.40\nGroupPortugueseMGerman                             -1.30      0.17    -1.63\nTimeT2:TextTypenarrative                           -0.24      0.16    -0.57\nTimeT3:TextTypenarrative                           -0.06      0.17    -0.39\nTimeT2:GroupPortugueseMFrench                      -0.55      0.18    -0.91\nTimeT3:GroupPortugueseMFrench                      -0.38      0.19    -0.74\nTimeT2:GroupPortugueseMGerman                      -0.64      0.18    -1.00\nTimeT3:GroupPortugueseMGerman                      -0.23      0.20    -0.62\nTextTypenarrative:GroupPortugueseMFrench            0.14      0.24    -0.33\nTextTypenarrative:GroupPortugueseMGerman            0.18      0.24    -0.30\nTimeT2:TextTypenarrative:GroupPortugueseMFrench     0.37      0.24    -0.11\nTimeT3:TextTypenarrative:GroupPortugueseMFrench     0.25      0.24    -0.22\nTimeT2:TextTypenarrative:GroupPortugueseMGerman     0.55      0.25     0.06\nTimeT3:TextTypenarrative:GroupPortugueseMGerman     0.27      0.25    -0.23\n                                                u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept                                           5.51 1.00     3025     4012\nTimeT2                                              0.84 1.00     3131     4204\nTimeT3                                              1.19 1.00     3148     4685\nTextTypenarrative                                   0.09 1.00     2486     4100\nGroupPortugueseMFrench                             -0.70 1.00     3201     4467\nGroupPortugueseMGerman                             -0.96 1.00     3052     4142\nTimeT2:TextTypenarrative                            0.08 1.00     3290     5287\nTimeT3:TextTypenarrative                            0.27 1.00     3221     4880\nTimeT2:GroupPortugueseMFrench                      -0.20 1.00     3517     4684\nTimeT3:GroupPortugueseMFrench                      -0.01 1.00     3485     5470\nTimeT2:GroupPortugueseMGerman                      -0.29 1.00     3477     4481\nTimeT3:GroupPortugueseMGerman                       0.15 1.00     3416     5390\nTextTypenarrative:GroupPortugueseMFrench            0.62 1.00     3078     4651\nTextTypenarrative:GroupPortugueseMGerman            0.65 1.00     2626     3876\nTimeT2:TextTypenarrative:GroupPortugueseMFrench     0.84 1.00     3863     5728\nTimeT3:TextTypenarrative:GroupPortugueseMFrench     0.72 1.00     3538     5159\nTimeT2:TextTypenarrative:GroupPortugueseMGerman     1.05 1.00     3820     5109\nTimeT3:TextTypenarrative:GroupPortugueseMGerman     0.76 1.00     3447     5446\n\nFurther Distributional Parameters:\n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma     0.60      0.02     0.56     0.65 1.01      783     2117\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::\n\n\nThe output looks pretty similar to what we'd obtain when using `lmer()`, but let's review what these estimates actually refer to. By default, `R` uses treatment coding. This entails that the `Intercept` refers to a specific combination of factors: the combination of all reference levels. Again by default, the reference levels are chosen alphabetically:\n\n-   `Time` consists of three levels (`T1`, `T2`, `T3`); for alphabetical reasons, `T1` is chosen as the default reference level.\n-   `Group` also consists of three levels (`monolingual Portuguese`, `Portuguese-French`, `Portuguese-German`); `monolingual Portuguese` is chosen as the default level.\n-   `TextType` consists of two levels (`argumentative`, `narrative`); `argumentative` is the default reference level.\n\nThe `Intercept`, then, shows the modelled mean Guiraud value of `argumentative` texts written by `monolingual Portuguese` children at `T1`: 5.25.\n\nIf you're unsure which factor level was used as the reference level, you can use the `contrasts()` function. The reference level is the one in whose rows only zeroes occur.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrasts(d$Group)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                       Portuguese-French Portuguese-German\nmonolingual Portuguese                 0                 0\nPortuguese-French                      1                 0\nPortuguese-German                      0                 1\n```\n\n\n:::\n:::\n\n\nCrucially, all other estimated effects are computed with respect to this intercept. That is, `TimeT2` (0.57) shows the difference between T1 and T2 *for monolingual Portuguese children writing argumentative texts*. Similarly, `TimeT3` (0.91) shows the difference between *T1* and T3 for monolingual Portuguese children writing argumentative texts, and `TextTypenarrative` (-0.27) shows the difference between the mean Guiraud values of argumentative and narrative texts written by monolingual Portuguese children writing at T1. The texts written by the Portuguese-German and Portuguese-French bilinguals don't enter into these estimates.\n\nNow, it's possible to piece together the mean values associated with each combination of predictor values, but questions such as the following remain difficult to answer with just these estimates at hand:\n\n-   What's the overall difference between T2 and T3 and its uncertainty?\n-   What's the overall difference between the Guiraud values of texts written by Portuguese-French and Portuguese-German children and its uncertainty?\n-   ...\n\nWe'll tackle these questions in a minute; for now, the point is merely that the estimated parameters above all refer to highly specific comparisons that may not be the most relevant.\n\n### Plotting the fitted values and the uncertainty about them\n\nWhen working with `brms`, it's relatively easy to obtain the modelled average outcome value for each combination of the predictor variables as well as a measure of the uncertainty associated with them.\n\nFirst construct a small data frame containing the unique combinations of predictor variables in our dataset:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd_pred <- d |> \n  select(Group, Time, TextType) |> \n  distinct() |> \n  arrange(Group, Time, TextType)\nd_pred\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 18 × 3\n   Group                  Time  TextType     \n   <fct>                  <fct> <fct>        \n 1 monolingual Portuguese T1    argumentative\n 2 monolingual Portuguese T1    narrative    \n 3 monolingual Portuguese T2    argumentative\n 4 monolingual Portuguese T2    narrative    \n 5 monolingual Portuguese T3    argumentative\n 6 monolingual Portuguese T3    narrative    \n 7 Portuguese-French      T1    argumentative\n 8 Portuguese-French      T1    narrative    \n 9 Portuguese-French      T2    argumentative\n10 Portuguese-French      T2    narrative    \n11 Portuguese-French      T3    argumentative\n12 Portuguese-French      T3    narrative    \n13 Portuguese-German      T1    argumentative\n14 Portuguese-German      T1    narrative    \n15 Portuguese-German      T2    argumentative\n16 Portuguese-German      T2    narrative    \n17 Portuguese-German      T3    argumentative\n18 Portuguese-German      T3    narrative    \n```\n\n\n:::\n:::\n\n\nIf you feed the model (here: `m_default`) and the data frame we've just created (`d_pred`) to the `fitted()` function, it outputs the modelled mean estimate for each combination of predictor values (`Estimate`), the estimated error of this mean estimate (`Est.Error`), and a 95% uncertainty interval about the estimate (`Q2.5` and `Q97.5`). One more thing: The `re_formula = NA` line specifies that we do not want the variability associated with the by-`Class` and by-`Child` random effects to affect the estimates and their uncertainty. This is what I typically want.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncbind(\n  d_pred, \n  fitted(m_default, \n         newdata = d_pred, \n         re_formula = NA)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    Group Time      TextType Estimate Est.Error Q2.5 Q97.5\n1  monolingual Portuguese   T1 argumentative     5.25     0.131 4.99  5.51\n2  monolingual Portuguese   T1     narrative     4.99     0.181 4.63  5.35\n3  monolingual Portuguese   T2 argumentative     5.82     0.140 5.55  6.11\n4  monolingual Portuguese   T2     narrative     5.32     0.191 4.93  5.69\n5  monolingual Portuguese   T3 argumentative     6.17     0.159 5.84  6.48\n6  monolingual Portuguese   T3     narrative     5.84     0.193 5.45  6.24\n7       Portuguese-French   T1 argumentative     4.19     0.117 3.97  4.42\n8       Portuguese-French   T1     narrative     4.07     0.162 3.75  4.40\n9       Portuguese-French   T2 argumentative     4.21     0.124 3.97  4.46\n10      Portuguese-French   T2     narrative     4.22     0.158 3.91  4.52\n11      Portuguese-French   T3 argumentative     4.73     0.131 4.48  4.99\n12      Portuguese-French   T3     narrative     4.80     0.157 4.49  5.11\n13      Portuguese-German   T1 argumentative     3.95     0.109 3.74  4.17\n14      Portuguese-German   T1     narrative     3.87     0.151 3.57  4.16\n15      Portuguese-German   T2 argumentative     3.88     0.116 3.65  4.11\n16      Portuguese-German   T2     narrative     4.10     0.159 3.79  4.41\n17      Portuguese-German   T3 argumentative     4.64     0.129 4.38  4.89\n18      Portuguese-German   T3     narrative     4.76     0.148 4.46  5.05\n```\n\n\n:::\n:::\n\n\nSo where do these estimates and uncertainty intervals come from? In the Bayesian approach, every model parameter hasn't got just one estimate but an entire distribution of estimates. Moreover, everything that *depends* on model parameters also has an entire distribution of estimates associated with it. The mean modelled outcome values per cell depend on the model parameters, so they, too, have entire distributions associated with them. The `fitted()` function summarises these distributions for us: it returns their means as `Estimate`, their standard deviations as `Est.Error` and their 2.5th and 97.5 percentiles as `Q2.5` and `Q97.5`. If so inclined, you can generate these distributions yourself using the `posterior_linpred()` function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nposterior_fit <- posterior_linpred(m_default, newdata = d_pred, re_formula = NA)\ndim(posterior_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8000   18\n```\n\n\n:::\n:::\n\n\nThis returns matrix of 4000 rows and 18 columns. 4000 is the number of 'post-warmup samples' (see the output of `summary(m_default)`; 18 is the number of combinations of predictor values in `d_pred`.\n\nThe first *column* of `posterior_fit` contains the distribution associated with the first *row* in `d_pred`. If you compute its mean, standard deviation and 2.5th and 97.5th percentiles, you end up with the same numbers as above:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(posterior_fit[, 1])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.25\n```\n\n\n:::\n\n```{.r .cell-code}\nsd(posterior_fit[, 1])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.131\n```\n\n\n:::\n\n```{.r .cell-code}\nquantile(posterior_fit[, 1], probs = c(0.025, 0.975))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 2.5% 97.5% \n 4.99  5.51 \n```\n\n\n:::\n:::\n\n\nOr similarly for the 10th row of `d_pred` (Portuguese-French, T2, narrative):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(posterior_fit[, 10])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.22\n```\n\n\n:::\n\n```{.r .cell-code}\nsd(posterior_fit[, 10])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.158\n```\n\n\n:::\n\n```{.r .cell-code}\nquantile(posterior_fit[, 10], probs = c(0.025, 0.975))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 2.5% 97.5% \n 3.91  4.52 \n```\n\n\n:::\n:::\n\n\nAt the moment, using `posterior_linpred()` has no added value, but it's good to know where these numbers come from.\n\nLet's draw a graph showing these modelled averages and the uncertainty about them. 95% uncertainty intervals are typically used, but they may instill dichotomous thinking. To highlight that such an interval highlights but two points on a continuum, I'm tempted to add 80% intervals as well:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Obtain fitted values + uncertainty\nfitted_values <- fitted(m_default, newdata = d_pred, re_formula = NA, \n                        # 95% interval: between 2.5th and 97.5th percentile\n                        # 80% interval: between 10th and 90th percentile\n                        probs = c(0.025, 0.10, 0.90, 0.975))\n# Combine fitted values with predictor values\nfitted_values <- cbind(d_pred, fitted_values)\nfitted_values\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    Group Time      TextType Estimate Est.Error Q2.5  Q10  Q90\n1  monolingual Portuguese   T1 argumentative     5.25     0.131 4.99 5.09 5.42\n2  monolingual Portuguese   T1     narrative     4.99     0.181 4.63 4.77 5.22\n3  monolingual Portuguese   T2 argumentative     5.82     0.140 5.55 5.65 6.00\n4  monolingual Portuguese   T2     narrative     5.32     0.191 4.93 5.08 5.56\n5  monolingual Portuguese   T3 argumentative     6.17     0.159 5.84 5.97 6.37\n6  monolingual Portuguese   T3     narrative     5.84     0.193 5.45 5.60 6.09\n7       Portuguese-French   T1 argumentative     4.19     0.117 3.97 4.04 4.34\n8       Portuguese-French   T1     narrative     4.07     0.162 3.75 3.87 4.28\n9       Portuguese-French   T2 argumentative     4.21     0.124 3.97 4.06 4.37\n10      Portuguese-French   T2     narrative     4.22     0.158 3.91 4.02 4.42\n11      Portuguese-French   T3 argumentative     4.73     0.131 4.48 4.56 4.89\n12      Portuguese-French   T3     narrative     4.80     0.157 4.49 4.60 5.00\n13      Portuguese-German   T1 argumentative     3.95     0.109 3.74 3.81 4.09\n14      Portuguese-German   T1     narrative     3.87     0.151 3.57 3.67 4.06\n15      Portuguese-German   T2 argumentative     3.88     0.116 3.65 3.73 4.02\n16      Portuguese-German   T2     narrative     4.10     0.159 3.79 3.90 4.30\n17      Portuguese-German   T3 argumentative     4.64     0.129 4.38 4.47 4.80\n18      Portuguese-German   T3     narrative     4.76     0.148 4.46 4.57 4.95\n   Q97.5\n1   5.51\n2   5.35\n3   6.11\n4   5.69\n5   6.48\n6   6.24\n7   4.42\n8   4.40\n9   4.46\n10  4.52\n11  4.99\n12  5.11\n13  4.17\n14  4.16\n15  4.11\n16  4.41\n17  4.89\n18  5.05\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nAnd now for the graph:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Move all points apart horizontally to reduce overlap\nposition_adjustment <- position_dodge(width = 0.3)\n\nggplot(fitted_values,\n       aes(x = Time,\n           y = Estimate,\n           # Sort Groups from low to high\n           colour = reorder(Group, Estimate),\n           group = Group)) +\n  # Move point apart:\n  geom_point(position = position_adjustment) +\n  # Move lines apart:\n  geom_path(position = position_adjustment) +\n  # Add 95% intervals; move them apart, too\n  geom_linerange(aes(ymin = Q2.5, ymax = Q97.5), linewidth = 0.4,\n                 position = position_adjustment) +\n  # Add 80% intervals; move them apart, too\n  geom_linerange(aes(ymin = Q10, ymax = Q90), linewidth = 0.9,\n                 position = position_adjustment) +\n  facet_wrap(~ TextType) +\n  # Override default colour\n  scale_colour_brewer(name = element_blank(), type = \"qual\") +\n  ylab(\"Modelled mean Guiraud\") +\n  theme_bw() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![**Figure 2.** The modelled mean Guiraud values and their uncertainty (thick vertical lines: 80% interval; thin vertical lines: 95% interval).](index_files/figure-html/unnamed-chunk-15-1.svg)\n:::\n:::\n\n\n## A model with more sensible coding\n\n### Tailoring the coding of categorical predictors to the research questions\n\nThe `summary()` output for `m_default` was difficult to interpret because treatment coding was used. However, we can override this default behaviour to end up with estimates that are more readily and more usefully interpretable.\n\nThe first thing we can do is to override the default refence level. Figure 1 showed that the Guiraud values at T2 tend to be somewhere midway between those at T1 and T3, so we can make the intercept estimate more representative of the dataset as a whole by making T2 the reference level of `Time` rather than T1. A benefit of doing so is that we will now have two parameters, `TimeT1` and `TimeT3` that specify the difference between T1-T2 and T2-T3, respectively. In other words, the estimated parameters will directly reflect the progression from data collection to data collection. (Before, the parameter estimates specified the differences between T1-T2 and *T1*-T3, so a direct estimate for T2-T3 was lacking.)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Set T2 as default time; retain treatment coding\nd$Time <- relevel(d$Time, \"T2\")\n```\n:::\n\n\nSecond, there's no reason for preferring `argumentative` or `narrative` texts as the reference level. If we sum-code this predictor, the intercept reflects the *grand mean* of the argumentative and narrative texts (at T2), and the estimated parameter then specifies how far the mean Guiraud value of each text type is removed from this mean:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Sum (or deviation) coding for TextType (2 levels)\ncontrasts(d$TextType) <- contr.sum(2)\n```\n:::\n\n\nSimilarly, there are a couple of reasonable ways to choose the reference level for `Group` when using treatment coding. But you can also sum-code this predictor so that the intercept reflects the grand mean of the Guiraud values of texts written by monolingual Portuguese and bilingual Portuguese-French and Portuguese-German kids (at T2).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Sum (or deviation) coding for Group (3 levels)\ncontrasts(d$Group) <- contr.sum(3)\n```\n:::\n\n\n### Refitting the model\n\nNo difference here.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_recoded <- brm(Guiraud ~ Time*TextType*Group +\n                   (1 + TextType + Time|Class) +\n                   (1 + TextType + Time|Child),\n                 cores = 4, iter = 4000,\n                 silent = 2,\n                 control = list(adapt_delta = 0.95),\n                 data = d)\n```\n:::\n\n\n### Interpreting the parameter estimates\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m_recoded)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: gaussian \n  Links: mu = identity \nFormula: Guiraud ~ Time * TextType * Group + (1 + TextType + Time | Class) + (1 + TextType + Time | Child) \n   Data: d (Number of observations: 1040) \n  Draws: 4 chains, each with iter = 4000; warmup = 2000; thin = 1;\n         total post-warmup draws = 8000\n\nMultilevel Hyperparameters:\n~Child (Number of levels: 328) \n                         Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS\nsd(Intercept)                0.46      0.04     0.38     0.55 1.00     2275\nsd(TextType1)                0.13      0.05     0.03     0.22 1.00      706\nsd(TimeT1)                   0.10      0.08     0.00     0.28 1.00     1022\nsd(TimeT3)                   0.38      0.09     0.18     0.54 1.01      590\ncor(Intercept,TextType1)    -0.47      0.21    -0.86    -0.02 1.00     2148\ncor(Intercept,TimeT1)       -0.04      0.39    -0.77     0.73 1.00     5998\ncor(TextType1,TimeT1)        0.05      0.43    -0.78     0.80 1.00     3249\ncor(Intercept,TimeT3)        0.14      0.23    -0.24     0.66 1.01      926\ncor(TextType1,TimeT3)        0.03      0.32    -0.63     0.62 1.01      510\ncor(TimeT1,TimeT3)          -0.02      0.42    -0.81     0.77 1.02      268\n                         Tail_ESS\nsd(Intercept)                4601\nsd(TextType1)                1278\nsd(TimeT1)                   1980\nsd(TimeT3)                    859\ncor(Intercept,TextType1)     3347\ncor(Intercept,TimeT1)        4574\ncor(TextType1,TimeT1)        5031\ncor(Intercept,TimeT3)        1331\ncor(TextType1,TimeT3)        1297\ncor(TimeT1,TimeT3)            892\n\n~Class (Number of levels: 25) \n                         Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS\nsd(Intercept)                0.18      0.07     0.04     0.34 1.00     1298\nsd(TextType1)                0.12      0.04     0.05     0.21 1.00     2542\nsd(TimeT1)                   0.10      0.07     0.01     0.27 1.00     2235\nsd(TimeT3)                   0.10      0.07     0.00     0.27 1.00     2161\ncor(Intercept,TextType1)    -0.20      0.35    -0.79     0.56 1.00     2368\ncor(Intercept,TimeT1)       -0.14      0.42    -0.84     0.74 1.00     5527\ncor(TextType1,TimeT1)       -0.03      0.41    -0.78     0.76 1.00     6213\ncor(Intercept,TimeT3)        0.04      0.43    -0.76     0.80 1.00     5339\ncor(TextType1,TimeT3)        0.16      0.42    -0.69     0.85 1.00     5890\ncor(TimeT1,TimeT3)           0.11      0.44    -0.78     0.85 1.00     4306\n                         Tail_ESS\nsd(Intercept)                1281\nsd(TextType1)                2768\nsd(TimeT1)                   3747\nsd(TimeT3)                   3171\ncor(Intercept,TextType1)     3745\ncor(Intercept,TimeT1)        5022\ncor(TextType1,TimeT1)        6110\ncor(Intercept,TimeT3)        5475\ncor(TextType1,TimeT3)        5570\ncor(TimeT1,TimeT3)           5635\n\nRegression Coefficients:\n                        Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS\nIntercept                   4.59      0.06     4.47     4.72 1.00     4328\nTimeT1                     -0.21      0.06    -0.33    -0.08 1.00     6617\nTimeT3                      0.56      0.06     0.44     0.69 1.00     6613\nTextType1                   0.05      0.05    -0.05     0.14 1.00     4556\nGroup1                      0.98      0.10     0.78     1.17 1.00     3423\nGroup2                     -0.38      0.09    -0.56    -0.19 1.00     3473\nTimeT1:TextType1            0.03      0.05    -0.07     0.13 1.00     6741\nTimeT3:TextType1           -0.02      0.05    -0.12     0.08 1.00     6181\nTimeT1:Group1              -0.24      0.09    -0.41    -0.08 1.00     4832\nTimeT3:Group1              -0.13      0.09    -0.30     0.04 1.00     5460\nTimeT1:Group2               0.12      0.09    -0.05     0.30 1.00     4994\nTimeT3:Group2              -0.01      0.09    -0.18     0.16 1.00     5093\nTextType1:Group1            0.20      0.07     0.06     0.34 1.00     3541\nTextType1:Group2           -0.04      0.07    -0.17     0.09 1.00     3527\nTimeT1:TextType1:Group1    -0.15      0.07    -0.28    -0.01 1.00     6125\nTimeT3:TextType1:Group1    -0.07      0.07    -0.20     0.07 1.00     6193\nTimeT1:TextType1:Group2     0.03      0.07    -0.11     0.17 1.00     5731\nTimeT3:TextType1:Group2    -0.01      0.07    -0.14     0.12 1.00     5675\n                        Tail_ESS\nIntercept                   4832\nTimeT1                      5591\nTimeT3                      6012\nTextType1                   5530\nGroup1                      4024\nGroup2                      4055\nTimeT1:TextType1            6272\nTimeT3:TextType1            5424\nTimeT1:Group1               5080\nTimeT3:Group1               5557\nTimeT1:Group2               5074\nTimeT3:Group2               4939\nTextType1:Group1            4792\nTextType1:Group2            4530\nTimeT1:TextType1:Group1     5989\nTimeT3:TextType1:Group1     6461\nTimeT1:TextType1:Group2     6285\nTimeT3:TextType1:Group2     6247\n\nFurther Distributional Parameters:\n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma     0.60      0.02     0.55     0.65 1.00      909     1428\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::\n\n\nNow the `Intercept` reflects the grand mean of the Guiraud values for both argumentative and narrative texts for all three groups **written at T2**. The `TimeT1` estimate (-0.20) shows the difference between T1 and T2 averaged over all text types and all groups (0.20 points worse at T1); the `TimeT3` estimate (0.56) shows the difference between T2 and T3 averaged over all text types and all groups (0.56 points better at T3).\n\n`TextType1` (0.05) shows that the mean Guiraud value of one text type (still written at T2!) averaged over all groups is 0.05 points higher than the grand mean; and by implication that the mean Guiraud value of the other text type is 0.05 lower than the grand mean. To find out which text type is which, use `contrasts()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrasts(d$TextType)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              [,1]\nargumentative    1\nnarrative       -1\n```\n\n\n:::\n:::\n\n\nSince `argumentative` is coded as 1, it's the argumentative texts that have the higher Guiraud values at T2.\n\nSimilarly, `Group1` (0.98) shows that one group has higher-than-average Guiraud values averaged across text types at T2, whereas `Group2` (-0.38) shows that another group has a mean Guiraud value that lies 0.38 points below the average at T2. By implication, the third group's mean Guiraud value lies 0.60 points below average ((0.98-0.38-0.60)/3 = 0). To see which group is which, use `contrasts()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrasts(d$Group)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                       [,1] [,2]\nmonolingual Portuguese    1    0\nPortuguese-French         0    1\nPortuguese-German        -1   -1\n```\n\n\n:::\n:::\n\n\n`monolingual Portuguese` is '1' for the purposes of `Group1`, `Portuguese-French` is `1` for the purposes of `Group2`, and `Portuguese-German` is the third group.\n\nWe can double-check these numbers by generating the modelled mean values for each predictor value combination:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndouble_check <- cbind(\n  d_pred, \n  fitted(m_recoded, \n         newdata = d_pred, \n         re_formula = NA)\n  )\ndouble_check\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    Group Time      TextType Estimate Est.Error Q2.5 Q97.5\n1  monolingual Portuguese   T1 argumentative     5.25     0.151 4.95  5.55\n2  monolingual Portuguese   T1     narrative     4.99     0.171 4.65  5.33\n3  monolingual Portuguese   T2 argumentative     5.82     0.142 5.54  6.10\n4  monolingual Portuguese   T2     narrative     5.32     0.166 4.98  5.65\n5  monolingual Portuguese   T3 argumentative     6.16     0.170 5.82  6.50\n6  monolingual Portuguese   T3     narrative     5.84     0.179 5.48  6.19\n7       Portuguese-French   T1 argumentative     4.19     0.131 3.94  4.46\n8       Portuguese-French   T1     narrative     4.06     0.160 3.75  4.37\n9       Portuguese-French   T2 argumentative     4.21     0.124 3.97  4.46\n10      Portuguese-French   T2     narrative     4.21     0.141 3.94  4.50\n11      Portuguese-French   T3 argumentative     4.73     0.138 4.46  5.01\n12      Portuguese-French   T3     narrative     4.79     0.152 4.50  5.11\n13      Portuguese-German   T1 argumentative     3.95     0.116 3.72  4.18\n14      Portuguese-German   T1     narrative     3.88     0.148 3.58  4.16\n15      Portuguese-German   T2 argumentative     3.88     0.115 3.65  4.10\n16      Portuguese-German   T2     narrative     4.11     0.145 3.83  4.40\n17      Portuguese-German   T3 argumentative     4.64     0.135 4.36  4.90\n18      Portuguese-German   T3     narrative     4.76     0.142 4.48  5.04\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nSome sanity checks:\n\n(1) Intercept = 4.59 = grand mean at T2:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndouble_check |> \n  filter(Time == \"T2\") |> \n  summarise(mean_est = mean(Estimate))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  mean_est\n1     4.59\n```\n\n\n:::\n:::\n\n\n(2) TimeT3 = 0.56 = T2/T3 difference across texts and groups:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndouble_check |> \n  group_by(Time) |> \n  summarise(mean_est = mean(Estimate)) |> \n  spread(Time, mean_est) |> \n  summarise(diff_T2T3 = T3 - T2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  diff_T2T3\n      <dbl>\n1     0.562\n```\n\n\n:::\n:::\n\n\n(3) Portuguese-German lies 0.60 below average at T2 across texts:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndouble_check |> \n  filter(Time == \"T2\") |> \n  group_by(Group) |> \n  summarise(mean_est = mean(Estimate)) |> \n  mutate(diff_mean = mean_est - mean(mean_est))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  Group                  mean_est diff_mean\n  <fct>                     <dbl>     <dbl>\n1 monolingual Portuguese     5.57     0.977\n2 Portuguese-French          4.21    -0.381\n3 Portuguese-German          4.00    -0.596\n```\n\n\n:::\n:::\n\n\nI won't plot the modelled averages and their uncertainty, because the result will be the same as before: Recoding the predictors in this way doesn't affect the modelled averages per cell; it just makes the summary output easier to parse.\n\n### Homing in on specific comparisons\n\nFinally, let's see how we can target some specific comparisons without having to refit the model several times. A specific comparison you might be interested in could be \"How large is the difference in Guiraud scores for narrative texts written by Portuguese-French bilinguals between T1 and T2?\" Or a more complicated one: \"How large is the difference in the progression from T1 to T3 for argumentative texts between Portuguese-French and Portuguese-German children?\"\n\nTo answer such questions, we need to generate the distribution of the modelled averages per predictor value combination:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nposterior_fit <- posterior_linpred(m_recoded, newdata = d_pred, re_formula = NA)\n```\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n#### Question 1: Progression T1-T2 for narrative texts, Portuguese-French bilinguals?\n\nThis question requires us to compare the modelled average for narrative texts written by Portuguese-French bilinguals at T2 to that of the narrative texts written by Portuguese-French bilinguals at T1. The first combination of predictor values can be found in row 10 in `d_pred`, so the corresponding estimates are in *column* 10 in `posterior_fit`. The second combination of predictor values can be found in row 8 in `d_pred`, so the corresponding estimates are in *column* 8 in `posterior_fit`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt2 <- posterior_fit[, 10]\nt1 <- posterior_fit[, 8]\ndf <- data.frame(t2, t1)\n```\n:::\n\n\nNow compute and plot the pairwise differences:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- df |> \n  mutate(progression = t2 - t1)\nggplot(df,\n       aes(x = progression)) +\n  geom_histogram(bins = 50, fill = \"lightgrey\", colour = \"black\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![**Figure 3.** Estimate of the progression in Guiraud values for narrative texts by Portuguese-French bilinguals from T1 to T2.](index_files/figure-html/unnamed-chunk-31-1.svg)\n:::\n:::\n\n\nThe mean progression is easily calculated:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(df$progression)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.147\n```\n\n\n:::\n:::\n\n\nThe estimated error for this estimate is:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd(df$progression)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.148\n```\n\n\n:::\n:::\n\n\nAnd its 95% uncertainty interval is:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(df$progression, probs = c(0.025, 0.975))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  2.5%  97.5% \n-0.144  0.436 \n```\n\n\n:::\n:::\n\n\nAccording to the model, there's about a 84% chance that there's indeed some progression going from T1 to T2.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(df$progression > 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.839\n```\n\n\n:::\n:::\n\n\n#### Question 2: T1-T3 progression for argumentative texts, Portuguese-French vs. Portuguese-German?\n\nThis question requires us to take into consideration the modelled average for argumentative texts written by Portuguese-French bilinguals at T1, that for argumentative texts written by Portuguese-French bilinguals at T3, and the same for the texts written by Portuguese-German bilinguals. We need the following columns in `posterior_fit`:\n\n-   7 (Portuguese-French, T1, argumentative)\n-   11 (Portuguese-French, T3, argumentative)\n-   13 (Portuguese-German, T1, argumentative)\n-   17 (Portuguese-German, T3, argumentative)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfr_t1 <- posterior_fit[, 7]\nfr_t3 <- posterior_fit[, 11]\ngm_t1 <- posterior_fit[, 13]\ngm_t3 <- posterior_fit[, 17]\ndf <- data.frame(fr_t1, fr_t3, gm_t1, gm_t3)\n```\n:::\n\n\nWe compute the progression for the Portuguese-French bilinguals and that for the Portuguese-German bilinguals. Then we compute the difference between these progressions:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- df |> \n  mutate(prog_fr = fr_t3 - fr_t1,\n         prog_gm = gm_t3 - gm_t1,\n         diff_prog = prog_gm - prog_fr)\n```\n:::\n\n\nThe mean progression for the Portuguese-French bilinguals was 0.54 compared to 0.68 for the Portuguese-German bilinguals:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(df$prog_fr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.54\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(df$prog_gm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.687\n```\n\n\n:::\n:::\n\n\nThe mean difference between these progressions, then, is 0.14 in favour of the Portuguese-German bilinguals:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(df$diff_prog)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.146\n```\n\n\n:::\n:::\n\n\nHowever, there is considerable uncertainty about this difference:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(df,\n       aes(x = diff_prog)) +\n  geom_histogram(bins = 50, fill = \"lightgrey\", colour = \"black\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-40-1.svg)\n:::\n:::\n\n\nThe probability that the Portuguese-German bilinguals make more progress than the Portuguese-French bilinguals is 77%, and according to the model, there's a 95% chance its size is somewhere between -0.25 and 0.52 points.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(df$diff_prog > 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.777\n```\n\n\n:::\n\n```{.r .cell-code}\nquantile(df$diff_prog, probs = c(0.025, 0.975))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  2.5%  97.5% \n-0.248  0.532 \n```\n\n\n:::\n:::\n\n\n## Summary\n\nBy investing some time in recoding your predictors, you can make the parameter estimates more relevant to your questions. Any specific comparisons you may be interested in can additionally be addressed by making use of the entire distribution of estimates. You can also use these estimate distributions to draw effect plots.\n\n## Further resources\n\n-   [R Library Contrast Coding Systems for categorical variables](https://stats.idre.ucla.edu/r/library/r-library-contrast-coding-systems-for-categorical-variables/)\n-   Matthew Kay. 2018. [Extracting and visualizing tidy draws from brms models](https://mjskay.github.io/tidybayes/articles/tidy-brms.html)\n-   Daniel J. Schad, Sven Hohenstein, Shravan Vasishth and Reinhold Kliegl. 2018. [How to capitalize on a priori contrasts in linear (mixed) models: A tutorial](https://arxiv.org/abs/1807.10451).\n-   In simpler models, you can use bootstrapping to generate distributions of estimates. This would be possible for these data, too, but it would take a considerable amount of time.\n\n## References\n\nAudrey Bonvin, Jan Vanhove, Raphael Berthele and Amelia Lambelet. 2018. [Die Entwicklung von produktiven lexikalischen Kompetenzen bei Schüler(innen) mit portugiesischem Migrationshintergrund in der Schweiz.](http://tujournals.ulb.tu-darmstadt.de/index.php/zif/article/view/886) *Zeitschrift für Interkulturellen Fremdsprachenunterricht* 23(1). 135-148. Data and R code available from [figshare](http://dx.doi.org/10.6084/m9.figshare.4578991).\n\nAmelia Lambelet, Raphael Berthele, Magalie Desgrippes, Carlos Pestana and Jan Vanhove. 2017a. Chapter 2: Testing interdependence in Portuguese Heritage speakers in Switzerland: the HELASCOT project. In Raphael Berthele and Amelia Lambelet (eds.), [Heritage and school language literacy development in migrant children: Interdependence or independence?](http://www.multilingual-matters.com/display.asp?k=9781783099030), pp. 26-33. Multilingual Matters.\n\nAmelia Lambelet, Magalie Desgrippes and Jan Vanhove. 2017b. Chapter 5: The development of argumentative and narrative writing skills in Portuguese heritage speakers in Switzerland (HELASCOT project). In Raphael Berthele and Amelia Lambelet (eds.), [Heritage and school language literacy development in migrant children: Interdependence or independence?](http://www.multilingual-matters.com/display.asp?k=9781783099030), pp. 83-96. Multilingual Matters.\n\nJan Vanhove, Audrey Bonvin, Amelia Lambelet and Raphael Berthele. 2019. [Predicting perceptions of the lexical richness of short French, German, and Portuguese texts.](https://doi.org/10.17239/jowr-2019.10.03.04) *Journal of Writing Research*. Technical report, data (including texts), elicitation materials, and R code available from the [Open Science Framework](https://osf.io/vw4pc/).\n\n## Session info\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndevtools::session_info()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n─ Session info ───────────────────────────────────────────────────────────────\n setting  value\n version  R version 4.5.1 (2025-06-13)\n os       Ubuntu 22.04.5 LTS\n system   x86_64, linux-gnu\n ui       X11\n language en_US\n collate  en_US.UTF-8\n ctype    en_US.UTF-8\n tz       Europe/Zurich\n date     2025-09-24\n pandoc   2.12 @ /home/jan/miniconda3/bin/ (via rmarkdown)\n\n─ Packages ───────────────────────────────────────────────────────────────────\n package        * version  date (UTC) lib source\n abind            1.4-8    2024-09-12 [1] CRAN (R 4.5.1)\n backports        1.5.0    2024-05-23 [1] CRAN (R 4.5.1)\n bayesplot        1.14.0   2025-08-31 [1] CRAN (R 4.5.1)\n bit              4.6.0    2025-03-06 [1] CRAN (R 4.5.1)\n bit64            4.6.0-1  2025-01-16 [1] CRAN (R 4.5.1)\n bridgesampling   1.1-2    2021-04-16 [1] CRAN (R 4.5.1)\n brms           * 2.23.0   2025-09-09 [1] CRAN (R 4.5.1)\n Brobdingnag      1.2-9    2022-10-19 [1] CRAN (R 4.5.1)\n cachem           1.1.0    2024-05-16 [1] CRAN (R 4.5.1)\n callr            3.7.6    2024-03-25 [1] CRAN (R 4.5.1)\n checkmate        2.3.3    2025-08-18 [1] CRAN (R 4.5.1)\n cli              3.6.5    2025-04-23 [1] CRAN (R 4.5.1)\n coda             0.19-4.1 2024-01-31 [1] CRAN (R 4.5.1)\n codetools        0.2-19   2023-02-01 [4] CRAN (R 4.2.2)\n crayon           1.5.1    2022-03-26 [2] CRAN (R 4.2.0)\n curl             6.4.0    2025-06-22 [1] CRAN (R 4.5.1)\n devtools         2.4.5    2022-10-11 [1] CRAN (R 4.5.1)\n digest           0.6.37   2024-08-19 [1] CRAN (R 4.5.1)\n distributional   0.5.0    2024-09-17 [1] CRAN (R 4.5.1)\n dplyr          * 1.1.4    2023-11-17 [1] CRAN (R 4.5.1)\n ellipsis         0.3.2    2021-04-29 [2] CRAN (R 4.2.0)\n evaluate         1.0.4    2025-06-18 [1] CRAN (R 4.5.1)\n farver           2.1.2    2024-05-13 [1] CRAN (R 4.5.1)\n fastmap          1.2.0    2024-05-15 [1] CRAN (R 4.5.1)\n forcats        * 1.0.0    2023-01-29 [1] CRAN (R 4.5.1)\n fs               1.5.2    2021-12-08 [2] CRAN (R 4.2.0)\n generics         0.1.4    2025-05-09 [1] CRAN (R 4.5.1)\n ggplot2        * 3.5.2    2025-04-09 [1] CRAN (R 4.5.1)\n glue             1.6.2    2022-02-24 [2] CRAN (R 4.2.0)\n gridExtra        2.3      2017-09-09 [1] CRAN (R 4.5.1)\n gtable           0.3.6    2024-10-25 [1] CRAN (R 4.5.1)\n hms              1.1.3    2023-03-21 [1] CRAN (R 4.5.1)\n htmltools        0.5.8.1  2024-04-04 [1] CRAN (R 4.5.1)\n htmlwidgets      1.6.4    2023-12-06 [1] CRAN (R 4.5.1)\n httpuv           1.6.16   2025-04-16 [1] CRAN (R 4.5.1)\n inline           0.3.21   2025-01-09 [1] CRAN (R 4.5.1)\n jsonlite         2.0.0    2025-03-27 [1] CRAN (R 4.5.1)\n knitr            1.50     2025-03-16 [1] CRAN (R 4.5.1)\n labeling         0.4.3    2023-08-29 [1] CRAN (R 4.5.1)\n later            1.4.2    2025-04-08 [1] CRAN (R 4.5.1)\n lattice          0.22-5   2023-10-24 [4] CRAN (R 4.3.1)\n lifecycle        1.0.4    2023-11-07 [1] CRAN (R 4.5.1)\n loo              2.8.0    2024-07-03 [1] CRAN (R 4.5.1)\n lubridate      * 1.9.4    2024-12-08 [1] CRAN (R 4.5.1)\n magrittr         2.0.3    2022-03-30 [1] CRAN (R 4.5.1)\n Matrix           1.7-3    2025-03-11 [4] CRAN (R 4.4.3)\n matrixStats      1.5.0    2025-01-07 [1] CRAN (R 4.5.1)\n memoise          2.0.1    2021-11-26 [2] CRAN (R 4.2.0)\n mime             0.10     2021-02-13 [2] CRAN (R 4.0.2)\n miniUI           0.1.2    2025-04-17 [1] CRAN (R 4.5.1)\n mvtnorm          1.3-3    2025-01-10 [1] CRAN (R 4.5.1)\n nlme             3.1-168  2025-03-31 [4] CRAN (R 4.4.3)\n pillar           1.10.2   2025-04-05 [1] CRAN (R 4.5.1)\n pkgbuild         1.3.1    2021-12-20 [2] CRAN (R 4.2.0)\n pkgconfig        2.0.3    2019-09-22 [2] CRAN (R 4.2.0)\n pkgload          1.4.0    2024-06-28 [1] CRAN (R 4.5.1)\n plyr             1.8.9    2023-10-02 [1] CRAN (R 4.5.1)\n posterior        1.6.1    2025-02-27 [1] CRAN (R 4.5.1)\n prettyunits      1.1.1    2020-01-24 [2] CRAN (R 4.2.0)\n processx         3.8.6    2025-02-21 [1] CRAN (R 4.5.1)\n profvis          0.4.0    2024-09-20 [1] CRAN (R 4.5.1)\n promises         1.3.3    2025-05-29 [1] CRAN (R 4.5.1)\n ps               1.9.1    2025-04-12 [1] CRAN (R 4.5.1)\n purrr          * 1.0.4    2025-02-05 [1] CRAN (R 4.5.1)\n QuickJSR         1.8.1    2025-09-20 [1] CRAN (R 4.5.1)\n R6               2.5.1    2021-08-19 [2] CRAN (R 4.2.0)\n RColorBrewer     1.1-3    2022-04-03 [1] CRAN (R 4.5.1)\n Rcpp           * 1.0.14   2025-01-12 [1] CRAN (R 4.5.1)\n RcppParallel     5.1.11-1 2025-08-27 [1] CRAN (R 4.5.1)\n readr          * 2.1.5    2024-01-10 [1] CRAN (R 4.5.1)\n remotes          2.4.2    2021-11-30 [2] CRAN (R 4.2.0)\n reshape2         1.4.4    2020-04-09 [1] CRAN (R 4.5.1)\n rlang            1.1.6    2025-04-11 [1] CRAN (R 4.5.1)\n rmarkdown        2.29     2024-11-04 [1] CRAN (R 4.5.1)\n rstan            2.32.7   2025-03-10 [1] CRAN (R 4.5.1)\n rstantools       2.5.0    2025-09-01 [1] CRAN (R 4.5.1)\n rstudioapi       0.17.1   2024-10-22 [1] CRAN (R 4.5.1)\n scales           1.4.0    2025-04-24 [1] CRAN (R 4.5.1)\n sessioninfo      1.2.2    2021-12-06 [2] CRAN (R 4.2.0)\n shiny            1.10.0   2024-12-14 [1] CRAN (R 4.5.1)\n StanHeaders      2.32.10  2024-07-15 [1] CRAN (R 4.5.1)\n stringi          1.7.6    2021-11-29 [2] CRAN (R 4.2.0)\n stringr        * 1.5.1    2023-11-14 [1] CRAN (R 4.5.1)\n tensorA          0.36.2.1 2023-12-13 [1] CRAN (R 4.5.1)\n tibble         * 3.3.0    2025-06-08 [1] CRAN (R 4.5.1)\n tidyr          * 1.3.1    2024-01-24 [1] CRAN (R 4.5.1)\n tidyselect       1.2.1    2024-03-11 [1] CRAN (R 4.5.1)\n tidyverse      * 2.0.0    2023-02-22 [1] CRAN (R 4.5.1)\n timechange       0.3.0    2024-01-18 [1] CRAN (R 4.5.1)\n tzdb             0.5.0    2025-03-15 [1] CRAN (R 4.5.1)\n urlchecker       1.0.1    2021-11-30 [1] CRAN (R 4.5.1)\n usethis          3.1.0    2024-11-26 [1] CRAN (R 4.5.1)\n utf8             1.2.2    2021-07-24 [2] CRAN (R 4.2.0)\n V8               6.0.4    2025-06-04 [1] CRAN (R 4.5.1)\n vctrs            0.6.5    2023-12-01 [1] CRAN (R 4.5.1)\n vroom            1.6.5    2023-12-05 [1] CRAN (R 4.5.1)\n withr            3.0.2    2024-10-28 [1] CRAN (R 4.5.1)\n xfun             0.52     2025-04-02 [1] CRAN (R 4.5.1)\n xtable           1.8-4    2019-04-21 [1] CRAN (R 4.5.1)\n yaml             2.3.5    2022-02-21 [2] CRAN (R 4.2.0)\n\n [1] /home/jan/R/x86_64-pc-linux-gnu-library/4.5\n [2] /usr/local/lib/R/site-library\n [3] /usr/lib/R/site-library\n [4] /usr/lib/R/library\n\n──────────────────────────────────────────────────────────────────────────────\n```\n\n\n:::\n:::\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}