<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jan Vanhove">
<meta name="dcterms.date" content="2026-06-03">

<title>When interaction effects are hard to explain, try nested effects – Jan Vanhove</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-ef9afd74c936c907027de2a6fad25a4d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<!-- Google tag (gtag.js) -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-7PMKN7SZET"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-7PMKN7SZET');
</script>
<link href="../../site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="../../site_libs/pagedtable-1.1/js/pagedtable.js"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Jan Vanhove</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../support.html"> 
<span class="menu-text">Methods and stats support</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../courses.html"> 
<span class="menu-text">Courses</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../archive.html"> 
<span class="menu-text">Blog archive</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resources.html"> 
<span class="menu-text">Teaching resources</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../publications.html"> 
<span class="menu-text">Publications</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../archive.xml"> <i class="bi bi-rss" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#example-data" id="toc-example-data" class="nav-link active" data-scroll-target="#example-data">Example data</a></li>
  <li><a href="#interaction-effects" id="toc-interaction-effects" class="nav-link" data-scroll-target="#interaction-effects">Interaction effects</a></li>
  <li><a href="#nested-effects-using-rs-shorthand-notation" id="toc-nested-effects-using-rs-shorthand-notation" class="nav-link" data-scroll-target="#nested-effects-using-rs-shorthand-notation">Nested effects using R’s shorthand notation</a></li>
  <li><a href="#nested-effects-using-a-custom-coding-scheme" id="toc-nested-effects-using-a-custom-coding-scheme" class="nav-link" data-scroll-target="#nested-effects-using-a-custom-coding-scheme">Nested effects using a custom coding scheme</a></li>
  <li><a href="#interaction-effect-or-nested-effects" id="toc-interaction-effect-or-nested-effects" class="nav-link" data-scroll-target="#interaction-effect-or-nested-effects">Interaction effect or nested effects?</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#reference" id="toc-reference" class="nav-link" data-scroll-target="#reference">Reference</a></li>
  <li><a href="#session-info" id="toc-session-info" class="nav-link" data-scroll-target="#session-info">Session info</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">When interaction effects are hard to explain, try nested effects</h1>
  <div class="quarto-categories">
    <div class="quarto-category">contrast coding</div>
    <div class="quarto-category">multiple regression</div>
    <div class="quarto-category">R</div>
    <div class="quarto-category">tutorial</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jan Vanhove </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 3, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>When analysing a factorial experiment, R’s default regression output gives you the main effects and interaction effects. The meaning of the resulting parameter estimates can be tricky to explain, especially that of the interaction effect: in essence, it tells you what the difference between two differences is. Nested effects, which immediately tell you what the differences themselves are, are often easier to interpret. This post shows how you can obtain such nested effects in R.</p>
<section id="example-data" class="level2">
<h2 class="anchored" data-anchor-id="example-data">Example data</h2>
<p><a href="#fig-example-data" class="quarto-xref">Figure&nbsp;1</a> shows <a href="berthele2012.csv">data</a> from an experiment with a two-by-two design carried out by Berthele (2012). French-speaking students at a university for teacher education were played a recording of what they thought was a first-language German boy speaking French. About half of the students were told that the boy had a typical Swiss-German name (e.g., Luca); the others were told that he had a name associated with the Balkan region (e.g., Dragan). Furthermore, about half of the recordings contained code-switches (i.e., the boy would occasionally use German expressions when speaking French); the other half of the recordings did not contain any such code-switches. The future teachers were asked to rate the boy’s academic potential on a scale from 1 to 6, with 6 being the highest.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_bw</span>())</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"berthele2012.csv"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(d, </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> CS, <span class="at">y =</span> Potential)) <span class="sc">+</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">shape =</span> <span class="dv">1</span>, <span class="at">position =</span> <span class="fu">position_jitter</span>(<span class="at">width =</span> <span class="fl">0.2</span>, <span class="at">height =</span> <span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> d <span class="sc">|&gt;</span> </span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>               <span class="fu">group_by</span>(CS, Name) <span class="sc">|&gt;</span> </span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>               <span class="fu">summarise</span>(<span class="at">Potential =</span> <span class="fu">mean</span>(Potential), <span class="at">.groups =</span> <span class="st">"drop"</span>),</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">shape =</span> <span class="dv">8</span>, <span class="at">size =</span> <span class="dv">5</span>, <span class="at">colour =</span> <span class="st">"darkred"</span>) <span class="sc">+</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="at">cols =</span> <span class="fu">vars</span>(Name)) <span class="sc">+</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Code-switching?"</span>) <span class="sc">+</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Rated academic potential"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-example-data" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-example-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-example-data-1.svg" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-example-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Data from Berthele’s (2012) experiment. Each circle shows a rating given by a teacher trainee. The red stars highlight the cell means.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="interaction-effects" class="level2">
<h2 class="anchored" data-anchor-id="interaction-effects">Interaction effects</h2>
<p><a href="#fig-example-data" class="quarto-xref">Figure&nbsp;1</a> suggests that there is some <strong>interaction</strong> going on in the data: ‘Dragan’s’ ratings tend to be higher than ‘Luca’s’ when there is no code-switching, but lower where there is code-switching. It’s pretty easy to model this interaction in R:<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>mod.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Potential <span class="sc">~</span> Name<span class="sc">*</span>CS, <span class="at">data =</span> d)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod.lm)<span class="sc">$</span>coefficients</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                     Estimate Std. Error   t value     Pr(&gt;|t|)
(Intercept)         2.9642857  0.1581785 18.740129 3.056638e-41
NameLuca            0.3993506  0.2023426  1.973636 5.024817e-02
CSwithout           0.6631653  0.1968684  3.368572 9.589511e-04
NameLuca:CSwithout -0.9330516  0.2767167 -3.371866 9.483562e-04</code></pre>
</div>
</div>
<p>You need a bit of practice to wrap your head around what these parameter estimates actually refer to, however. The parameter estimate for <code>NameLuca</code> (<span class="math inline">\(0.40 \pm 0.20\)</span>), for instance, tells you that the ratings for ‘Luca’ tend to be <span class="math inline">\(0.40\)</span> points higher than those for ‘Dragan’ <em>if the recording contains code-switches</em>. Next, the parameter estimate of <code>CSwithout</code> (<span class="math inline">\(0.66 \pm 0.20\)</span>), tells you that the ratings for recordings without code-switches tend to be <span class="math inline">\(0.66\)</span> points higher than those with code-switches <em>if the students were told that the boy is called Dragan</em>. The estimate of the interaction parameter <code>NameLuca:CSwithout</code> (<span class="math inline">\(-0.93 \pm 0.28\)</span>) tells you that the absence of code-switches was <span class="math inline">\(0.93\)</span> points more detrimental for ‘Luca’ than it was for ‘Dragan’. <em>Equivalently</em>, it tells you that the <em>presence</em> of code-switches was <span class="math inline">\(0.93\)</span> points more detrimental for ‘Dragan’ than it was for ‘Luca’. <em>Also equivalently</em>, it tells you that labelling the recording ‘Dragan’ instead of ‘Luca’ is <span class="math inline">\(0.93\)</span> points more detrimental on average for recordings with code-switches than for recordings without code-switches.</p>
<p>If you skipped the previous paragraph: I understand. Even for a fairly simple two-by-two design, figuring out the precise meaning of the estimated parameters requires sitting down with a pencil and a piece of paper; see Chapter 10 in my <a href="https://github.com/janhove/AnalysingQuantitativeData">statistics booklet</a>. Thankfully, however, you can usually make the output of statistical models such as the one above more readily interpretable both to yourself and to your audience by changing the coding scheme. I’ve explained how this can be done in a <a href="../2020-05-05-contrast-coding">previous blog post</a>.</p>
</section>
<section id="nested-effects-using-rs-shorthand-notation" class="level2">
<h2 class="anchored" data-anchor-id="nested-effects-using-rs-shorthand-notation">Nested effects using R’s shorthand notation</h2>
<p>Whereas an interaction effect tells you <em>how much stronger</em> an effect of one factor (e.g., code-switching) is for one level of another factor (e.g., if the name is Luca) than for the other level (e.g., if the name is Dragan), <strong>nested effects</strong> tell you quite simply <em>what</em> the effect of one factor is for each level of another factor. To fit nested effects in R, you can use the slash notation:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>mod.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Potential <span class="sc">~</span> Name<span class="sc">/</span>CS, <span class="at">data =</span> d)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod.lm)<span class="sc">$</span>coefficients</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                       Estimate Std. Error   t value     Pr(&gt;|t|)
(Intercept)           2.9642857  0.1581785 18.740129 3.056638e-41
NameLuca              0.3993506  0.2023426  1.973636 5.024817e-02
NameDragan:CSwithout  0.6631653  0.1968684  3.368572 9.589511e-04
NameLuca:CSwithout   -0.2698864  0.1944608 -1.387871 1.672209e-01</code></pre>
</div>
</div>
<p>As before, the estimated intercept (<span class="math inline">\(2.96 \pm 0.16\)</span>) shows the average rating given to Dragan recordings with code-switches, and the <code>NameLuca</code> estimate (<span class="math inline">\(0.40 \pm 0.20\)</span>) shows that the Luca recordings with code-switches were rated a bit better on average than these. Again like before, the <code>NameDragan:CSwithout</code> (<span class="math inline">\(0.66 \pm 0.20\)</span>) shows the effect of the absence of code-switches on the ratings given to Dragan. What’s different from before is the <code>NameLuca:CSwithout</code> estimate (<span class="math inline">\(-0.27 \pm 0.19\)</span>): it shows that, for ‘Luca’, recordings without code-switches tended to be rated <span class="math inline">\(0.27\)</span> worse than recordings with code-switches.</p>
<p>The next snippet shows an alternative coding scheme that suppresses the intercept using the <code>0</code> notation:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>mod.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Potential <span class="sc">~</span> <span class="dv">0</span> <span class="sc">+</span> Name<span class="sc">/</span>CS, <span class="at">data =</span> d)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod.lm)<span class="sc">$</span>coefficients</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                       Estimate Std. Error   t value     Pr(&gt;|t|)
NameDragan            2.9642857  0.1581785 18.740129 3.056638e-41
NameLuca              3.3636364  0.1261828 26.656854 5.631382e-59
NameDragan:CSwithout  0.6631653  0.1968684  3.368572 9.589511e-04
NameLuca:CSwithout   -0.2698864  0.1944608 -1.387871 1.672209e-01</code></pre>
</div>
</div>
<p>This makes it clearer that the previous intercept estimate refers to the Dragan recordings exclusively. The parameter estimate for <code>NameLuca</code> (<span class="math inline">\(3.36 \pm 0.13\)</span>) now shows the average rating for a Luca recording with code-switches rather than a difference between two averages. The remaining estimates refers to the same nested effects as before.</p>
<p>Of course, we can switch the order in which the factors appear. In doing so, we obtain the average ratings for the Dragan recordings with and without code-switches as well as the effects of labelling the recordings ‘Luca’ rather than ‘Dragan’ for both recordings with and without code-switches:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>mod.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Potential <span class="sc">~</span> <span class="dv">0</span> <span class="sc">+</span> CS<span class="sc">/</span>Name, <span class="at">data =</span> d)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod.lm)<span class="sc">$</span>coefficients</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                     Estimate Std. Error   t value     Pr(&gt;|t|)
CSwith              2.9642857  0.1581785 18.740129 3.056638e-41
CSwithout           3.6274510  0.1172037 30.949964 2.927176e-67
CSwith:NameLuca     0.3993506  0.2023426  1.973636 5.024817e-02
CSwithout:NameLuca -0.5337010  0.1887580 -2.827434 5.328876e-03</code></pre>
</div>
</div>
</section>
<section id="nested-effects-using-a-custom-coding-scheme" class="level2">
<h2 class="anchored" data-anchor-id="nested-effects-using-a-custom-coding-scheme">Nested effects using a custom coding scheme</h2>
<p>One of the representations above is sufficient for our purposes. If you want even more control over what the estimates refer to, I recommend you use a custom coding scheme. In this example, it’s a bit unfortunate that the <code>with</code> code-switching condition gets absorbed in the intercept but the <code>without</code> condition doesn’t. By using a custom coding scheme, we can have the estimated parameters mean exactly what we want them to mean.</p>
<p>First, we explicitly label each cell of the design and convert these labels to a factor:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>Cell <span class="ot">&lt;-</span> <span class="fu">paste0</span>(d<span class="sc">$</span>Name, <span class="st">"-"</span>, d<span class="sc">$</span>CS) <span class="sc">|&gt;</span> </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.factor</span>()</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(d<span class="sc">$</span>Cell)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
   Dragan-with Dragan-without      Luca-with   Luca-without 
            28             51             44             32 </code></pre>
</div>
</div>
<p>Next, we write down what we want the intercept to represent. I think that a sensible choice is to have the intercept represent the mean of the two cells in which no code-switching occurred, i.e., <code>Dragan-without</code> and <code>Luca-without</code>.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> We write this down in the form of a null hypothesis, even if we don’t really want to test this null hypothesis:</p>
<p><span class="math display">\[\frac{1}{2}\left(\mu_{\textrm{Luca, no CS}} + \mu_{\textrm{Dragan, no CS}}\right) = 0.\]</span></p>
<p>We then rewrite this null hypothesis so that all four cells are represented on the left-hand side of the equation. In doing so, make sure that the cells occur in the same order in which they appear above, i.e., first Dragan with code-switches, then Dragan without, then Luca with, and finally Luca-without. (If you find this confusing, either bear with me or read the longer blog post on <a href="../2020-05-05-contrast-coding">contrast coding</a>.)</p>
<p><span class="math display">\[\frac{1}{2}\left(\mu_{\textrm{Luca, no CS}} + \mu_{\textrm{Dragan, no CS}}\right) = 0
\Leftrightarrow
0\mu_{\textrm{Dragan, with CS}}
+ \frac{1}{2}\mu_{\textrm{Dragan, no CS}}
+ 0\mu_{\textrm{Luca, with CS}}
+ \frac{1}{2}\mu_{\textrm{Luca, no CS}} = 0.\]</span></p>
<p>We put the coefficients so obtained (i.e., 0, 1/2, 0 and 1/2) into a vector. The vector’s name makes it clear that its purpose is to estimate the mean of the averages of the cells in which no code-switching occurred; the vector entries are named for clarity’s sake (e.g., <code>Ln</code> means Luca, no code-switches).</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>Mean_NoCS <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">Dw =</span> <span class="dv">0</span>, <span class="at">Dn =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>, <span class="at">Lw =</span> <span class="dv">0</span>, <span class="at">Ln =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>We now write down what we want the next parameter estimate to refer to. I want it to represent the difference between Dragan’s code-switch-free ratings and Luca’s code-switch-free ratings. We can write this down as a null hypothesis like so:</p>
<p><span class="math display">\[\left(\mu_{\textrm{Dragan, no CS}} = \mu_{\textrm{Luca, no CS}}\right)
\Leftrightarrow
0\mu_{\textrm{Dragan, with CS}}
+ 1\mu_{\textrm{Dragan, no CS}}
+ 0\mu_{\textrm{Luca, with CS}}
- 1\mu_{\textrm{Luca, no CS}} = 0.\]</span></p>
<p>Again, we put the resulting coefficients in a vector.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>NoCS_DraganvLuca <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">Dw =</span> <span class="dv">0</span>, <span class="at">Dn =</span> <span class="dv">1</span>, <span class="at">Lw =</span> <span class="dv">0</span>, <span class="at">Ln =</span> <span class="sc">-</span><span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>I want the third parameter estimate to show the (nested) code-switching effect for Luca:</p>
<p><span class="math display">\[\left(\mu_{\textrm{Luca, with CS}} = \mu_{\textrm{Luca, no CS}}\right)
\Leftrightarrow
0\mu_{\textrm{Dragan, with CS}}
+ 0\mu_{\textrm{Dragan, no CS}}
+ 1\mu_{\textrm{Luca, with CS}}
- 1\mu_{\textrm{Luca, no CS}} = 0.\]</span></p>
<p>Let’s put this into a vector, too:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>Luca_CS <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">Dw =</span> <span class="dv">0</span>, <span class="at">Dn =</span> <span class="dv">0</span>, <span class="at">Lw =</span> <span class="dv">1</span>, <span class="at">Ln =</span> <span class="sc">-</span><span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>The fourth and final parameter estimate should show the (nested) code-switching effect for Dragan: <span class="math display">\[\left(\mu_{\textrm{Dragan, with CS}} = \mu_{\textrm{Dragan, no CS}}\right)
\Leftrightarrow
1\mu_{\textrm{Dragan, with CS}}
- 1\mu_{\textrm{Dragan, no CS}}
+ 0\mu_{\textrm{Luca, with CS}}
+ 0\mu_{\textrm{Luca, no CS}} = 0.\]</span></p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>Dragan_CS <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">Dw =</span> <span class="dv">1</span>, <span class="at">Dn =</span> <span class="sc">-</span><span class="dv">1</span>, <span class="at">Lw =</span> <span class="dv">0</span>, <span class="at">Ln =</span> <span class="dv">0</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Now we collect the four vectors into a hypothesis matrix <code>Hm</code>:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>Hm <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  Mean_NoCS,</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  NoCS_DraganvLuca,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  Luca_CS,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  Dragan_CS </span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Using the <code>apply_contrasts()</code> function defined in the next snippet, the hypothesis matrix can be converted into a set of contrasts that can be applied to the <code>Cell</code> factor:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>apply_contrasts <span class="ot">&lt;-</span> <span class="cf">function</span>(Hm) {</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    MASS<span class="sc">::</span><span class="fu">fractions</span>(<span class="fu">provideDimnames</span>(MASS<span class="sc">::</span><span class="fu">ginv</span>(Hm), <span class="at">base =</span> <span class="fu">dimnames</span>(Hm)[<span class="dv">2</span><span class="sc">:</span><span class="dv">1</span>]))[, <span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(d<span class="sc">$</span>Cell) <span class="ot">&lt;-</span> <span class="fu">apply_contrasts</span>(Hm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Now fit the model using the <code>Cell</code> factor with the custom coding scheme as a predictor:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>mod.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Potential <span class="sc">~</span> Cell, d)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod.lm)<span class="sc">$</span>coefficients</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                       Estimate Std. Error   t value     Pr(&gt;|t|)
(Intercept)           3.3606005 0.09437902 35.607495 2.378887e-75
CellNoCS_DraganvLuca  0.5337010 0.18875804  2.827434 5.328876e-03
CellLuca_CS           0.2698864 0.19446075  1.387871 1.672209e-01
CellDragan_CS        -0.6631653 0.19686836 -3.368572 9.589511e-04</code></pre>
</div>
</div>
<p>As you can verify, each parameter estimate refers exactly to what we wanted it to refer to.</p>
</section>
<section id="interaction-effect-or-nested-effects" class="level2">
<h2 class="anchored" data-anchor-id="interaction-effect-or-nested-effects">Interaction effect or nested effects?</h2>
<p>In the example above, the nested effects tell you what the effect of code-switching is for Luca recordings and for Dragan recordings, whereas the interaction effect tells you by how much these differ. I find the nested effects easier to interpret. But if you’re interested in the <em>difference</em> between these nested effects (and this is often the case!), you also need the interaction effect. What you could do in this case is have your cake and eat it, too: report the easy-to-interpret nested effects in a table, and report the interaction effect in the text if it’s also relevant. Perhaps something along the lines of</p>
<blockquote class="blockquote">
<p>“Luca recordings with code-switches received ratings that were <span class="math inline">\(0.27 \pm 0.19\)</span> points higher on average than did Luca recordings without code-switches. The opposite was true for ‘Dragan’: if he code-switched, the ratings were <span class="math inline">\(0.66 \pm 0.20\)</span> lower than when he did not. The difference between these code-switching effects is statistically significant (<span class="math inline">\(0.93 \pm 0.28\)</span>, <span class="math inline">\(t(151) = 3.4, p = 0.0009\)</span>).</p>
</blockquote>
<p>The interaction estimate and standard error as well as the significance test can be gleaned from the output of the model at the top of this page.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>In sum, if you’re analysing a study with a factorial design and you find that you’re tripping yourself up when explaining the literal meaning of the parameter estimates, consider using a nested-effects parametrisation instead of an interaction-effect parametrisation. If you want full control, use a custom-coding scheme.</p>
</section>
<section id="reference" class="level2">
<h2 class="anchored" data-anchor-id="reference">Reference</h2>
<p>Berthele, Raphael. 2012. <a href="https://doi.org/10.1177/1367006911429514">The influence of code-mixing and speaker information on perception and assessment of foreign language proficiency: An experimental study</a>. <em>International Journal of Bilingualism</em> 16(4). 453–466.</p>
</section>
<section id="session-info" class="level2">
<h2 class="anchored" data-anchor-id="session-info">Session info</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>devtools<span class="sc">::</span><span class="fu">session_info</span>(<span class="st">"attached"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in system2("quarto", "-V", stdout = TRUE, env = paste0("TMPDIR=", :
running command '"quarto"
TMPDIR=C:/Users/VanhoveJ/AppData/Local/Temp/RtmpqGZ5bQ/file19a412c1715d -V' had
status 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>─ Session info ───────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.5.0 (2025-04-11 ucrt)
 os       Windows 11 x64 (build 26200)
 system   x86_64, mingw32
 ui       RTerm
 language (EN)
 collate  English_United Kingdom.utf8
 ctype    English_United Kingdom.utf8
 tz       Europe/Zurich
 date     2026-06-03
 pandoc   3.1.1 @ C:/Program Files/RStudio/resources/app/bin/quarto/bin/tools/ (via rmarkdown)
 quarto   NA @ C:\\Users\\VanhoveJ\\AppData\\Local\\Programs\\Quarto\\bin\\quarto.exe

─ Packages ───────────────────────────────────────────────────────────────────
 package   * version date (UTC) lib source
 dplyr     * 1.2.1   2026-04-03 [1] CRAN (R 4.5.3)
 forcats   * 1.0.1   2025-09-25 [1] CRAN (R 4.5.3)
 ggplot2   * 4.0.3   2026-04-22 [1] CRAN (R 4.5.3)
 lubridate * 1.9.5   2026-02-04 [1] CRAN (R 4.5.3)
 purrr     * 1.0.4   2025-02-05 [1] CRAN (R 4.5.0)
 readr     * 2.2.0   2026-02-19 [1] CRAN (R 4.5.3)
 stringr   * 1.6.0   2025-11-04 [1] CRAN (R 4.5.3)
 tibble    * 3.2.1   2023-03-20 [1] CRAN (R 4.5.0)
 tidyr     * 1.3.2   2025-12-19 [1] CRAN (R 4.5.3)
 tidyverse * 2.0.0   2023-02-22 [1] CRAN (R 4.5.3)

 [1] C:/Users/VanhoveJ/AppData/Local/R/win-library/4.5
 [2] C:/Program Files/R/R-4.5.0/library
 * ── Packages attached to the search path.

──────────────────────────────────────────────────────────────────────────────</code></pre>
</div>
</div>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Here I’m ignoring the rather coarse nature of the data. If you want to go the whole hog, you can use bootstrapping to verify the standard errors, but this would detract from the blog post’s goal.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Other choices are defensible, too. In fact, if this technique is new to you, I suggest you try to adapt the code snippets so that the intercept represents the grand mean (the average of all cell averages) or just Luca’s code-switch-free recordings.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/janhove\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>