{
  "hash": "8d5ff8f0e0b9f63b79944107e580991b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Confidence intervals for standardised mean differences\"\ndate: \"2017-02-22\"\ncategories: [R, effect sizes]\nexecute:\n  cache: true\n---\n\n\n::: {.cell}\n\n:::\n\n\nStandardised effect sizes express patterns found in the data in \nterms of the variability found in the data. For instance, a mean difference\nin body height could be expressed in the metric in which the data were\nmeasured (e.g., a difference of 4 centimetres) or relative to the \nvariation in the data (e.g., a difference of 0.9 standard deviations).\nThe latter is a standardised effect size known as Cohen's _d_.\n\nAs I've \n[written](../2015-02-05-standardised-vs-unstandardised-es) \n[before](../2015-03-16-standardised-es-revisited), \nI don't particularly like standardised effect sizes.\nNonetheless, I wondered how confidence intervals around standardised\neffect sizes (more specifically: standardised mean differences) \nare constructed. Until recently, I hadn't really thought about it\nand sort of assumed you would compute them the same way as \nconfidence intervals around\nraw effect sizes. But unlike raw (unstandardised) mean differences,\nstandardised mean differences are a combination of _two_ estimates \nsubject to sampling error: the mean difference itself \nand the sample standard deviation. \nMoreover, the sample standard deviation is a biased estimate of \nthe population standard deviation (it tends to be \n[too low](https://en.wikipedia.org/wiki/Unbiased_estimation_of_standard_deviation#Background)),\nwhich causes Cohen's _d_ to be an upwardly biased estimate of the \npopulation standardised mean difference.\nSurely both of these factors must affect how \nthe confidence intervals around standardised effect sizes are constructed?\n\nIt turns out that indeed they do. When I compared the confidence\nintervals that I computed around a standardised effect size\nusing a naive approach that assumed that the standard deviation\nwasn't subject to sampling error and wasn't biased, I got different \nresults than when I used specialised R functions.\n\nBut these R functions all produced different results, too.\n\nObviously, there may well be more than one way to skin a cat, but this\ncaused me to wonder if the different procedures for computing confidence\nintervals all covered the true population parameter with the nominal\nprobability (e.g., in 95% of cases for a 95% confidence interval).\nI ran a simulation to find out, which I'll report in the remainder of this post.\n**If you spot any mistakes, please let me know.**\n\n## Introducing the contenders\n\nBelow, I'm going to introduce three R functions for computing\nconfidence intervals for standardised effect sizes (standardised mean\ndifferences, to be specific). To illustrate how they work, though,\nI'm first going to generate a two samples\nfrom normal distributions with standard deviations of 1 and\nmeans of 0.5 and 0, respectively.\n\n**Update (2023-08-07):** I reran all of the code in this blog post\nwith newer software versions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Set random seed for reproducible results\n# (today's date)\nRNGversion(\"3.5.3\")\nset.seed(2017-02-21)\n\n# Population standardised mean difference\nd <- 0.5\n# Number of observations per sample\nn <- 20\n\n# Generate data\ny <- c(rnorm(n, d, sd = 1), \n       rnorm(n, 0, sd = 1))\nx <- factor(c(rep(\"A\", n),\n              rep(\"B\", n)))\n```\n:::\n\n\n### `cohen.d` in the `effsize` package\n\nThe first function is `cohen.d` from the `effsize` package.\nIt takes as its arguments the two samples you want to compare and\nthe desired confidence level (here: 90%). You can also specify\nwhether you want to apply `hedges.correction`, \nwhich causes the function to compute\n[Hegdes' _g_](https://en.wikipedia.org/wiki/Effect_size#Hedges.27_g)\nand confidence intervals for it.\n(Hedges' _g_ is less biased than Cohen's _d_.)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(effsize)\ncohen.d(y, x, conf.level = 0.9, hedges.correction = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCohen's d\n\nd estimate: 0.811 (large)\n90 percent confidence interval:\nlower upper \n0.257 1.366 \n```\n\n\n:::\n:::\n\n\n90% confidence interval for Cohen's _d_: [0.25, 1.37].\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncohen.d(y, x, conf.level = 0.9, hedges.correction = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nHedges's g\n\ng estimate: 0.795 (medium)\n90 percent confidence interval:\nlower upper \n0.252 1.338 \n```\n\n\n:::\n:::\n\n\n90% confidence interval for Hedges' _g_: [0.25, 1.34].\n\n(Incidentally, `cohen.d` also has a parameter called `noncentral`, \nbut setting it to `TRUE` doesn't seem to work... (**Update (2023-08-07):** It does now.))\n\n### `tes` in the `compute.es` package\n\nThe second function is `tes` from the `compute.es` package.\nIt takes as its arguments the _t_ statistic for the _t_ test comparing the two samples,\nthe sample sizes and the desired confidence level (as a percentage, not as a proportion):\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compute t-statistic\nt.stat <- t.test(y ~ x, var.equal = TRUE)$statistic\n\n# Compute effect sizes and confidence intervals\nlibrary(compute.es)\ntes(t.stat, n.1 = 20, n.2 = 20, level = 90)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean Differences ES: \n \n d [ 90 %CI] = 0.81 [ 0.27 , 1.35 ] \n  var(d) = 0.11 \n  p-value(d) = 0.02 \n  U3(d) = 79.1 % \n  CLES(d) = 71.7 % \n  Cliff's Delta = 0.43 \n \n g [ 90 %CI] = 0.8 [ 0.26 , 1.33 ] \n  var(g) = 0.1 \n  p-value(g) = 0.02 \n  U3(g) = 78.7 % \n  CLES(g) = 71.3 % \n \n Correlation ES: \n \n r [ 90 %CI] = 0.38 [ 0.13 , 0.59 ] \n  var(r) = 0.02 \n  p-value(r) = 0.02 \n \n z [ 90 %CI] = 0.41 [ 0.13 , 0.68 ] \n  var(z) = 0.03 \n  p-value(z) = 0.02 \n \n Odds Ratio ES: \n \n OR [ 90 %CI] = 4.36 [ 1.63 , 11.6 ] \n  p-value(OR) = 0.02 \n \n Log OR [ 90 %CI] = 1.47 [ 0.49 , 2.45 ] \n  var(lOR) = 0.36 \n  p-value(Log OR) = 0.02 \n \n Other: \n \n NNT = 3.47 \n Total N = 40\n```\n\n\n:::\n:::\n\n\n\nThis function outputs a lot of standardised effect sizes and their confidence intervals.\nHere, I'm only interested in Cohen's _d_, whose 90% confidence interval now is [0.27, 1.35]. \n(The confidence interval for Hedges' _g_ is also different from that from the `cohen.d` function.)\n\nNote, incidentally, that the Cohen's _d_ and Hedges' _g_ values are the same for the \n`tes` and the `cohen.d` function; \nit's just the confidence intervals that are different.\n\n### `ci.smd` in the `MBESS` package\n\nLastly, the `ci.smd` function from the `MBESS` package takes\nas its input a Cohen's _d_, the two sample sizes, and the desired confidence level.\nHere I compute Cohen's _d_ using the `cohen.d` function and then feed it to `ci.smd`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compute Cohen's d\nd.stat <- cohen.d(y, x, conf.level = 0.9, hedges.correction = FALSE)$estimate\n\n# Compute confidence intervals\nlibrary(MBESS)\nci.smd(smd = d.stat, n.1 = 20, n.2 = 20, conf.level = 0.9)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Lower.Conf.Limit.smd\n[1] 0.264\n\n$smd\n[1] 0.811\n\n$Upper.Conf.Limit.smd\n[1] 1.35\n```\n\n\n:::\n:::\n\n\nThis time, the 90% confidence interval is [0.26, 1.35]. \nIt was fairly small differences between the three functions \nsuch as these that led me to run the simulation I report below.\n\n## Coverage of the population standardised mean difference by different confidence intervals\n\n### Method\nFor the simulation I generated lots of samples from two normal distributions\nwith the same standard deviation whose means where half a standard deviation apart.\nIn other words, the population standardised mean difference was 0.5.\nFor each sample, I computed 90% confidence intervals around the sample standardised\nmean difference (Cohen's d) using the `cohen.d`, `tes` and `ci.smd` functions;\nI also computed 90% confidence intervals around Hedges' _g_ using the `cohen.d` function.\nI then checked how often these intervals contained the population mean standardised \ndifference (0.5). Ideally, this should be the case in about 90% of the samples generated.\nIf it's fewer than that, the confidence intervals are too narrow;\nif it's more than that, they're too wide.\nI ran this simulation for different sample sizes, ranging from 5 observations per\ngroup to 500 per group.\n\nThe R code for this simulation is available at the bottom of this post.\n\n### Results\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Figure 1. Coverage of the population standardised mean difference (0.5) by confidence intervals computed using the `cohen.d`, `tes` and `ci.smd` functions based on 10,000 simulation runs per sample size. The dashed horizontal line shows the nominal confidence level; the grey lines around it show the values between which the coverage rates should lie with 95% probability if the confidence interval had their nominal coverage rate.](index_files/figure-html/unnamed-chunk-7-1.svg)\n:::\n:::\n\n\nAs Figure 1 clearly shows, the coverage rates for the confidence intervals computed around\nCohen's _d_ using the `ci.smd` function are at their nominal level even for small samples.\nThe confidence intervals computed using the `cohen.d` and `tes` functions, however, are too wide\nfor sample sizes of up to 50 observations per group.\n\n## Conclusions and further reading\nFirst of all, I want to reiterate that I think standardised effect sizes,\nincluding standardised mean differences and correlation coefficients,\nare overvalued and that I think we should strive to interpret \nraw effect sizes instead.\n\nThat said, on a practical level, this simulation suggests that \nif you nonetheless want to express your results as a standardised\nmean difference and you want to compute a confidence around it, \nit's a good idea to take a look at the `MBESS` package.\nThe package's [vignette](http://www.jstatsoft.org/v20/i08/paper) also has \na good discussion of how exact confidence intervals can be constructed around standardised effect sizes,\nand the package provides a fast implementation of these methods.\n\nBy contrast, the `effsize` and `compute.es` packages seem to rely on overly\nconservative approximations to these exact methods, and differ between\neach other in how the variance for Cohen's _d_ is computed (see [here](https://cran.r-project.org/web/packages/compute.es/compute.es.pdf#page=81)\nand [here](https://cran.r-project.org/web/packages/effsize/effsize.pdf#6)).\n\nFor those of you interested in further details, Wolfgang Viechtbauer provided\n[some](https://twitter.com/wviechtb/status/834009942323519489) \n[links](https://twitter.com/wviechtb/status/834047963307634688) on Twitter that you may want to take a look at.\n\n\n## R code\n\nFor those interested, here's the R code I used for the simulation.\nIf you spot an error that explains the results above, please let me know.\n\nFirst, I defined a function, `d_ci`, that generates two samples from normal distributions\nwith standard deviations of 1. In the simulation, the mean difference between these populations\nis 0.5, which, since both population have standard deviations of 1, means that the\ntrue standardised mean difference is 0.5.\nThen, four confidence intervals are computed around the sample Cohen's _d_:\n\n1. Using `cohen.d` with Hedges' correction.  \n2. Using `tes`. (I only used the code relevant to Cohen's _d_ to speed things up.)\n3. Using `ci.smd`.\n4. Using `cohen.d` without Hedges' correction.\n\n`d_ci` simply returns, for each of these four intervals, whether they contain the true\npopulation standardised mean difference (i.e., 0.5).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd_ci <- function(d = 0.5, n = 20, ci = 0.80) {\n  # Two samples with specified d\n  y <- c(rnorm(n, d, sd = 1), \n         rnorm(n, 0, sd = 1))\n  x <- factor(c(rep(\"A\", n),\n                rep(\"B\", n)))\n\n  # Run t-test\n  ttest <- t.test(y ~ x, var.equal = TRUE, conf.level = ci)\n\n  # Effect size using effsize package ----------------------\n  # with Hedges' correction\n  es <- effsize::cohen.d(y, x, conf.level = ci, \n                         hedges.correction = TRUE)\n  d.lo1 <- es$conf.int[1]\n  d.hi1 <- es$conf.int[2]\n\n  # Effect size using compute.es ---------------------------\n  # This is a selection from the source code for compute.es::tes.\n  df <- 2 * n - 2\n  d.est2 <- ttest$statistic * sqrt((2 * n)/(n * n))\n  var.d <- (2 * n)/(n * n) + (d.est2^2) / (2 * (2 * n))\n  crit <- qt((1 - ci)/2, df, lower.tail = FALSE)\n  d.lo2 <- d.est2 - crit * sqrt(var.d)\n  d.hi2 <- d.est2 + crit * sqrt(var.d)\n  \n  # MBESS package ---------------------------------------\n  # (d.est2 computed above for compute.es)\n  mbess_out <- MBESS::ci.smd(smd = d.est2, n.1 = n, n.2 = n, conf.level = ci)\n  d.lo3 <- mbess_out$Lower.Conf.Limit.smd\n  d.hi3 <- mbess_out$Upper.Conf.Limit.smd\n  \n  # Effect size using effsize package \n  # no hedges corrections ----------------------\n  es4 <- effsize::cohen.d(y, x, conf.level = ci, \n                         hedges.correction = FALSE)\n  d.lo4 <- es4$conf.int[1]\n  d.hi4 <- es4$conf.int[2]\n  \n  # In CI? ----------------------------------------------------\n  d.in.ci1 <- (d < d.hi1 && d > d.lo1)      # effsize::cohen.d\n  d.in.ci2 <- (d < d.hi2 && d > d.lo2)      # compute.es::tes\n  d.in.ci3 <- (d < d.hi3 && d > d.lo3)      # MBESS::ci.smd\n  d.in.ci4 <- (d < d.hi4 && d > d.lo4)      # MBESS::ci.smd\n  \n  # Return -------------------------------------------- \n  return(list(d.in.ci1, d.in.ci2, d.in.ci3, d.in.ci4))\n}\n```\n:::\n\n\nThen I wrote a function, `sim_es`, which runs `d_ci` a set number of times\nand return the proportion of times the four confidence intervals\ncontained the true population _d_.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Run d_ci a couple of times and store the coverage rates\nsim_es <- function(runs = 1e1, n = 10, d = 0.5, ci = 0.8) {\n  reps <- replicate(runs, d_ci(n = n, d = d, ci = ci))\n  return(list(mean(unlist(reps[1, ])),\n              mean(unlist(reps[2, ])),\n              mean(unlist(reps[3, ])),\n              mean(unlist(reps[4, ]))))\n}\n```\n:::\n\n\nNext I ran `sim_es` 10,000 times for 9 different samples, from\n5 observations per sample to 500.\nThe desired confidence level was 90%.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Define the sample sizes\nsampleSizes <- c(5, 10, 20, 30, 40, 50,\n                 100, 200, 500)\n\n# Define the confidence level and the number of runs\nci <- 0.90\nruns <- 10000\n\n# Evaluate sim_es for different sampleSizes\n# but with runs and ci set to the same value each time.\n# You can use mapply instead of mcmapply.\n# Remove the last line (with mc.cores) in that case.\nlibrary(parallel)\nresults <- mcmapply(sim_es,\n                    n = sampleSizes,\n                    MoreArgs = list(runs = runs, ci = ci),\n                    mc.cores = detectCores())\n```\n:::\n\n\nFinally, I stored the results to a dataframe and plotted them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Store results in dataframe\nd_results <- data.frame(sampleSizes)\nd_results$`cohen.d (correction) in\\neffsize package` <- unlist(results[1, ])\nd_results$`tes in\\ncompute.es package` <- unlist(results[2, ])\nd_results$`ci.smd in\\nMBESS package` <- unlist(results[3, ])\nd_results$`cohen.d (no correction) in\\neffsize package` <- unlist(results[4, ])\n\n# Load packages for plotting\nlibrary(tidyverse)\n\n# Plot\nggplot(d_results |> \n         gather(\"Method\", \"Coverage\", -sampleSizes),\n       aes(x = sampleSizes,\n           y = Coverage)) +\n  # Draw lines for expected coverage rate and its 2.5 and 97.5% percentiles.\n  geom_hline(yintercept = qbinom(p = 0.025, runs, ci)/runs, colour = \"grey80\") +\n  geom_hline(yintercept = qbinom(p = 0.975, runs, ci)/runs, colour = \"grey80\") +\n  geom_hline(yintercept = ci, linetype = 2, colour = \"grey10\") +\n  geom_point() +\n  geom_line() +\n  scale_x_log10(breaks = c(5, 50, 500, 5000)) +\n  scale_y_continuous(breaks = seq(0.8, 1, 0.02)) +\n  facet_wrap(~ Method, ncol = 4) +\n  xlab(\"sample size per group\") +\n  ylab(\"Coverage of true standardised d\\nby 90% confidence interval\") +\n  theme(legend.position = \"top\", legend.direction = \"vertical\")\n```\n:::\n\n\n## Software versions\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndevtools::session_info()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n─ Session info ───────────────────────────────────────────────────────────────\n setting  value\n version  R version 4.5.1 (2025-06-13)\n os       Ubuntu 22.04.5 LTS\n system   x86_64, linux-gnu\n ui       X11\n language en_US\n collate  en_US.UTF-8\n ctype    en_US.UTF-8\n tz       Europe/Zurich\n date     2025-10-09\n pandoc   2.12 @ /home/jan/miniconda3/bin/ (via rmarkdown)\n\n─ Packages ───────────────────────────────────────────────────────────────────\n package      * version date (UTC) lib source\n bit            4.6.0   2025-03-06 [1] CRAN (R 4.5.1)\n bit64          4.6.0-1 2025-01-16 [1] CRAN (R 4.5.1)\n cachem         1.1.0   2024-05-16 [1] CRAN (R 4.5.1)\n callr          3.7.6   2024-03-25 [1] CRAN (R 4.5.1)\n cli            3.6.5   2025-04-23 [1] CRAN (R 4.5.1)\n codetools      0.2-19  2023-02-01 [4] CRAN (R 4.2.2)\n compute.es   * 0.2-5   2020-04-01 [1] CRAN (R 4.5.1)\n crayon         1.5.1   2022-03-26 [2] CRAN (R 4.2.0)\n devtools       2.4.5   2022-10-11 [1] CRAN (R 4.5.1)\n digest         0.6.37  2024-08-19 [1] CRAN (R 4.5.1)\n dplyr        * 1.1.4   2023-11-17 [1] CRAN (R 4.5.1)\n effsize      * 0.8.1   2020-10-05 [1] CRAN (R 4.5.1)\n ellipsis       0.3.2   2021-04-29 [2] CRAN (R 4.2.0)\n evaluate       1.0.4   2025-06-18 [1] CRAN (R 4.5.1)\n farver         2.1.2   2024-05-13 [1] CRAN (R 4.5.1)\n fastmap        1.2.0   2024-05-15 [1] CRAN (R 4.5.1)\n forcats      * 1.0.0   2023-01-29 [1] CRAN (R 4.5.1)\n fs             1.5.2   2021-12-08 [2] CRAN (R 4.2.0)\n generics       0.1.4   2025-05-09 [1] CRAN (R 4.5.1)\n ggplot2      * 3.5.2   2025-04-09 [1] CRAN (R 4.5.1)\n glue           1.6.2   2022-02-24 [2] CRAN (R 4.2.0)\n gtable         0.3.6   2024-10-25 [1] CRAN (R 4.5.1)\n hms            1.1.3   2023-03-21 [1] CRAN (R 4.5.1)\n htmltools      0.5.8.1 2024-04-04 [1] CRAN (R 4.5.1)\n htmlwidgets    1.6.4   2023-12-06 [1] CRAN (R 4.5.1)\n httpuv         1.6.16  2025-04-16 [1] CRAN (R 4.5.1)\n jsonlite       2.0.0   2025-03-27 [1] CRAN (R 4.5.1)\n knitr          1.50    2025-03-16 [1] CRAN (R 4.5.1)\n later          1.4.2   2025-04-08 [1] CRAN (R 4.5.1)\n lifecycle      1.0.4   2023-11-07 [1] CRAN (R 4.5.1)\n lubridate    * 1.9.4   2024-12-08 [1] CRAN (R 4.5.1)\n magrittr       2.0.3   2022-03-30 [1] CRAN (R 4.5.1)\n MBESS        * 4.9.41  2025-07-25 [2] CRAN (R 4.5.1)\n memoise        2.0.1   2021-11-26 [2] CRAN (R 4.2.0)\n mime           0.10    2021-02-13 [2] CRAN (R 4.0.2)\n miniUI         0.1.2   2025-04-17 [1] CRAN (R 4.5.1)\n pillar         1.10.2  2025-04-05 [1] CRAN (R 4.5.1)\n pkgbuild       1.3.1   2021-12-20 [2] CRAN (R 4.2.0)\n pkgconfig      2.0.3   2019-09-22 [2] CRAN (R 4.2.0)\n pkgload        1.4.0   2024-06-28 [1] CRAN (R 4.5.1)\n prettyunits    1.1.1   2020-01-24 [2] CRAN (R 4.2.0)\n processx       3.8.6   2025-02-21 [1] CRAN (R 4.5.1)\n profvis        0.4.0   2024-09-20 [1] CRAN (R 4.5.1)\n promises       1.3.3   2025-05-29 [1] CRAN (R 4.5.1)\n ps             1.9.1   2025-04-12 [1] CRAN (R 4.5.1)\n purrr        * 1.0.4   2025-02-05 [1] CRAN (R 4.5.1)\n R6             2.5.1   2021-08-19 [2] CRAN (R 4.2.0)\n RColorBrewer   1.1-3   2022-04-03 [1] CRAN (R 4.5.1)\n Rcpp           1.0.14  2025-01-12 [1] CRAN (R 4.5.1)\n readr        * 2.1.5   2024-01-10 [1] CRAN (R 4.5.1)\n remotes        2.4.2   2021-11-30 [2] CRAN (R 4.2.0)\n rlang          1.1.6   2025-04-11 [1] CRAN (R 4.5.1)\n rmarkdown      2.29    2024-11-04 [1] CRAN (R 4.5.1)\n rstudioapi     0.17.1  2024-10-22 [1] CRAN (R 4.5.1)\n scales         1.4.0   2025-04-24 [1] CRAN (R 4.5.1)\n sessioninfo    1.2.2   2021-12-06 [2] CRAN (R 4.2.0)\n shiny          1.10.0  2024-12-14 [1] CRAN (R 4.5.1)\n stringi        1.7.6   2021-11-29 [2] CRAN (R 4.2.0)\n stringr      * 1.5.1   2023-11-14 [1] CRAN (R 4.5.1)\n tibble       * 3.3.0   2025-06-08 [1] CRAN (R 4.5.1)\n tidyr        * 1.3.1   2024-01-24 [1] CRAN (R 4.5.1)\n tidyselect     1.2.1   2024-03-11 [1] CRAN (R 4.5.1)\n tidyverse    * 2.0.0   2023-02-22 [1] CRAN (R 4.5.1)\n timechange     0.3.0   2024-01-18 [1] CRAN (R 4.5.1)\n tzdb           0.5.0   2025-03-15 [1] CRAN (R 4.5.1)\n urlchecker     1.0.1   2021-11-30 [1] CRAN (R 4.5.1)\n usethis        3.1.0   2024-11-26 [1] CRAN (R 4.5.1)\n vctrs          0.6.5   2023-12-01 [1] CRAN (R 4.5.1)\n vroom          1.6.5   2023-12-05 [1] CRAN (R 4.5.1)\n withr          3.0.2   2024-10-28 [1] CRAN (R 4.5.1)\n xfun           0.52    2025-04-02 [1] CRAN (R 4.5.1)\n xtable         1.8-4   2019-04-21 [1] CRAN (R 4.5.1)\n yaml           2.3.5   2022-02-21 [2] CRAN (R 4.2.0)\n\n [1] /home/jan/R/x86_64-pc-linux-gnu-library/4.5\n [2] /usr/local/lib/R/site-library\n [3] /usr/lib/R/site-library\n [4] /usr/lib/R/library\n\n──────────────────────────────────────────────────────────────────────────────\n```\n\n\n:::\n:::\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}