<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jan Vanhove">
<meta name="dcterms.date" content="2016-12-20">

<title>A few examples of bootstrapping – Jan Vanhove</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-89bf13ec4319bff50ce537e56bf4cb29.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<!-- Google tag (gtag.js) -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-7PMKN7SZET"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-7PMKN7SZET');
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Jan Vanhove</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../support.html"> 
<span class="menu-text">Methods and stats support</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../courses.html"> 
<span class="menu-text">Courses</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../archive.html"> 
<span class="menu-text">Blog archive</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resources.html"> 
<span class="menu-text">Teaching resources</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../publications.html"> 
<span class="menu-text">Publications</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../archive.xml"> <i class="bi bi-rss" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#a-confidence-interval-around-an-asymmetrically-trimmed-mean" id="toc-a-confidence-interval-around-an-asymmetrically-trimmed-mean" class="nav-link active" data-scroll-target="#a-confidence-interval-around-an-asymmetrically-trimmed-mean">A confidence interval around an asymmetrically trimmed mean</a></li>
  <li><a href="#a-confidence-interval-for-a-regression-coefficient-non-parametric-parametric-and-semi-parametric-bootstrapping" id="toc-a-confidence-interval-for-a-regression-coefficient-non-parametric-parametric-and-semi-parametric-bootstrapping" class="nav-link" data-scroll-target="#a-confidence-interval-for-a-regression-coefficient-non-parametric-parametric-and-semi-parametric-bootstrapping">A confidence interval for a regression coefficient: Non-parametric, parametric and semi-parametric bootstrapping</a>
  <ul class="collapse">
  <li><a href="#non-parametric-bootstrap" id="toc-non-parametric-bootstrap" class="nav-link" data-scroll-target="#non-parametric-bootstrap">Non-parametric bootstrap</a></li>
  <li><a href="#parametric-bootstrap" id="toc-parametric-bootstrap" class="nav-link" data-scroll-target="#parametric-bootstrap">Parametric bootstrap</a></li>
  <li><a href="#semi-parametric-bootstrap" id="toc-semi-parametric-bootstrap" class="nav-link" data-scroll-target="#semi-parametric-bootstrap">Semi-parametric bootstrap</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a></li>
  </ul></li>
  <li><a href="#testing-null-hypotheses-using-bootstrapping" id="toc-testing-null-hypotheses-using-bootstrapping" class="nav-link" data-scroll-target="#testing-null-hypotheses-using-bootstrapping">Testing null hypotheses using bootstrapping</a>
  <ul class="collapse">
  <li><a href="#parametric-bootstrapping" id="toc-parametric-bootstrapping" class="nav-link" data-scroll-target="#parametric-bootstrapping">Parametric bootstrapping</a></li>
  <li><a href="#semi-parametric-bootstrapping" id="toc-semi-parametric-bootstrapping" class="nav-link" data-scroll-target="#semi-parametric-bootstrapping">Semi-parametric bootstrapping</a></li>
  <li><a href="#results-1" id="toc-results-1" class="nav-link" data-scroll-target="#results-1">Results</a></li>
  </ul></li>
  <li><a href="#concluding-remarks" id="toc-concluding-remarks" class="nav-link" data-scroll-target="#concluding-remarks">Concluding remarks</a></li>
  <li><a href="#software-versions" id="toc-software-versions" class="nav-link" data-scroll-target="#software-versions">Software versions</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">A few examples of bootstrapping</h1>
  <div class="quarto-categories">
    <div class="quarto-category">bootstrapping</div>
    <div class="quarto-category">R</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jan Vanhove </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 20, 2016</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>This post illustrates a statistical technique that becomes particularly useful when you want to calculate the sampling variation of some custom statistic when you start to dabble in mixed-effects models. This technique is called <a href="https://books.google.ch/books/about/An_Introduction_to_the_Bootstrap.html?id=gLlpIUxRntoC"><strong>bootstrapping</strong></a> and I will first illustrate its use in constructing confidence intervals around a custom summary statistic. Then I’ll illustrate three bootstrapping approaches when constructing confidence intervals around a regression coefficient, and finally, I will show how bootstrapping can be used to compute <em>p</em>-values.</p>
<p>The goal of this post is <em>not</em> to argue that bootstrapping is superior to the traditional alternatives—in the examples discussed, they are pretty much on par—but merely to illustrate how it works. The main advantage of bootstrapping, as I understand it, is that it can be applied in situation where the traditional alternatives are not available, where you don’t understand how to use them or where their assumptions are questionable, but I think it’s instructive to see how its results compare to those of traditional approaches where both can readily be applied.</p>
<p>Those interested can <a href="http://janhove.github.io/RCode/bootstrapping.Rmd">download</a> the <code>R</code> code for this post.</p>
<section id="a-confidence-interval-around-an-asymmetrically-trimmed-mean" class="level2">
<h2 class="anchored" data-anchor-id="a-confidence-interval-around-an-asymmetrically-trimmed-mean">A confidence interval around an asymmetrically trimmed mean</h2>
<p>The histogram below shows how well 159 participants performed on a L1 German vocabulary test (<em>WST</em>). While the distribution is clearly left-skewed, we still want to characterise its central tendency. Let’s say, for the sake of this example, that we decide to calculate the sample mean, but we want to disregard the lowest 10% of scores. For this sample, this yields a value of 32.7.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.svg" class="img-fluid figure-img"></p>
<figcaption>The distribution of 159 <em>WST</em> (German vocabulary test) scores. Disregarding the bottom 10% of this sample (16 values), its mean is 32.7.</figcaption>
</figure>
</div>
</div>
</div>
<p>Easy enough, but let’s say we want to express the sampling variation of this number (32.7) using an 80% confidence interval? Constructing confidence intervals around regular means can be done using the appropriate <em>t</em>-distribution, but we may not feel comfortable applying this approach to a mean based on the top 90% of the data only or we may not be sure how many degrees of freedom the <em>t</em>-distribution should have (158 or 142?). (In practice, this won’t make much of a difference, but verifying this would be reassuring.)</p>
<p>One possible solution is to proceed as follows. We take the sample that we actually observed (the green histogram below) and use it to create a <em>new</em> sample with the same number of observations (in this case: 159). We do this by taking a random observation from the original dataset, jotting down its value, putting it back in the dataset, sampling again etc., until we have the number of observations required (<strong>resampling with replacement</strong>). This new sample will be fairly similar in shape to our original sample, but won’t be identical to it (the purple histogram below): Some values will occur more often than in the original sample, others less often, and some may not occur at all in the new sample. We then compute the statistic of interest for the new sample (here: the mean after disregarding the lowest 10% of observations; the dashed red line) and jot down its value. We can do this, say, 20,000 times to see to what extent the trimmed means vary in the new, randomly created samples (blue histogram below).</p>
<p><strong>Update (2023-08-08):</strong> I reran the code with 20,000 bootstrap runs; in the original blog post, I only used 1,000 bootstrap runs.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.svg" class="img-fluid figure-img"></p>
<figcaption><em>Top row:</em> The observed distribution of WST scores; the dashed red line indicates the asymmetrically trimmed mean (disregarding the bottom 10% of the data). <em>Middle row</em>: Three new samples obtained by resampling with replacement from the observed WST distribution and their asymmetrically trimmed means. <em>Bottom row:</em> The distribution of asymmetrically trimmed means in 20,000 such new samples.</figcaption>
</figure>
</div>
</div>
</div>
<p>To construct a 80% confidence interval around the asymmetrically trimmed mean of 32.7, we can sort the values in the blue histogram from low to high and look up the values that demarcate the middle 80% (roughly 31.9 and 33.6).</p>
<p>The technique used above—generating new samples based on the observed data to assess how much a statistic varies in similar but different samples—is known as <strong>bootstrapping</strong>. It is particularly useful when you want to gauge the variability of a sample statistic</p>
<ul>
<li>when you don’t have an analytic means of doing so (e.g., based on a theoretical distribution such as the <em>t</em>-distribution for sample means)<br>
</li>
<li>or if you fear that the assumptions behind the analytic approach may be violated to such an extent that it may not provide good enough approximations.</li>
</ul>
<p>While I’ve described <em>how</em> bootstrapping works, it’s less easy to see <em>why</em> it works. To assess the sampling variation of a given sample statistic, we would ideally have access to the population from which the sample at hand was drawn. Needless to say, we rarely have this luxury, and the sample at hand typically represents our best guess of how the population might look like, so we use our sample as a stand-in for the population.</p>
<p>Perhaps you feel that it requires too big a leap of faith to use the sample we have as a stand-in for the population. After all, by chance, the sample we have may poorly reflect the population from which it was drawn. I think this is a reasonable concern, but rather than to alleviate it, I will just point out that analytical approaches operate on similar assumptions: <em>t</em>-values, for instance, use the sample standard deviations as stand-ins for the population standard deviations, and their use in smaller samples is predicated on the fiction that the samples were drawn from normal distributions. Assumptions, then, are needed to get a handle on inferential problems, whether you choose to solve them analytically, using bootstrapping or by another means.</p>
</section>
<section id="a-confidence-interval-for-a-regression-coefficient-non-parametric-parametric-and-semi-parametric-bootstrapping" class="level2">
<h2 class="anchored" data-anchor-id="a-confidence-interval-for-a-regression-coefficient-non-parametric-parametric-and-semi-parametric-bootstrapping">A confidence interval for a regression coefficient: Non-parametric, parametric and semi-parametric bootstrapping</h2>
<p>The procedure outlined in the example above is only one kind of bootstrapping. While it’s usually just called ‘bootstrapping’, it is sometimes called <strong>non-parametric bootstrapping</strong> to distinguish it from two other flavours of bootstrapping: <strong>parametric bootstrapping</strong> and <strong>semi-parametric bootstrapping</strong>. In this section, I will briefly explain the difference between these three techniques using a regression example.</p>
<p>We have a dataset with 159 observations of four variables, whose intercorrelations are outlined below. The outcome variable is <code>TotCorrect</code>; the other three variables serve as predictors.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.svg" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>After standardising the three predictors, we fit a multiple regression model on these data, which yields the following estimated coefficients:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                Estimate
(Intercept)        16.50
z.WST               1.15
z.Raven             1.89
z.English.Cloze     1.60</code></pre>
</div>
</div>
<p>To express the variabilitity of <code>z.WST</code>’s coefficient, we want to construct a 90% confidence interval around it. We could use the regression model’s output to construct a 90% confidence interval using the appropriate <em>t</em>-distribution, but for the sake of the argument, let’s pretend that option is off the table.</p>
<section id="non-parametric-bootstrap" class="level3">
<h3 class="anchored" data-anchor-id="non-parametric-bootstrap">Non-parametric bootstrap</h3>
<p>For the non-parametric bootstrap, we do essentially the same as in the previous example, but rather than computing the trimmed means for 20,000 new samples, we fit a regression model on them and jot down the estimated coefficient for <code>z.WST</code>.</p>
<ol type="1">
<li>Resample 159 rows with replacement from the original dataset.</li>
<li>Fit the multiple regression model on the new dataset.</li>
<li>Jot down the estimated coefficient for <code>z.WST</code>.</li>
<li>Perform steps 1–3 20,000 times.</li>
</ol>
<p>(The results are shown further down.)</p>
</section>
<section id="parametric-bootstrap" class="level3">
<h3 class="anchored" data-anchor-id="parametric-bootstrap">Parametric bootstrap</h3>
<p>The regression model above is really just an equation:</p>
<p><span class="math display">\[
\textrm{TotCorrect}_i = 16.50 + 1.15\times \textrm{z.WST}_i + 1.89\times\textrm{z.Raven}_i+1.60\times\textrm{z.English.Cloze}_i + \textrm{random error}_i,
\]</span></p>
<p>where the random errors are assumed to be normally distributed around 0 with a standard deviation that is estimated from the data.</p>
<p>Instead of randomly resampling cases from the original dataset, we could use this regression equation to generate new outcome values. Due to the random error term, new simulated samples will differ from each other. We can then refit the regression model on the new values to see how much the estimated coefficients vary.</p>
<ol type="1">
<li>Simulate 159 new outcome values on the basis of the regression model (prediction + random error from normal distribution) and the original predictors.</li>
<li>Fit the multiple regression model on the new outcome values using the old predictors.</li>
<li>Jot down the estimated coefficient for <code>z.WST</code>.</li>
<li>Perform steps 1–3 20,000 times.</li>
</ol>
<p>This approach is called <em>parametric</em> bootstrapping because it relies on the original model’s estimated regression coefficients (parameters), its error term estimate as well as the assumption that the errors are drawn from a normal distribution.</p>
</section>
<section id="semi-parametric-bootstrap" class="level3">
<h3 class="anchored" data-anchor-id="semi-parametric-bootstrap">Semi-parametric bootstrap</h3>
<p>As its name suggests, the semi-parametric bootstrap is a compromise between the non-parametric and the parametric bootstrap. The new outcome values are partly based on the original regression model, but instead of drawing the errors randomly from a normal distribution, the original model’s errors are resampled with replacement and added to the model’s predictions.</p>
<ol type="1">
<li>Extract the residuals (errors) from the original regression model.</li>
<li>Predict 159 new outcome values on the basis of the regression model (prediction only) and the original predictors.</li>
<li>Resample 159 values with replacement from the errors extracted in step 1 and add these to the predictions from step 2.</li>
<li>Fit the multiple regression model on the new outcome values (prediction + resampled errors) using the old predictors.</li>
<li>Jot down the estimated coefficient for <code>z.WST</code>.</li>
<li>Perform steps 3–5 20,000 times.</li>
</ol>
<p>This approach is called <em>semi-parametric</em> bootstrapping because, while it relies on the original model’s estimated regression coefficients, the error distribution is assumed to be normal but is instead approximated by sampling from the original model’s errors.</p>
</section>
<section id="results" class="level3">
<h3 class="anchored" data-anchor-id="results">Results</h3>
<p>The histograms below show the sampling variability of the estimated <code>z.WST</code> coefficient according to each method.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-11-1.svg" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>To construct 90% confidence intervals, we pick the 5th and 95th percentiles of the bootstrapped estimates. The resulting intervals are plotted below alongside the 90% confidence interval constructed from the model summary. In this case, the confidence interval obtained by nonparametric bootstrapping is a bit wider.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-12-1.svg" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="testing-null-hypotheses-using-bootstrapping" class="level2">
<h2 class="anchored" data-anchor-id="testing-null-hypotheses-using-bootstrapping">Testing null hypotheses using bootstrapping</h2>
<p>Another use for parametric and semi-parametric bootstrapping is to compute <em>p</em>-values if they can’t be computed analytically or if the assumptions of the analytical approach aren’t adequately met. The basic logic is the same in either case: You generate a large number of datasets in which you <em>know</em> the null hypothesis (e.g., ‘no difference’ or ‘the coefficient is 0’ or perhaps even ‘the difference/coefficient is 0.3’) to be true. You then compute whichever statistic you’re interested in for all of these new datasets and you calculate the proportion of cases where the statistic in the new datasets exceeds the statistic in your original sample. This proportion is a <em>p</em>-value as it expresses the (approximate) probability of observing a sample statistic of at least this magnitude if the null hypothesis is actually true.</p>
<p>(Example for more advanced users: Likelihood ratio tests used for comparing nested mixed effects models are based on the assumption that likelihood ratios follow a <span class="math inline">\(\chi^2\)</span> distribution if the null hypothesis is true. This is a good enough assumption for large samples, but when you’re fitting mixed effects models, it isn’t always clear exactly what a large sample is. When in doubt, you can <a href="https://cran.r-project.org/web/packages/pbkrtest/index.html">resort</a> to <a href="https://cran.r-project.org/web/packages/lme4/lme4.pdf#page.6">bootstrapping</a> in such cases: You generate new datasets in which the null hypothesis is true and compute likelihood ratios for them. These likelihood ratios then serve as distribution of likelihood ratios under the null hypothesis against which you can then compare the likelihood ratio computed for your original dataset.)</p>
<p>For illustrative purposes, we’re going to compute the <em>p</em>-value for the estimated <code>z.WST</code> coefficient from the previous example using parametric and semi-parametric bootstrapping, although there are no reasons to suspect that the <em>t</em>-distribution-based <em>p</em>-value in the model output (0.012) is completely off. As such, we’d expect the three methods to yield similar results. For both the parametric and semi-parametric bootstraps, we need to generate datasets in which we <em>know</em> the null hypothesis to be true (i.e., the coefficient for <code>z.WST</code> = 0). This we do by first fitting a <strong>null model</strong> to the data, that is, a model that is similar to the full model we want to fit but without the <code>z.WST</code> term we want to compute the <em>p</em>-value for. Then we generate new datasets on the basis of this null model. This guarantees that the null hypothesis is actually true in all newly generated samples, so that the distribution of the estimated <code>z.WST</code> coefficients for the newly generated samples can serve as an approximation of the estimated <code>z.WST</code> coefficient’s distribution under the null hypothesis.</p>
<p>The steps for computing <em>p</em>-values using a parametric and semi-parametric bootstrap are pretty similar; the only real difference is whether we’re more comfortable assuming that the residuals are drawn from a normal distribution or that their distribution is similar to that of the null model’s residuals.</p>
<section id="parametric-bootstrapping" class="level3">
<h3 class="anchored" data-anchor-id="parametric-bootstrapping">Parametric bootstrapping</h3>
<ol type="1">
<li>Fit a null model, i.e., a model <em>without</em> whichever term you want to compute the <em>p</em>-value for (here: <code>z.WST</code>).</li>
<li>Simulate 159 new outcome values on the basis of the null model (prediction + random error from normal distribution) and the predictors in the null model.</li>
<li>Fit the <em>full</em> multiple regression model, i.e., with the term we want to compute the <em>p</em>-value for, on the new outcome values using the old predictors.</li>
<li>Jot down the esetimated coefficient for <code>z.WST</code>.</li>
<li>Perform steps 2–4 20,000 times.</li>
<li>See how often the estimated <code>z.WST</code> coefficients in the 20,000 samples generated under the null hypothesis are larger in magnitude than the estimated <code>z.WST</code> coefficient in the original sample. This is the <em>p</em>-value.</li>
</ol>
<p>(Results below.)</p>
</section>
<section id="semi-parametric-bootstrapping" class="level3">
<h3 class="anchored" data-anchor-id="semi-parametric-bootstrapping">Semi-parametric bootstrapping</h3>
<ol type="1">
<li>Fit a null model, i.e., a model <em>without</em> whichever term you want to compute the <em>p</em>-value for (here: <code>z.WST</code>).</li>
<li>Extract the null model’s residuals (errors).</li>
<li>Predict 159 new outcome values on the basis of the null model (prediction only) and the predictors in the null model.</li>
<li>Resample 159 values with replacement from the errors extracted in step 2 and add these to the predictions from step 3.</li>
<li>Fit the <em>full</em> multiple regression model, i.e., with the term we want to compute the <em>p</em>-value for, on the new outcome values (prediction + resampled error) using the old predictors.</li>
<li>Jot down the estimated coefficient for <code>z.WST</code>.</li>
<li>Perform steps 4–6 20,000 times.</li>
<li>See how often the estimated <code>z.WST</code> coefficients in the 20,000 samples generated under the null hypothesis are larger in magnitude than the estimated <code>z.WST</code> coefficient in the original sample. This is the <em>p</em>-value.</li>
</ol>
</section>
<section id="results-1" class="level3">
<h3 class="anchored" data-anchor-id="results-1">Results</h3>
<p>The distribution of the <code>z.WST</code> looks pretty similar whether we use parametric or semi-parametric bootstrapping.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-15-1.svg" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The <em>p</em>-value obtained by parametric bootstrapping is 0.0146 (i.e., 291 out of 20,000 estimated <code>z.WST</code> coefficients have absolute values larger than 1.15), the one obtained by semi-parametric bootstrapping is 0.0122, whereas the <em>t</em>-distribution-based <em>p</em>-value was 0.012. As expected, then, there is hardly any difference between them. The bootstrapped <em>p</em>-values are themselves subject to random variation, and different runs of the bootstrap will produce slightly different results. We could increase the number of bootstrap runs for greater accuracy, but I don’t think this is really necessary here.</p>
</section>
</section>
<section id="concluding-remarks" class="level2">
<h2 class="anchored" data-anchor-id="concluding-remarks">Concluding remarks</h2>
<p>My goal was to illustrate how bootstrapping works rather than to discuss at length when to use which approach. Indeed, in the regression example above, the results of the bootstraps hardly differ from the <em>t</em>-distribution-based results, so the choice of method doesn’t really matter much.</p>
<p>That said, bootstrapping is a technique that’s useful to at least know about as it comes in handy if you want to estimate the sampling variation of a summary statistic in some funky distribution or if you want to verify, say, a likelihood ratio test for nested mixed-effects models.</p>
</section>
<section id="software-versions" class="level2">
<h2 class="anchored" data-anchor-id="software-versions">Software versions</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>devtools<span class="sc">::</span><span class="fu">session_info</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>─ Session info ───────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.5.1 (2025-06-13)
 os       Ubuntu 22.04.5 LTS
 system   x86_64, linux-gnu
 ui       X11
 language en_US
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       Europe/Zurich
 date     2025-09-24
 pandoc   2.12 @ /home/jan/miniconda3/bin/ (via rmarkdown)

─ Packages ───────────────────────────────────────────────────────────────────
 package      * version date (UTC) lib source
 cachem         1.1.0   2024-05-16 [1] CRAN (R 4.5.1)
 callr          3.7.6   2024-03-25 [1] CRAN (R 4.5.1)
 cli            3.6.5   2025-04-23 [1] CRAN (R 4.5.1)
 crayon         1.5.1   2022-03-26 [2] CRAN (R 4.2.0)
 devtools       2.4.5   2022-10-11 [1] CRAN (R 4.5.1)
 digest         0.6.37  2024-08-19 [1] CRAN (R 4.5.1)
 dplyr        * 1.1.4   2023-11-17 [1] CRAN (R 4.5.1)
 ellipsis       0.3.2   2021-04-29 [2] CRAN (R 4.2.0)
 evaluate       1.0.4   2025-06-18 [1] CRAN (R 4.5.1)
 farver         2.1.2   2024-05-13 [1] CRAN (R 4.5.1)
 fastmap        1.2.0   2024-05-15 [1] CRAN (R 4.5.1)
 forcats      * 1.0.0   2023-01-29 [1] CRAN (R 4.5.1)
 fs             1.5.2   2021-12-08 [2] CRAN (R 4.2.0)
 generics       0.1.4   2025-05-09 [1] CRAN (R 4.5.1)
 ggplot2      * 3.5.2   2025-04-09 [1] CRAN (R 4.5.1)
 glue           1.6.2   2022-02-24 [2] CRAN (R 4.2.0)
 gtable         0.3.6   2024-10-25 [1] CRAN (R 4.5.1)
 hms            1.1.3   2023-03-21 [1] CRAN (R 4.5.1)
 htmltools      0.5.8.1 2024-04-04 [1] CRAN (R 4.5.1)
 htmlwidgets    1.6.4   2023-12-06 [1] CRAN (R 4.5.1)
 httpuv         1.6.16  2025-04-16 [1] CRAN (R 4.5.1)
 jsonlite       2.0.0   2025-03-27 [1] CRAN (R 4.5.1)
 knitr          1.50    2025-03-16 [1] CRAN (R 4.5.1)
 labeling       0.4.3   2023-08-29 [1] CRAN (R 4.5.1)
 later          1.4.2   2025-04-08 [1] CRAN (R 4.5.1)
 lifecycle      1.0.4   2023-11-07 [1] CRAN (R 4.5.1)
 lubridate    * 1.9.4   2024-12-08 [1] CRAN (R 4.5.1)
 magrittr     * 2.0.3   2022-03-30 [1] CRAN (R 4.5.1)
 memoise        2.0.1   2021-11-26 [2] CRAN (R 4.2.0)
 mime           0.10    2021-02-13 [2] CRAN (R 4.0.2)
 miniUI         0.1.2   2025-04-17 [1] CRAN (R 4.5.1)
 patchwork    * 1.3.2   2025-08-25 [1] CRAN (R 4.5.1)
 pillar         1.10.2  2025-04-05 [1] CRAN (R 4.5.1)
 pkgbuild       1.3.1   2021-12-20 [2] CRAN (R 4.2.0)
 pkgconfig      2.0.3   2019-09-22 [2] CRAN (R 4.2.0)
 pkgload        1.4.0   2024-06-28 [1] CRAN (R 4.5.1)
 prettyunits    1.1.1   2020-01-24 [2] CRAN (R 4.2.0)
 processx       3.8.6   2025-02-21 [1] CRAN (R 4.5.1)
 profvis        0.4.0   2024-09-20 [1] CRAN (R 4.5.1)
 promises       1.3.3   2025-05-29 [1] CRAN (R 4.5.1)
 ps             1.9.1   2025-04-12 [1] CRAN (R 4.5.1)
 purrr        * 1.0.4   2025-02-05 [1] CRAN (R 4.5.1)
 R6             2.5.1   2021-08-19 [2] CRAN (R 4.2.0)
 RColorBrewer * 1.1-3   2022-04-03 [1] CRAN (R 4.5.1)
 Rcpp           1.0.14  2025-01-12 [1] CRAN (R 4.5.1)
 readr        * 2.1.5   2024-01-10 [1] CRAN (R 4.5.1)
 remotes        2.4.2   2021-11-30 [2] CRAN (R 4.2.0)
 rlang          1.1.6   2025-04-11 [1] CRAN (R 4.5.1)
 rmarkdown      2.29    2024-11-04 [1] CRAN (R 4.5.1)
 rstudioapi     0.17.1  2024-10-22 [1] CRAN (R 4.5.1)
 scales         1.4.0   2025-04-24 [1] CRAN (R 4.5.1)
 sessioninfo    1.2.2   2021-12-06 [2] CRAN (R 4.2.0)
 shiny          1.10.0  2024-12-14 [1] CRAN (R 4.5.1)
 stringi        1.7.6   2021-11-29 [2] CRAN (R 4.2.0)
 stringr      * 1.5.1   2023-11-14 [1] CRAN (R 4.5.1)
 tibble       * 3.3.0   2025-06-08 [1] CRAN (R 4.5.1)
 tidyr        * 1.3.1   2024-01-24 [1] CRAN (R 4.5.1)
 tidyselect     1.2.1   2024-03-11 [1] CRAN (R 4.5.1)
 tidyverse    * 2.0.0   2023-02-22 [1] CRAN (R 4.5.1)
 timechange     0.3.0   2024-01-18 [1] CRAN (R 4.5.1)
 tzdb           0.5.0   2025-03-15 [1] CRAN (R 4.5.1)
 urlchecker     1.0.1   2021-11-30 [1] CRAN (R 4.5.1)
 usethis        3.1.0   2024-11-26 [1] CRAN (R 4.5.1)
 vctrs          0.6.5   2023-12-01 [1] CRAN (R 4.5.1)
 withr          3.0.2   2024-10-28 [1] CRAN (R 4.5.1)
 xfun           0.52    2025-04-02 [1] CRAN (R 4.5.1)
 xtable         1.8-4   2019-04-21 [1] CRAN (R 4.5.1)
 yaml           2.3.5   2022-02-21 [2] CRAN (R 4.2.0)

 [1] /home/jan/R/x86_64-pc-linux-gnu-library/4.5
 [2] /usr/local/lib/R/site-library
 [3] /usr/lib/R/site-library
 [4] /usr/lib/R/library

──────────────────────────────────────────────────────────────────────────────</code></pre>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/janhove\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>