{
  "hash": "e1686cd2c13db94229cb0f5c6612d1ac",
  "result": {
    "markdown": "---\ntitle: \"Tutorial: Plotting regression models\"\ndate: \"2017-04-23\"\ncategories: [R, graphs, logistic regression, mixed-effects models, multiple regression, tutorial]\nexecute:\n  cache: true\n---\n\n::: {.cell hash='index_cache/html/unnamed-chunk-1_1e3d623ad756a5b8ab818ea827e4d0ce'}\n\n:::\n\n\nThe results of regression models,\nparticularly fairly complex ones,\ncan be difficult to appreciate\nand hard to communicate to an audience.\nOne useful technique is to plot\nthe effect of each predictor variable\non the outcome while holding constant\nany other predictor variables.\n[Fox (2003)](https://www.jstatsoft.org/article/view/v008i15)\ndiscusses how such **effect displays** are \nconstructed and provides an implementation\nin the `effects` package for `R`.\n\nSince I think it's both instructive to see how effect displays \nare constructed from the ground up\nand useful to be able to tweak them yourself in `R`, \nthis blog post illustrates how to draw such plots\nfor three increasingly complex statistical models:\nordinary multiple regression,\nlogistic regression,\nand mixed-effects logistic regression.\nThe goal in each of these three examples\nis to visualise the effects of the predictor\nvariables without factoring in the uncertainty \nabout these effects;\nvisualising such uncertainty will be the\ntopic of a future blog post.\n\n## Multiple regression\n\n### Data\nFor the first example, we'll use a dataset\nfrom my PhD thesis. 163 German-speaking participants\ntranslated 45 spoken Swedish words into German\nand took a couple of cognitive and linguistic tests.\nFor the sake of this example, we will model\nthe number of correctly translated spoken words\n(`Spoken`) in terms of the participants' performance\non an intelligence test (`Raven.Right`)\nand an English-language test (`English.Cloze`)\nas well as their `Sex`.\nWe'll also fit an interaction between the \nintelligence test score and the participants' sex,\nbut this is mainly to illustrate how interactions\ncan be visualised in effect displays.\n\nThe lines below read in the data,\nretain the variables of interest,\nfilter out any rows with incomplete data,\nand summarise the structure of the dataset.\n\n\n::: {.cell hash='index_cache/html/unnamed-chunk-2_bba1498185d3f3837503d4a8a46c294c'}\n\n```{.r .cell-code}\n# Read in data\nex1 <- read.csv(\"http://homeweb.unifr.ch/VanhoveJ/Pub/Data/participants_163.csv\",\n                stringsAsFactors = TRUE)\n# Retain variables of interest\nex1 <- ex1[, c(\"Subject\", \"Spoken\", \"Sex\", \"Raven.Right\", \"English.Cloze\")]\n# Retain complete cases\nex1 <- ex1[complete.cases(ex1), ]\n# Summarise structure\nstr(ex1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t160 obs. of  5 variables:\n $ Subject      : int  1034 1076 1232 1264 1312 134 1350 1401 1404 1644 ...\n $ Spoken       : int  19 20 20 9 2 24 18 20 20 21 ...\n $ Sex          : Factor w/ 2 levels \"female\",\"male\": 1 2 2 2 2 2 2 2 1 1 ...\n $ Raven.Right  : int  23 32 8 19 2 24 31 21 27 19 ...\n $ English.Cloze: int  11 11 19 2 2 8 21 20 15 17 ...\n```\n:::\n:::\n\n\n### Model\nSince this isn't a tutorial on modelling data,\nwe won't bother with whether this dataset can\nbe analysed in a better way and we'll just\nfit the data in a multiple regression model.\nEven though it isn't really necessary in this\nexample, it's generally good practice to first centre \nthe numeric predictors at their sample means\nand to convert the binary predictor `Sex`\nto a numeric predictor with the values\n-0.5 and 0.5 for `female` and `male`, respectively\n(= sum-coding). \nThis makes the model's intercept readily\ninterpretable as the modelled `Spoken` score\nfor someone of unknown sex with average Raven \nand English scores. In this example, it adds a \ncouple of extra steps to the process, but \ncentring and numerically recoding variables is \na good habit to get into.\n\n\n::: {.cell hash='index_cache/html/unnamed-chunk-3_7d9af38c5336fde34225e2dac4d2887d'}\n\n```{.r .cell-code}\n# Define shorthand for centring at sample mean,\n# i.e., subtracting sample mean from each value\nc. <- function(x) x - mean(x)\n\n# Centre numeric predictors at sample mean\nex1$c.Raven <- c.(ex1$Raven.Right)\nex1$c.English <- c.(ex1$English.Cloze)\n\n# Sum-code binary predictor (-0.5 vs. 0.5)\nex1$n.Sex <- as.numeric(ex1$Sex) - 1.5\n# Confirm that female = -0.5, and male = 0.5\nxtabs(~ n.Sex + Sex, ex1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      Sex\nn.Sex  female male\n  -0.5     89    0\n  0.5       0   71\n```\n:::\n\n```{.r .cell-code}\n# Fit multiple regression model with n.Sex, \n# c.Raven, their interaction, and c.English\nmod1 <- lm(Spoken ~ n.Sex * c.Raven + c.English,\n           data = ex1)\n\n# Show model coefficients\ncoef(mod1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  (Intercept)         n.Sex       c.Raven     c.English n.Sex:c.Raven \n       16.510        -1.234         0.209         0.329         0.180 \n```\n:::\n:::\n\n\n### Effect displays\n\nFor the first effect display, we want to visualise the modelled\nrelationship between the participants' English score and their sex \non the one hand and their `Spoken` score on the other hand\nwhile holding constant their performance on the Raven intelligence test.\nTo this end, we create a new dataframe (I'll prefix these with `nd`) \nthat contains each unique `c.English` value that occurs in the dataset \n(there are 25 such values) in combination with each possible value of \n`n.Sex` (i.e., -0.5 and 0.5), yielding a dataframe with 50 entries.\nTo this dataframe, we add the `c.Raven` value at which we want to hold \nthis variable constant. A natural choice is the sample mean, which is \nobviously 0 for the centred variable. But you could also pick the \nsample median (`median(ex1$c.Raven)`) instead, or indeed any other \nvalue that you think is sensible. The `expand.grid()` call accomplishes \nall of this:\n\n\n::: {.cell hash='index_cache/html/unnamed-chunk-4_98c311e99d010f98e217d72e72a76862'}\n\n```{.r .cell-code}\nnd1_eng <- expand.grid(\n  # Two possible values for n.Sex\n  n.Sex = c(-0.5, 0.5),\n  # Fix c.Raven at its sample mean (= 0)\n  c.Raven = 0,\n  # Unique c.English values in sample\n  c.English = unique(ex1$c.English)\n)\n# Show first 6 rows\nhead(nd1_eng)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  n.Sex c.Raven c.English\n1  -0.5       0     -3.64\n2   0.5       0     -3.64\n3  -0.5       0      4.36\n4   0.5       0      4.36\n5  -0.5       0    -12.64\n6   0.5       0    -12.64\n```\n:::\n:::\n\n\nWe can now add to this dataframe the average `Spoken` values \nthat you would expect to find according to the regression model \nfor each combination of the `n.Sex`, `c.Raven` and `c.English`\nvalues listed. This is simply a matter of taking these values, \nmultiplying them by the corresponding model efficients \n(shown under 'Model' above), and adding them up \n(don't forget to include the intercept term!).\n\nLet's walk through this for the first row in `nd1_eng`.\n\n* Take the model's estimated intercept: **16.51**.\n* Multiply -0.5 (`n.Sex` value) with the model's `n.Sex` coefficient: \n-0.5 &#215; -1.234 = **0.617**.\n* Multiply 0 (`c.Raven` value) with the model's `c.Raven` coefficient,\nwhich obviously yields **0**.\n* Multiply -3.64 (`c.English` value) with the model's `c.English` coefficient: \n-3.64 &#215; 0.329 = **-1.2**.\n* For the interaction term between `n.Sex` and `c.Raven`, \nmultiply the two values and the interaction coefficient: \n-0.5 &#215; 0 &#215; 0.180 = **0**.\n* Add the results: 16.51 + 0.617 + 0 - 1.2 + 0 = **15.9**.\n\n15.9, then, is the predicted average `Spoken` value for women \nwhose Raven intelligence score is at the sample mean and \nwhose English-language test result is 3.64 below the sample mean. \n(If you ever come across the expression M<i>&beta;</i> in a statistics text,\nthe above computation is what is meant: take the predictor values,\nmultiply them with the respective model coefficients,\nand add them up together with the intercept.)\nThe `predict()` does this calculation for all rows in `nd1_eng`:\n\n\n::: {.cell hash='index_cache/html/unnamed-chunk-5_45a740b149022eee1cfebf9c01484630'}\n\n```{.r .cell-code}\n# Use mod1 to 'predict' the Spoken values for the data in nd1_eng,\n# and add these predictions to nd1_eng:\nnd1_eng$Prediction <- predict(mod1, newdata = nd1_eng)\n\n# Show first 6 rows\nhead(nd1_eng)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  n.Sex c.Raven c.English Prediction\n1  -0.5       0     -3.64       15.9\n2   0.5       0     -3.64       14.7\n3  -0.5       0      4.36       18.6\n4   0.5       0      4.36       17.3\n5  -0.5       0    -12.64       13.0\n6   0.5       0    -12.64       11.7\n```\n:::\n:::\n\n\nNow, finally, we can use these predicted values to visualise\nthe modelled relationship between `c.English` and `n.Sex`\non the one hand and `Spoken` on the other hand.\n(Check out the \n[tutorial on drawing line charts](../2016-06-13-drawing-a-linechart)\nif the following commands are new to you.)\n\n\n::: {.cell hash='index_cache/html/unnamed-chunk-6_90b1e22c91079d186d9687c29dbce842'}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nggplot(nd1_eng,\n       aes(x = c.English,\n           y = Prediction,\n           colour = factor(n.Sex))) +\n  geom_line()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.svg)\n:::\n:::\n\n\nThe predictor variables `c.English` and `n.Sex` aren't readily\ninterpretable because they are centred and sum-coded, respectively.\nTo make the plot above more informative, we can de-centre the \n`c.English` variable by simply adding the sample mean of \n`English.Cloze` in the original dataset (= `ex1`) to the \n`c.English` values in `nd1_eng`. Similarly, we can relabel \nthe values in `n.Sex`:\n\n\n::: {.cell hash='index_cache/html/unnamed-chunk-7_95ceee64b94bb85e9db879a0b1a79809'}\n\n```{.r .cell-code}\n# De-centre c.English\nnd1_eng$English.Cloze <- nd1_eng$c.English + mean(ex1$English.Cloze)\n# Relabel n.Sex\nnd1_eng$Sex <- ifelse(nd1_eng$n.Sex == -0.5, \"woman\", \"man\")\n\n# Plot using decentred/relabel variables\nggplot(nd1_eng,\n       aes(x = English.Cloze,\n           y = Prediction,\n           colour = Sex)) +\n  geom_line() +\n  xlab(\"English cloze test score\") +\n  ylab(\"Modelled 'Spoken' score\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-1.svg)\n:::\n:::\n\n\nThe plot shows the average `Spoken` values \npredicted by the regression model\nfor men and women with a Raven test score\nequal to the current sample mean depending\non their performance on the English cloze test.\nUsually, though, the precise values\nmatter less than the general pattern of the results.\n\nThe female advantage in the plot above is constant across\nthe `English.Cloze` range, which isn't surprising:\nwe didn't model an interaction between `n.Sex` and `c.English`,\nso we won't find one if we plot the modelled effects.\nWe did, however, model an interaction between `n.Sex` and `c.Raven`,\nso let's see what an effect display of an interaction looks like:\n\n\n::: {.cell hash='index_cache/html/unnamed-chunk-8_c98328889aef006cf198624311d6febe'}\n\n```{.r .cell-code}\n# Construct grid with relevant predictor combinations\nnd1_rav <- expand.grid(\n  n.Sex = c(-0.5, 0.5),\n  # Vary the Raven scores\n  c.Raven = unique(ex1$c.Raven),\n  # Fix c.English at sample mean\n  c.English = 0\n)\n# Add predictions\nnd1_rav$Prediction <- predict(mod1, newdata = nd1_rav)\n\n# Decentre/relabel predictors\nnd1_rav$Raven <- nd1_rav$c.Raven + mean(ex1$Raven.Right)\nnd1_rav$Sex <- ifelse(nd1_rav$n.Sex == -0.5, \"woman\", \"man\")\n\n# Plot\nggplot(nd1_rav,\n       aes(x = Raven,\n           y = Prediction,\n           colour = Sex)) +\n  geom_line()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.svg)\n:::\n:::\n\n\nIncidentally, I wouldn't read too much into this interaction\nsince there are considerably better ways to analyse this dataset.\nThe aim here was to illustrate how to draw such plots,\nnot to compare different methods of analysis.\n\n## Logistic regression\n\n### Data\nIn the second and third example we will apply the \nsame procedure as in the first example\nto logistic regression model. The dataset is from \n[Vanhove & Berthele (2015)](http://homeweb.unifr.ch/VanhoveJ/Pub/papers/ItemRelatedDeterminants.pdf),\nand the goal in both cases is to model and visualise\nthe relationship between a cognate pair's orthographic Levenshtein distance\n(the larger the distance, \nthe less orthographic overlap the cognates have)\nand their corpus frequency (`log.FreqGermanic`; \na logarithmically transformed frequency measure) on the one hand\nand the probability that readers will spot \nthe cognate relationship on the other hand.\n\nFor the present example, we will model the data from a single,\nrandomly chosen participant, viz. `DB3`, so that the data\ncan be analysed in a straightforward logistic regression model;\nfor the next example, we'll analyse the data for all participants\nsimultaneously in a mixed-effects model.\n\n\n::: {.cell hash='index_cache/html/unnamed-chunk-9_513a6245fba98a7899581555cdce9feb'}\n\n```{.r .cell-code}\n# Read in the data\nex2 <- read.csv(\"http://homeweb.unifr.ch/VanhoveJ/Pub/Data/ExampleLogisticRegression.csv\",\n                stringsAsFactors = TRUE)\n# Retain only the observations for participant `DB3`:\nex2 <- droplevels(subset(ex2, Subject == \"DB3\"))\nstr(ex2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t180 obs. of  8 variables:\n $ Subject         : Factor w/ 1 level \"DB3\": 1 1 1 1 1 1 1 1 1 1 ...\n $ Stimulus        : Factor w/ 180 levels \"aai\",\"aarde\",..: 94 134 35 15 1 5 41 148 55 174 ...\n $ Lx              : Factor w/ 4 levels \"DK\",\"FR\",\"NL\",..: 2 1 2 4 2 4 4 1 3 3 ...\n $ Correct         : int  1 0 0 0 0 0 0 0 1 1 ...\n $ MinLevGermanic  : num  0.2 0.5 0.58 0.4 0.67 0.29 0.58 0.4 0.43 0 ...\n $ log.FreqGermanic: num  6.11 1.18 2.33 1.96 3.26 ...\n $ Sex             : Factor w/ 1 level \"m\": 1 1 1 1 1 1 1 1 1 1 ...\n $ EngReading      : int  2 2 2 2 2 2 2 2 2 2 ...\n```\n:::\n:::\n\n\n### Model\nAs in the first example,\ncentre the predictor variables, just\nto get into the habit:\n\n\n::: {.cell hash='index_cache/html/unnamed-chunk-10_8ce0f1edcf38e82e893e65d15c65f543'}\n\n```{.r .cell-code}\nex2$c.Lev <- c.(ex2$MinLevGermanic)\nex2$clog.Freq <- c.(ex2$log.FreqGermanic)\n```\n:::\n\n\nFit the logistic regression model:\n\n\n::: {.cell hash='index_cache/html/unnamed-chunk-11_19bb2936894ea2ad106bbfce8aafac6b'}\n\n```{.r .cell-code}\nmod2 <- glm(Correct ~ c.Lev + clog.Freq,\n            data = ex2,\n            family = \"binomial\")\n\n# Estimated model coefficients\ncoef(mod2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(Intercept)       c.Lev   clog.Freq \n     -0.331      -3.599       0.212 \n```\n:::\n:::\n\n\n### Effects display\nTo draw an effects display for the Levenshtein variable,\nwe do the exact same thing as in the first example:\nconstruct a dataframe that contains the predictors\nwhose effects we want to plot as well as the predictors \nwhose effects we want to keep constant.\nHere, we want to create a dataframe in which\n`c.Lev` varies along its range and where \n`clog.Freq` is kept constant (e.g., at its sample mean of 0).\nHere I use the `seq()` function rather than `unique()`\nto specify the `c.Lev` values, but either will work.\n\n\n::: {.cell hash='index_cache/html/unnamed-chunk-12_b0fb24db197bb888629fe4590de8e860'}\n\n```{.r .cell-code}\nnd2_lev <- expand.grid(\n  # A sequence of c.Lev values\n  # from the sample minimum\n  # through the sample maximum\n  # in steps of 0.05\n  c.Lev = seq(min(ex2$c.Lev),\n              max(ex2$c.Lev),\n              by = 0.05),\n  # Fix clog.Freq at its sample mean\n  clog.Freq = 0\n)\nhead(nd2_lev)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   c.Lev clog.Freq\n1 -0.361         0\n2 -0.311         0\n3 -0.261         0\n4 -0.211         0\n5 -0.161         0\n6 -0.111         0\n```\n:::\n:::\n\n\nUsing `predict()`, we can again compute the expected\nvalues -- according to the model -- for each combination\nof predictor values in `nd2_lev`. Since this is a\nlogistic model, the predictions are produced in log-odds,\nwhich we can plot:\n\n\n::: {.cell hash='index_cache/html/unnamed-chunk-13_6e872a9ad156552d7cefa8b4f08f513d'}\n\n```{.r .cell-code}\n# Fill in predicted values\nnd2_lev$Prediction <- predict(mod2, nd2_lev)\n\n# Plot Levenshtein effect\nggplot(nd2_lev,\n       aes(x = c.Lev,\n           y = Prediction)) +\n  geom_line() +\n  xlab(\"Centred Levenshtein distance\") +\n  ylab(\"Modelled outcome (in log-odds)\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-13-1.svg)\n:::\n:::\n\n\nThere is one problem: No-one really thinks in log-odds,\nand any audience will more readily understand\nprobabilities than log-odds,\nso it's better to express these predictions as probabilities.\nTo do so, specify the parameter `type` in the `predict()` function\nas `\"response\"`. (Alternatively, apply the logistic function\nto the values in log-odds using `plogis()`.) \nIf we then de-centre the `c.Lev` variable,\nwe can draw an interpretable effect display:\n\n\n::: {.cell hash='index_cache/html/unnamed-chunk-14_04fb881a1663dc415e60740562bc02cb'}\n\n```{.r .cell-code}\n# Fill in predicted values as probabilities\nnd2_lev$Probability <- predict(mod2, nd2_lev,\n                               type = \"response\")\n\n# De-centre c.Lev\nnd2_lev$Levenshtein <- nd2_lev$c.Lev + mean(ex2$MinLevGermanic)\n\n# Plot\nggplot(nd2_lev,\n       aes(x = Levenshtein,\n           y = Probability)) +\n  geom_line() +\n  ylab(\"Modelled probability\\nof correct response\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-14-1.svg)\n:::\n:::\n\n\nImportantly, we modelled the effect linearly in log-odds,\nbut when the effect is expressed in probabilities,\nthis yields a nonlinear curve. This is not surprising\nnor does it tell us anything about what we're investigating:\nif you model something linearly in log-odds,\nthe effect will be nonlinear if expressed in probabilities.\n\nNote, furthermore, that we kept the frequency predictor `clog.Freq`\nconstant at 0 for this plot. If you fix this predictor\nat different values, you'll end up with curves that don't run\nperfectly parallel to each other, as the plot below illustrates.\nThis is different from effects displays for ordinary regression models,\nwhere fixing the non-focus predictors at different values\nproduces parallel lines, and it is due to the log-odds--to--probability\ntransformation.\n\n\n::: {.cell hash='index_cache/html/unnamed-chunk-15_59bc538a668082ac83368112abb7b745'}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-15-1.svg)\n:::\n:::\n\n\nTo avoid making this blog post much too long,\nI'll leave the effect display of the frequency \nvariable as an exercise to the reader.\n\n## Mixed-effects logistic regression\n\n### Data\n\nWe'll use the same dataset as in the second example,\nbut this time we don't restrict the dataset to one\nparticipant.\n\n\n::: {.cell hash='index_cache/html/unnamed-chunk-16_facf69630b05f96f2fb97fdb21647d43'}\n\n```{.r .cell-code}\nex3 <- read.csv(\"http://homeweb.unifr.ch/VanhoveJ/Pub/Data/ExampleLogisticRegression.csv\",\n                stringsAsFactors = TRUE)\n```\n:::\n\n\n### Model\n\nNot that it's really necessary,\nbut since it's a good habit to develop,\ncentre the numeric variables at their sample mean,\nand express the binary predictor `Sex` as\na numeric variable with the values -0.5 and 0.5.\n\n\n::: {.cell hash='index_cache/html/unnamed-chunk-17_4756eba7c4b9f3e062de7ee3a295957c'}\n\n```{.r .cell-code}\n# Centre numeric variables\nex3$c.Lev <- c.(ex3$MinLevGermanic)\nex3$clog.Freq <- c.(ex3$log.FreqGermanic)\nex3$c.Eng <- c.(ex3$EngReading)\n\n# Express Sex as numeric variable (+/- 0.5)\n# where -0.5 = m(an) and 0.5 = w(oman)\nex3$n.Sex <- as.numeric(ex3$Sex) - 1.5\nxtabs(~ n.Sex + Sex, ex3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      Sex\nn.Sex      m     w\n  -0.5  6120     0\n  0.5      0 12060\n```\n:::\n:::\n\n\nFit a logistic mixed-effects regression model\nusing the `glmer()` function from the `lme4` package.\nAll effects are modelled linearly (in log-odds)\nwithout interaction: Levenshtein distance (`c.Lev`),\ncorpus frequency (`clog.Freq`),\nthe participants' English reading skills (`c.Eng`)\nand their sex (`n.Sex`).\nThe model also includes by-item and by-subject random intercepts\nas well as by-item adjustments to the English reading skills slope\nand by-subject adjustments to the Levenshtein effect.\n\n\n::: {.cell hash='index_cache/html/unnamed-chunk-18_f9ca3cf19caebe8c91c82bd617919963'}\n\n```{.r .cell-code}\nlibrary(lme4)\nmod3 <- glmer(Correct ~ c.Lev + clog.Freq +\n                c.Eng + n.Sex +\n                (1 + c.Lev | Subject) +\n                (1 + c.Eng | Stimulus),\n              data = ex3,\n              family = \"binomial\")\n\n# Uncomment the next line to show model\n# summary(mod3)\n```\n:::\n\n\n### Effect display\nFor the mixed-effects model, I'll assume\nthat you want to plot the effect of a predictor\nvariable for an otherwise average item\nand an otherwise average participant, i.e.,\na plot that is **based on the fixed-effect estimates alone**.\nAn alternative would be that you'd plot\nthe effects associated with a specific item\n(taking into account the random-effect adjustments\nfor that specific item), with a specific participant\n(taking into account the random-effect adjustments\nfor that particular participant), or both.\nFor this fixed-effects-only scenario,\nwhich I suspect is usually what is of interest,\nthe logic is the same as in the previous examples.\n\nFirst construct a data frame where the focus predictor\nvaries along its range (for instance, using `unique()` or `seq()`)\nand where the other predictors are fixed at sensible values.\nHere I fix the frequency and the English reading predictor\nat their sample means (0). The `n.Sex` variable, however, \ndoesn't have a sample mean of 0 but of 0.163.\n(There are 67 women and only 34 men in the sample.)\nI fixed `n.Sex` at 0 nonetheless because I want to plot\nthe modelled probabilities for an unknown participant\nof unspecified sex. If instead I wanted to plot the\nmodelled probabilities for an unknown participant\nwho is a 2-to-1 favourite to be a woman, I would use 0.163 instead;\nif I wanted to plot the modelled probabilities\nfor an unknown male participant, I'd use -0.5.\n\n\n::: {.cell hash='index_cache/html/unnamed-chunk-19_05e8f1d1e8c2ba86bc62c2788a8d42d0'}\n\n```{.r .cell-code}\nnd3_lev <- expand.grid(\n  c.Lev = seq(min(ex3$c.Lev),\n              max(ex3$c.Lev),\n              by = 0.05),\n  clog.Freq = 0,\n  c.Eng = 0,\n  n.Sex = 0\n)\n```\n:::\n\n\nThen add the predicted probabilities to this dataframe\n(`type = \"response\"`). The `re.form = NA` bit specifies\nthat we don't want to take into account any random effects.\n\n\n::: {.cell hash='index_cache/html/unnamed-chunk-20_2a63fdb5426ca7e436a846c13eaa775d'}\n\n```{.r .cell-code}\nnd3_lev$Prediction <- predict(mod3, nd3_lev,\n                              type = \"response\",\n                              re.form = NA)\n```\n:::\n\n\nThen plot the results:\n\n\n::: {.cell hash='index_cache/html/unnamed-chunk-21_f5799751f942ed161e4a9dc166d0adb6'}\n\n```{.r .cell-code}\nnd3_lev$Levenshtein <- nd3_lev$c.Lev + mean(ex3$MinLevGermanic)\nggplot(nd3_lev,\n       aes(x = Levenshtein,\n           y = Prediction)) +\n  geom_line()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-21-1.svg)\n:::\n:::\n\n\nAs for the interpretation of this plot, these\nare the probabilities of a correct response\nthat the model predicts \n\n* for a participant of unknown sex (`n.Sex` was set to 0, i.e.,\nthe participant is equally likely to be a man or a woman);\n* whose English reading skills equal the current sample average\n(`c.Eng` was set to 0) \n* and whose cognate guessing\nskills are otherwise average compared to the current sample\n(we didn't take into account any positive or negative by-participant\nadjustments to the overall intercept and `c.Lev` effects)\n* when responding to stimuli with varying Levenshtein\nvalues\n* whose logarithmically transformed corpus frequencies equal the current sample mean (`clog.Freq` was set to 0)\n* and which are otherwise of average difficult compared to the current sample\n(we didn't take into account any positive or negative adjustments to by-stimulus\nadjustments to the overall intercept and the `c.Eng` effects).\n\nA quicker way of putting this is that these are the probabilities\nwith which a participant with average English reading skills of whom\nnothing else is known would respond correctly to stimuli with\nvarying Levenshtein values and average corpus frequencies of which\nnothing else is known either. Again, though, the idea is usually\nnot so much to interpret these probabilities themselves but rather\nto get or give a broad sense of how variation in one predictor\nis associated with variation in the outcome.\n\n\n## Caveats about effect displays\n\nI find effect displays useful to convey regression results,\nbut you can't expect too much from them.\n\nFirst of all, in terms of effect displays,\n**you can only get out of a model what you put into it**.\nFor instance, if you don't model an interaction between two\nvariables, you won't find one in the effect display.\nSimilarly, if you model the effect of a predictor linearly,\nyou won't find a nonlinear effect in the plot -- unless,\nof course, you apply some nonlinear transformation in the process,\nsuch as expressing the effects modelle in a logistic regression\nas probabilities. In the latter case, you're guaranteed\nto find a nonlinear effect.\n\nI labour the latter point because I have seen one or two\ncases where a nonlinear effect emerging from a logistic\nregression was interpreted in subject-matter terms as\nsomething quite surprising. It isn't: it's a direct\nconsequence of how the model works.\n\nThe second caveat is that \"showing the effect\nof one variable while keeping constant the other variables\"\nis **often little more than a convenient fiction**.\nWhile you can use a statistical model to estimate\nhow a person's wage changes when varying \npeople's French reading skills and holding\nconstant their French oral skills, years of education,\nand intelligence, there needn't be anything \nin the real world that corresponds to this 'effect' nor\nwould any results be actionable.\n(How would you go about improving someone's French reading\nskills while keeping their years of education and their French\noral skills constant, anyway?)\nThis caveat is especially relevant in correlational studies\nwhere sets of predictors are highly correlated with each other,\nrendering difficult or even impossible the interpretation\nthe effect of any single 'independent' variable.\n\n\n## Software versions\n\n::: {.cell hash='index_cache/html/unnamed-chunk-22_561f03727a3a96531c6936bbf0359846'}\n\n```{.r .cell-code}\ndevtools::session_info()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n─ Session info ───────────────────────────────────────────────────────────────\n setting  value\n version  R version 4.5.1 (2025-06-13)\n os       Ubuntu 22.04.5 LTS\n system   x86_64, linux-gnu\n ui       X11\n language en_US\n collate  en_US.UTF-8\n ctype    en_US.UTF-8\n tz       Europe/Zurich\n date     2025-09-24\n pandoc   3.4 @ /usr/lib/rstudio/resources/app/bin/quarto/bin/tools/x86_64/ (via rmarkdown)\n\n─ Packages ───────────────────────────────────────────────────────────────────\n package      * version date (UTC) lib source\n boot           1.3-31  2024-08-28 [4] CRAN (R 4.4.2)\n cachem         1.1.0   2024-05-16 [1] CRAN (R 4.5.1)\n callr          3.7.6   2024-03-25 [1] CRAN (R 4.5.1)\n cli            3.6.5   2025-04-23 [1] CRAN (R 4.5.1)\n codetools      0.2-19  2023-02-01 [4] CRAN (R 4.2.2)\n crayon         1.5.1   2022-03-26 [2] CRAN (R 4.2.0)\n devtools       2.4.5   2022-10-11 [1] CRAN (R 4.5.1)\n digest         0.6.37  2024-08-19 [1] CRAN (R 4.5.1)\n dplyr          1.1.4   2023-11-17 [1] CRAN (R 4.5.1)\n ellipsis       0.3.2   2021-04-29 [2] CRAN (R 4.2.0)\n evaluate       1.0.4   2025-06-18 [1] CRAN (R 4.5.1)\n farver         2.1.2   2024-05-13 [1] CRAN (R 4.5.1)\n fastmap        1.2.0   2024-05-15 [1] CRAN (R 4.5.1)\n fs             1.5.2   2021-12-08 [2] CRAN (R 4.2.0)\n generics       0.1.4   2025-05-09 [1] CRAN (R 4.5.1)\n ggplot2      * 3.5.2   2025-04-09 [1] CRAN (R 4.5.1)\n glue           1.6.2   2022-02-24 [2] CRAN (R 4.2.0)\n gtable         0.3.6   2024-10-25 [1] CRAN (R 4.5.1)\n htmltools      0.5.8.1 2024-04-04 [1] CRAN (R 4.5.1)\n htmlwidgets    1.6.4   2023-12-06 [1] CRAN (R 4.5.1)\n httpuv         1.6.16  2025-04-16 [1] CRAN (R 4.5.1)\n jsonlite       2.0.0   2025-03-27 [1] CRAN (R 4.5.1)\n knitr          1.50    2025-03-16 [1] CRAN (R 4.5.1)\n labeling       0.4.3   2023-08-29 [1] CRAN (R 4.5.1)\n later          1.4.2   2025-04-08 [1] CRAN (R 4.5.1)\n lattice        0.22-5  2023-10-24 [4] CRAN (R 4.3.1)\n lifecycle      1.0.4   2023-11-07 [1] CRAN (R 4.5.1)\n lme4         * 1.1-37  2025-03-26 [1] CRAN (R 4.5.1)\n magrittr       2.0.3   2022-03-30 [1] CRAN (R 4.5.1)\n MASS           7.3-65  2025-02-28 [4] CRAN (R 4.4.3)\n Matrix       * 1.7-3   2025-03-11 [4] CRAN (R 4.4.3)\n memoise        2.0.1   2021-11-26 [2] CRAN (R 4.2.0)\n mime           0.10    2021-02-13 [2] CRAN (R 4.0.2)\n miniUI         0.1.2   2025-04-17 [1] CRAN (R 4.5.1)\n minqa          1.2.8   2024-08-17 [1] CRAN (R 4.5.1)\n nlme           3.1-168 2025-03-31 [4] CRAN (R 4.4.3)\n nloptr         2.2.1   2025-03-17 [1] CRAN (R 4.5.1)\n pillar         1.10.2  2025-04-05 [1] CRAN (R 4.5.1)\n pkgbuild       1.3.1   2021-12-20 [2] CRAN (R 4.2.0)\n pkgconfig      2.0.3   2019-09-22 [2] CRAN (R 4.2.0)\n pkgload        1.4.0   2024-06-28 [1] CRAN (R 4.5.1)\n prettyunits    1.1.1   2020-01-24 [2] CRAN (R 4.2.0)\n processx       3.8.6   2025-02-21 [1] CRAN (R 4.5.1)\n profvis        0.4.0   2024-09-20 [1] CRAN (R 4.5.1)\n promises       1.3.3   2025-05-29 [1] CRAN (R 4.5.1)\n ps             1.9.1   2025-04-12 [1] CRAN (R 4.5.1)\n purrr          1.0.4   2025-02-05 [1] CRAN (R 4.5.1)\n R6             2.5.1   2021-08-19 [2] CRAN (R 4.2.0)\n rbibutils      2.3     2024-10-04 [1] CRAN (R 4.5.1)\n RColorBrewer   1.1-3   2022-04-03 [1] CRAN (R 4.5.1)\n Rcpp           1.0.14  2025-01-12 [1] CRAN (R 4.5.1)\n Rdpack         2.6.4   2025-04-09 [1] CRAN (R 4.5.1)\n reformulas     0.4.1   2025-04-30 [1] CRAN (R 4.5.1)\n remotes        2.4.2   2021-11-30 [2] CRAN (R 4.2.0)\n rlang          1.1.6   2025-04-11 [1] CRAN (R 4.5.1)\n rmarkdown      2.29    2024-11-04 [1] CRAN (R 4.5.1)\n rstudioapi     0.17.1  2024-10-22 [1] CRAN (R 4.5.1)\n scales         1.4.0   2025-04-24 [1] CRAN (R 4.5.1)\n sessioninfo    1.2.2   2021-12-06 [2] CRAN (R 4.2.0)\n shiny          1.10.0  2024-12-14 [1] CRAN (R 4.5.1)\n tibble         3.3.0   2025-06-08 [1] CRAN (R 4.5.1)\n tidyselect     1.2.1   2024-03-11 [1] CRAN (R 4.5.1)\n urlchecker     1.0.1   2021-11-30 [1] CRAN (R 4.5.1)\n usethis        3.1.0   2024-11-26 [1] CRAN (R 4.5.1)\n vctrs          0.6.5   2023-12-01 [1] CRAN (R 4.5.1)\n withr          3.0.2   2024-10-28 [1] CRAN (R 4.5.1)\n xfun           0.52    2025-04-02 [1] CRAN (R 4.5.1)\n xtable         1.8-4   2019-04-21 [1] CRAN (R 4.5.1)\n yaml           2.3.5   2022-02-21 [2] CRAN (R 4.2.0)\n\n [1] /home/jan/R/x86_64-pc-linux-gnu-library/4.5\n [2] /usr/local/lib/R/site-library\n [3] /usr/lib/R/site-library\n [4] /usr/lib/R/library\n\n──────────────────────────────────────────────────────────────────────────────\n```\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}