on:
  push:
    branches: [master]

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Install R packages
        run: |
          Rscript -e 'install.packages("shinylive", repos="https://cloud.r-project.org")'

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}